// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../../core/resource';
import * as AuthorsAPI from './authors';
import {
  AuthorAttachToLangGroupParams,
  AuthorCreateBatchParams,
  AuthorCreateLanguageVariationParams,
  AuthorCreateParams,
  AuthorDeleteBatchParams,
  AuthorDeleteParams,
  AuthorDetachFromLangGroupParams,
  AuthorGetBatchParams,
  AuthorGetParams,
  AuthorListParams,
  AuthorSetNewLangPrimaryParams,
  AuthorUpdateBatchParams,
  AuthorUpdateLanguagesParams,
  AuthorUpdateParams,
  Authors,
  BatchInputBlogAuthor,
  BatchResponseBlogAuthor,
  BatchResponseBlogAuthorWithErrors,
  BlogAuthor,
  BlogAuthorCloneRequestVNext,
  BlogAuthorsPage,
  CollectionResponseWithTotalBlogAuthorForwardPaging,
} from './authors';
import * as SettingsAPI from './settings';
import {
  Blog,
  BlogLanguageCloneRequestVNext,
  BlogsPage,
  CollectionResponseWithTotalBlogForwardPaging,
  CollectionResponseWithTotalVersionBlog,
  SettingAttachToLangGroupParams,
  SettingCreateLanguageVariationParams,
  SettingDetachFromLangGroupParams,
  SettingGetRevisionParams,
  SettingListParams,
  SettingListRevisionsParams,
  SettingSetNewLangPrimaryParams,
  SettingUpdateLanguagesParams,
  Settings,
  VersionBlog,
  VersionBlogsPage,
} from './settings';
import * as TagsAPI from './tags';
import {
  BatchInputTag,
  BatchResponseTag,
  BatchResponseTagWithErrors,
  CollectionResponseWithTotalTagForwardPaging,
  Tag,
  TagAttachToLangGroupParams,
  TagCloneRequestVNext,
  TagCreateBatchParams,
  TagCreateLangVariationParams,
  TagCreateParams,
  TagDeleteBatchParams,
  TagDeleteParams,
  TagDetachFromLangGroupParams,
  TagGetBatchParams,
  TagGetParams,
  TagListParams,
  TagSetLangPrimaryParams,
  TagUpdateBatchParams,
  TagUpdateLangsParams,
  TagUpdateParams,
  Tags,
  TagsPage,
} from './tags';
import * as PostsAPI from './posts/posts';
import {
  BatchInputBlogPost,
  BatchResponseBlogPost,
  BatchResponseBlogPostWithErrors,
  BlogPost,
  BlogPostLanguageCloneRequestVNext,
  BlogPostsPage,
  CollectionResponseWithTotalBlogPostForwardPaging,
  CollectionResponseWithTotalVersionBlogPost,
  ContentLanguageVariation,
  PostAttachToLangGroupParams,
  PostCloneParams,
  PostCreateLangVariationParams,
  PostCreateParams,
  PostDeleteParams,
  PostDetachFromLangGroupParams,
  PostGetParams,
  PostGetPreviousVersionParams,
  PostGetPreviousVersionsParams,
  PostListParams,
  PostRestorePreviousVersionParams,
  PostRestorePreviousVersionToDraftParams,
  PostScheduleParams,
  PostSetLangPrimaryParams,
  PostUpdateDraftParams,
  PostUpdateLangsParams,
  PostUpdateParams,
  Posts,
  VersionBlogPost,
  VersionBlogPostsPage,
} from './posts/posts';

export class Blogs extends APIResource {
  authors: AuthorsAPI.Authors = new AuthorsAPI.Authors(this._client);
  posts: PostsAPI.Posts = new PostsAPI.Posts(this._client);
  settings: SettingsAPI.Settings = new SettingsAPI.Settings(this._client);
  tags: TagsAPI.Tags = new TagsAPI.Tags(this._client);
}

Blogs.Authors = Authors;
Blogs.Posts = Posts;
Blogs.Settings = Settings;
Blogs.Tags = Tags;

export declare namespace Blogs {
  export {
    Authors as Authors,
    type BatchInputBlogAuthor as BatchInputBlogAuthor,
    type BatchResponseBlogAuthor as BatchResponseBlogAuthor,
    type BatchResponseBlogAuthorWithErrors as BatchResponseBlogAuthorWithErrors,
    type BlogAuthor as BlogAuthor,
    type BlogAuthorCloneRequestVNext as BlogAuthorCloneRequestVNext,
    type CollectionResponseWithTotalBlogAuthorForwardPaging as CollectionResponseWithTotalBlogAuthorForwardPaging,
    type BlogAuthorsPage as BlogAuthorsPage,
    type AuthorCreateParams as AuthorCreateParams,
    type AuthorUpdateParams as AuthorUpdateParams,
    type AuthorListParams as AuthorListParams,
    type AuthorDeleteParams as AuthorDeleteParams,
    type AuthorAttachToLangGroupParams as AuthorAttachToLangGroupParams,
    type AuthorCreateBatchParams as AuthorCreateBatchParams,
    type AuthorCreateLanguageVariationParams as AuthorCreateLanguageVariationParams,
    type AuthorDeleteBatchParams as AuthorDeleteBatchParams,
    type AuthorDetachFromLangGroupParams as AuthorDetachFromLangGroupParams,
    type AuthorGetParams as AuthorGetParams,
    type AuthorGetBatchParams as AuthorGetBatchParams,
    type AuthorSetNewLangPrimaryParams as AuthorSetNewLangPrimaryParams,
    type AuthorUpdateBatchParams as AuthorUpdateBatchParams,
    type AuthorUpdateLanguagesParams as AuthorUpdateLanguagesParams,
  };

  export {
    Posts as Posts,
    type BatchInputBlogPost as BatchInputBlogPost,
    type BatchResponseBlogPost as BatchResponseBlogPost,
    type BatchResponseBlogPostWithErrors as BatchResponseBlogPostWithErrors,
    type BlogPost as BlogPost,
    type BlogPostLanguageCloneRequestVNext as BlogPostLanguageCloneRequestVNext,
    type CollectionResponseWithTotalBlogPostForwardPaging as CollectionResponseWithTotalBlogPostForwardPaging,
    type CollectionResponseWithTotalVersionBlogPost as CollectionResponseWithTotalVersionBlogPost,
    type ContentLanguageVariation as ContentLanguageVariation,
    type VersionBlogPost as VersionBlogPost,
    type BlogPostsPage as BlogPostsPage,
    type VersionBlogPostsPage as VersionBlogPostsPage,
    type PostCreateParams as PostCreateParams,
    type PostUpdateParams as PostUpdateParams,
    type PostListParams as PostListParams,
    type PostDeleteParams as PostDeleteParams,
    type PostAttachToLangGroupParams as PostAttachToLangGroupParams,
    type PostCloneParams as PostCloneParams,
    type PostCreateLangVariationParams as PostCreateLangVariationParams,
    type PostDetachFromLangGroupParams as PostDetachFromLangGroupParams,
    type PostGetParams as PostGetParams,
    type PostGetPreviousVersionParams as PostGetPreviousVersionParams,
    type PostGetPreviousVersionsParams as PostGetPreviousVersionsParams,
    type PostRestorePreviousVersionParams as PostRestorePreviousVersionParams,
    type PostRestorePreviousVersionToDraftParams as PostRestorePreviousVersionToDraftParams,
    type PostScheduleParams as PostScheduleParams,
    type PostSetLangPrimaryParams as PostSetLangPrimaryParams,
    type PostUpdateDraftParams as PostUpdateDraftParams,
    type PostUpdateLangsParams as PostUpdateLangsParams,
  };

  export {
    Settings as Settings,
    type Blog as Blog,
    type BlogLanguageCloneRequestVNext as BlogLanguageCloneRequestVNext,
    type CollectionResponseWithTotalBlogForwardPaging as CollectionResponseWithTotalBlogForwardPaging,
    type CollectionResponseWithTotalVersionBlog as CollectionResponseWithTotalVersionBlog,
    type VersionBlog as VersionBlog,
    type BlogsPage as BlogsPage,
    type VersionBlogsPage as VersionBlogsPage,
    type SettingListParams as SettingListParams,
    type SettingAttachToLangGroupParams as SettingAttachToLangGroupParams,
    type SettingCreateLanguageVariationParams as SettingCreateLanguageVariationParams,
    type SettingDetachFromLangGroupParams as SettingDetachFromLangGroupParams,
    type SettingGetRevisionParams as SettingGetRevisionParams,
    type SettingListRevisionsParams as SettingListRevisionsParams,
    type SettingSetNewLangPrimaryParams as SettingSetNewLangPrimaryParams,
    type SettingUpdateLanguagesParams as SettingUpdateLanguagesParams,
  };

  export {
    Tags as Tags,
    type BatchInputTag as BatchInputTag,
    type BatchResponseTag as BatchResponseTag,
    type BatchResponseTagWithErrors as BatchResponseTagWithErrors,
    type CollectionResponseWithTotalTagForwardPaging as CollectionResponseWithTotalTagForwardPaging,
    type Tag as Tag,
    type TagCloneRequestVNext as TagCloneRequestVNext,
    type TagsPage as TagsPage,
    type TagCreateParams as TagCreateParams,
    type TagUpdateParams as TagUpdateParams,
    type TagListParams as TagListParams,
    type TagDeleteParams as TagDeleteParams,
    type TagAttachToLangGroupParams as TagAttachToLangGroupParams,
    type TagCreateBatchParams as TagCreateBatchParams,
    type TagCreateLangVariationParams as TagCreateLangVariationParams,
    type TagDeleteBatchParams as TagDeleteBatchParams,
    type TagDetachFromLangGroupParams as TagDetachFromLangGroupParams,
    type TagGetParams as TagGetParams,
    type TagGetBatchParams as TagGetBatchParams,
    type TagSetLangPrimaryParams as TagSetLangPrimaryParams,
    type TagUpdateBatchParams as TagUpdateBatchParams,
    type TagUpdateLangsParams as TagUpdateLangsParams,
  };
}
