// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import path from 'node:path';
import util from 'node:util';
import Fuse from 'fuse.js';
import ts from 'typescript';
import { WorkerOutput } from './code-tool-types';
import { HubSpot, ClientOptions } from '@hubspot/sdk';

async function tseval(code: string) {
  return import('data:application/typescript;charset=utf-8;base64,' + Buffer.from(code).toString('base64'));
}

function getRunFunctionSource(code: string): {
  type: 'declaration' | 'expression';
  client: string | undefined;
  code: string;
} | null {
  const sourceFile = ts.createSourceFile('code.ts', code, ts.ScriptTarget.Latest, true);
  const printer = ts.createPrinter();

  for (const statement of sourceFile.statements) {
    // Check for top-level function declarations
    if (ts.isFunctionDeclaration(statement)) {
      if (statement.name?.text === 'run') {
        return {
          type: 'declaration',
          client: statement.parameters[0]?.name.getText(),
          code: printer.printNode(ts.EmitHint.Unspecified, statement.body!, sourceFile),
        };
      }
    }

    // Check for variable declarations: const run = () => {} or const run = function() {}
    if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        if (
          ts.isIdentifier(declaration.name) &&
          declaration.name.text === 'run' &&
          // Check if it's initialized with a function
          declaration.initializer &&
          (ts.isFunctionExpression(declaration.initializer) || ts.isArrowFunction(declaration.initializer))
        ) {
          return {
            type: 'expression',
            client: declaration.initializer.parameters[0]?.name.getText(),
            code: printer.printNode(ts.EmitHint.Unspecified, declaration.initializer, sourceFile),
          };
        }
      }
    }
  }

  return null;
}

function getTSDiagnostics(code: string): string[] {
  const functionSource = getRunFunctionSource(code)!;
  const codeWithImport = [
    'import { HubSpot } from "@hubspot/sdk";',
    functionSource.type === 'declaration' ?
      `async function run(${functionSource.client}: HubSpot)`
    : `const run: (${functionSource.client}: HubSpot) => Promise<unknown> =`,
    functionSource.code,
  ].join('\n');
  const sourcePath = path.resolve('code.ts');
  const ast = ts.createSourceFile(sourcePath, codeWithImport, ts.ScriptTarget.Latest, true);
  const options = ts.getDefaultCompilerOptions();
  options.target = ts.ScriptTarget.Latest;
  options.module = ts.ModuleKind.NodeNext;
  options.moduleResolution = ts.ModuleResolutionKind.NodeNext;
  const host = ts.createCompilerHost(options, true);
  const newHost: typeof host = {
    ...host,
    getSourceFile: (...args) => {
      if (path.resolve(args[0]) === sourcePath) {
        return ast;
      }
      return host.getSourceFile(...args);
    },
    readFile: (...args) => {
      if (path.resolve(args[0]) === sourcePath) {
        return codeWithImport;
      }
      return host.readFile(...args);
    },
    fileExists: (...args) => {
      if (path.resolve(args[0]) === sourcePath) {
        return true;
      }
      return host.fileExists(...args);
    },
  };
  const program = ts.createProgram({
    options,
    rootNames: [sourcePath],
    host: newHost,
  });
  const diagnostics = ts.getPreEmitDiagnostics(program, ast);
  return diagnostics.map((d) => {
    const message = ts.flattenDiagnosticMessageText(d.messageText, '\n');
    if (!d.file || !d.start) return `- ${message}`;
    const { line: lineNumber } = ts.getLineAndCharacterOfPosition(d.file, d.start);
    const line = codeWithImport.split('\n').at(lineNumber)?.trim();
    return line ? `- ${message}\n    ${line}` : `- ${message}`;
  });
}

const fuse = new Fuse(
  [
    'client.account.get',
    'client.account.getDailyPrivateAppsUsage',
    'client.account.activity.listAuditLogs',
    'client.account.activity.listLoginActivities',
    'client.account.activity.listSecurityActivities',
    'client.auth.oauth.createToken',
    'client.auth.oauth.introspectToken',
    'client.auth.oauth.revokeToken',
    'client.automation.actions.callbacks.complete',
    'client.automation.actions.callbacks.completeBatch',
    'client.automation.actions.definitions.create',
    'client.automation.actions.definitions.createRequiresObject',
    'client.automation.actions.definitions.delete',
    'client.automation.actions.definitions.get',
    'client.automation.actions.definitions.getRequiresObject',
    'client.automation.actions.definitions.list',
    'client.automation.actions.definitions.update',
    'client.automation.actions.functions.createOrReplace',
    'client.automation.actions.functions.createOrReplaceByFunctionType',
    'client.automation.actions.functions.delete',
    'client.automation.actions.functions.deleteByFunctionType',
    'client.automation.actions.functions.get',
    'client.automation.actions.functions.getByFunctionType',
    'client.automation.actions.functions.list',
    'client.automation.actions.revisions.get',
    'client.automation.actions.revisions.list',
    'client.automation.sequences.createEnrollment',
    'client.automation.sequences.get',
    'client.automation.sequences.getEnrollmentByContactID',
    'client.automation.sequences.list',
    'client.businessUnits.businessUnitEntries.getByUserID',
    'client.cms.auditLogs.export',
    'client.cms.auditLogs.list',
    'client.cms.blogs.authors.attachToLangGroup',
    'client.cms.blogs.authors.create',
    'client.cms.blogs.authors.createLanguageVariation',
    'client.cms.blogs.authors.delete',
    'client.cms.blogs.authors.detachFromLangGroup',
    'client.cms.blogs.authors.get',
    'client.cms.blogs.authors.getCursor',
    'client.cms.blogs.authors.getCursorByQuery',
    'client.cms.blogs.authors.getPostsCursor',
    'client.cms.blogs.authors.getPostsCursorByQuery',
    'client.cms.blogs.authors.getTagsCursor',
    'client.cms.blogs.authors.getTagsCursorByQuery',
    'client.cms.blogs.authors.list',
    'client.cms.blogs.authors.setNewLangPrimary',
    'client.cms.blogs.authors.update',
    'client.cms.blogs.authors.updateLanguages',
    'client.cms.blogs.authors.batch.create',
    'client.cms.blogs.authors.batch.delete',
    'client.cms.blogs.authors.batch.get',
    'client.cms.blogs.authors.batch.update',
    'client.cms.blogs.posts.clone',
    'client.cms.blogs.posts.create',
    'client.cms.blogs.posts.delete',
    'client.cms.blogs.posts.get',
    'client.cms.blogs.posts.getDraftByID',
    'client.cms.blogs.posts.list',
    'client.cms.blogs.posts.listAuthors',
    'client.cms.blogs.posts.listTags',
    'client.cms.blogs.posts.pushLive',
    'client.cms.blogs.posts.query',
    'client.cms.blogs.posts.queryAuthors',
    'client.cms.blogs.posts.queryTags',
    'client.cms.blogs.posts.resetDraft',
    'client.cms.blogs.posts.schedule',
    'client.cms.blogs.posts.update',
    'client.cms.blogs.posts.updateDraft',
    'client.cms.blogs.posts.batch.create',
    'client.cms.blogs.posts.batch.delete',
    'client.cms.blogs.posts.batch.get',
    'client.cms.blogs.posts.batch.update',
    'client.cms.blogs.posts.multiLanguage.attachToLangGroup',
    'client.cms.blogs.posts.multiLanguage.createLangVariation',
    'client.cms.blogs.posts.multiLanguage.detachFromLangGroup',
    'client.cms.blogs.posts.multiLanguage.setLangPrimary',
    'client.cms.blogs.posts.multiLanguage.updateLangs',
    'client.cms.blogs.posts.revisions.getPreviousVersion',
    'client.cms.blogs.posts.revisions.getPreviousVersions',
    'client.cms.blogs.posts.revisions.restorePreviousVersion',
    'client.cms.blogs.posts.revisions.restorePreviousVersionToDraft',
    'client.cms.blogs.settings.get',
    'client.cms.blogs.settings.getRevision',
    'client.cms.blogs.settings.list',
    'client.cms.blogs.settings.listRevisions',
    'client.cms.blogs.settings.multiLanguage.attachToLangGroup',
    'client.cms.blogs.settings.multiLanguage.createLanguageVariation',
    'client.cms.blogs.settings.multiLanguage.detachFromLangGroup',
    'client.cms.blogs.settings.multiLanguage.setNewLangPrimary',
    'client.cms.blogs.settings.multiLanguage.updateLanguages',
    'client.cms.blogs.tags.attachToLangGroup',
    'client.cms.blogs.tags.create',
    'client.cms.blogs.tags.createLangVariation',
    'client.cms.blogs.tags.delete',
    'client.cms.blogs.tags.detachFromLangGroup',
    'client.cms.blogs.tags.get',
    'client.cms.blogs.tags.list',
    'client.cms.blogs.tags.listAuthorsCursor',
    'client.cms.blogs.tags.listAuthorsCursorByQuery',
    'client.cms.blogs.tags.listCursor',
    'client.cms.blogs.tags.listCursorByQuery',
    'client.cms.blogs.tags.listPostsCursor',
    'client.cms.blogs.tags.listPostsCursorByQuery',
    'client.cms.blogs.tags.setLangPrimary',
    'client.cms.blogs.tags.update',
    'client.cms.blogs.tags.updateLangs',
    'client.cms.blogs.tags.batch.createBatch',
    'client.cms.blogs.tags.batch.delete',
    'client.cms.blogs.tags.batch.getBatch',
    'client.cms.blogs.tags.batch.updateBatch',
    'client.cms.domains.get',
    'client.cms.domains.list',
    'client.cms.hubdb.rows.cloneBatch',
    'client.cms.hubdb.rows.cloneDraft',
    'client.cms.hubdb.rows.create',
    'client.cms.hubdb.rows.createBatch',
    'client.cms.hubdb.rows.deleteDraft',
    'client.cms.hubdb.rows.get',
    'client.cms.hubdb.rows.getBatch',
    'client.cms.hubdb.rows.getDraft',
    'client.cms.hubdb.rows.getDraftBatch',
    'client.cms.hubdb.rows.list',
    'client.cms.hubdb.rows.purgeBatch',
    'client.cms.hubdb.rows.replaceBatch',
    'client.cms.hubdb.rows.replaceDraft',
    'client.cms.hubdb.rows.updateBatch',
    'client.cms.hubdb.rows.updateDraft',
    'client.cms.hubdb.tables.cloneDraft',
    'client.cms.hubdb.tables.create',
    'client.cms.hubdb.tables.delete',
    'client.cms.hubdb.tables.deleteVersion',
    'client.cms.hubdb.tables.export',
    'client.cms.hubdb.tables.exportDraft',
    'client.cms.hubdb.tables.get',
    'client.cms.hubdb.tables.getDraft',
    'client.cms.hubdb.tables.importDraft',
    'client.cms.hubdb.tables.list',
    'client.cms.hubdb.tables.listDraft',
    'client.cms.hubdb.tables.publishDraft',
    'client.cms.hubdb.tables.resetDraft',
    'client.cms.hubdb.tables.unpublish',
    'client.cms.hubdb.tables.updateDraft',
    'client.cms.mediaBridge.createAssociation',
    'client.cms.mediaBridge.createAttentionSpanEvent',
    'client.cms.mediaBridge.createMediaPlayedEvent',
    'client.cms.mediaBridge.createMediaPlayedPercentEvent',
    'client.cms.mediaBridge.createObjectType',
    'client.cms.mediaBridge.createOembedDomain',
    'client.cms.mediaBridge.createProperty',
    'client.cms.mediaBridge.createPropertyGroup',
    'client.cms.mediaBridge.createVideoAssociationDefinition',
    'client.cms.mediaBridge.deleteAssociation',
    'client.cms.mediaBridge.deleteOembedDomain',
    'client.cms.mediaBridge.deleteProperty',
    'client.cms.mediaBridge.deletePropertyGroup',
    'client.cms.mediaBridge.getEventVisibilitySettings',
    'client.cms.mediaBridge.getOembedDomain',
    'client.cms.mediaBridge.getProperty',
    'client.cms.mediaBridge.getPropertyGroup',
    'client.cms.mediaBridge.getSchema',
    'client.cms.mediaBridge.listObjectTypesByMediaType',
    'client.cms.mediaBridge.listOembedDomains',
    'client.cms.mediaBridge.listProperties',
    'client.cms.mediaBridge.listPropertyGroups',
    'client.cms.mediaBridge.listSchemas',
    'client.cms.mediaBridge.registerAppName',
    'client.cms.mediaBridge.updateEventVisibilitySettings',
    'client.cms.mediaBridge.updateOembedDomain',
    'client.cms.mediaBridge.updateProperty',
    'client.cms.mediaBridge.updatePropertyGroup',
    'client.cms.mediaBridge.updateSchema',
    'client.cms.mediaBridge.updateSettings',
    'client.cms.mediaBridge.batch.create',
    'client.cms.mediaBridge.batch.delete',
    'client.cms.mediaBridge.batch.get',
    'client.cms.pages.getLandingPageRevision',
    'client.cms.pages.getSitePageRevision',
    'client.cms.pages.listLandingPageRevisions',
    'client.cms.pages.listSitePageRevisions',
    'client.cms.pages.resetSitePageDraft',
    'client.cms.pages.restoreLandingPageRevision',
    'client.cms.pages.restoreLandingPageRevisionToDraft',
    'client.cms.pages.restoreSitePageRevision',
    'client.cms.pages.restoreSitePageRevisionToDraft',
    'client.cms.pages.aBTests.createLandingPageVariation',
    'client.cms.pages.aBTests.createSitePageVariation',
    'client.cms.pages.aBTests.endLandingPageTest',
    'client.cms.pages.aBTests.endSitePageTest',
    'client.cms.pages.aBTests.rerunLandingPageTest',
    'client.cms.pages.aBTests.rerunSitePageTest',
    'client.cms.pages.batch.createFolders',
    'client.cms.pages.batch.createLandingPages',
    'client.cms.pages.batch.createSitePages',
    'client.cms.pages.batch.deleteFolders',
    'client.cms.pages.batch.deleteLandingPages',
    'client.cms.pages.batch.deleteSitePages',
    'client.cms.pages.batch.getLandingPages',
    'client.cms.pages.batch.getSitePages',
    'client.cms.pages.batch.updateFolders',
    'client.cms.pages.batch.updateLandingPages',
    'client.cms.pages.batch.updateSitePages',
    'client.cms.pages.folders.batchGet',
    'client.cms.pages.folders.create',
    'client.cms.pages.folders.delete',
    'client.cms.pages.folders.get',
    'client.cms.pages.folders.getRevision',
    'client.cms.pages.folders.list',
    'client.cms.pages.folders.listRevisions',
    'client.cms.pages.folders.restoreRevision',
    'client.cms.pages.folders.update',
    'client.cms.pages.landingPages.clone',
    'client.cms.pages.landingPages.create',
    'client.cms.pages.landingPages.delete',
    'client.cms.pages.landingPages.get',
    'client.cms.pages.landingPages.getDraft',
    'client.cms.pages.landingPages.list',
    'client.cms.pages.landingPages.pushDraftLive',
    'client.cms.pages.landingPages.resetDraft',
    'client.cms.pages.landingPages.schedule',
    'client.cms.pages.landingPages.update',
    'client.cms.pages.landingPages.updateDraft',
    'client.cms.pages.multiLanguage.attachToLangGroup',
    'client.cms.pages.multiLanguage.createLanguageVariation',
    'client.cms.pages.multiLanguage.detachFromLangGroup',
    'client.cms.pages.multiLanguage.setNewLangPrimary',
    'client.cms.pages.multiLanguage.updateLanguages',
    'client.cms.pages.websitePages.clone',
    'client.cms.pages.websitePages.create',
    'client.cms.pages.websitePages.delete',
    'client.cms.pages.websitePages.get',
    'client.cms.pages.websitePages.getDraft',
    'client.cms.pages.websitePages.list',
    'client.cms.pages.websitePages.publishDraft',
    'client.cms.pages.websitePages.schedule',
    'client.cms.pages.websitePages.setNewLangPrimary',
    'client.cms.pages.websitePages.update',
    'client.cms.pages.websitePages.updateDraft',
    'client.cms.siteSearch.getIndexedData',
    'client.cms.siteSearch.search',
    'client.cms.sourceCode.extractAsync',
    'client.cms.sourceCode.getExtractionStatus',
    'client.cms.urlMappings.create',
    'client.cms.urlMappings.delete',
    'client.cms.urlMappings.get',
    'client.cms.urlMappings.list',
    'client.cms.urlRedirects.create',
    'client.cms.urlRedirects.delete',
    'client.cms.urlRedirects.get',
    'client.cms.urlRedirects.list',
    'client.cms.urlRedirects.update',
    'client.communicationPreferences.generateLinks',
    'client.communicationPreferences.getStatuses',
    'client.communicationPreferences.getUnsubscribeAllStatus',
    'client.communicationPreferences.unsubscribeAll',
    'client.communicationPreferences.updateStatus',
    'client.communicationPreferences.definitions.list',
    'client.communicationPreferences.statuses.batch.getUnsubscribeAllStatuses',
    'client.communicationPreferences.statuses.batch.read',
    'client.communicationPreferences.statuses.batch.unsubscribeAll',
    'client.communicationPreferences.statuses.batch.updateStatuses',
    'client.conversations.customChannels.create',
    'client.conversations.customChannels.delete',
    'client.conversations.customChannels.get',
    'client.conversations.customChannels.list',
    'client.conversations.customChannels.update',
    'client.conversations.customChannels.channelAccounts.create',
    'client.conversations.customChannels.channelAccounts.list',
    'client.conversations.customChannels.channelAccounts.update',
    'client.conversations.customChannels.channelAccounts.updateStagingToken',
    'client.conversations.customChannels.messages.create',
    'client.conversations.customChannels.messages.get',
    'client.conversations.customChannels.messages.update',
    'client.conversations.visitorIdentification.generateToken',
    'client.crm.appUninstalls.uninstall',
    'client.crm.associations.delete',
    'client.crm.associations.list',
    'client.crm.associations.requestHighUsageReport',
    'client.crm.associations.search',
    'client.crm.associations.updateAssociationLabels',
    'client.crm.associations.batch.create',
    'client.crm.associations.batch.createDefault',
    'client.crm.associations.batch.delete',
    'client.crm.associations.batch.deleteLabels',
    'client.crm.associations.batch.get',
    'client.crm.associationsSchema.labels.batchCreate',
    'client.crm.associationsSchema.labels.createLabel',
    'client.crm.associationsSchema.labels.deleteLabel',
    'client.crm.associationsSchema.labels.listLabels',
    'client.crm.associationsSchema.labels.updateLabel',
    'client.crm.associationsSchema.limits.batchDelete',
    'client.crm.associationsSchema.limits.batchUpdate',
    'client.crm.associationsSchema.limits.getByObjectTypes',
    'client.crm.associationsSchema.limits.list',
    'client.crm.dealSplits.batch.read',
    'client.crm.dealSplits.batch.upsert',
    'client.crm.exports.createAsync',
    'client.crm.exports.get',
    'client.crm.exports.getStatus',
    'client.crm.extensions.calling.createChannelConnectionSettings',
    'client.crm.extensions.calling.createInboundCall',
    'client.crm.extensions.calling.createRecordingReady',
    'client.crm.extensions.calling.createRecordingSettings',
    'client.crm.extensions.calling.createSettings',
    'client.crm.extensions.calling.deleteChannelConnectionSettings',
    'client.crm.extensions.calling.deleteSettings',
    'client.crm.extensions.calling.getChannelConnectionSettings',
    'client.crm.extensions.calling.getRecordingSettings',
    'client.crm.extensions.calling.getSettings',
    'client.crm.extensions.calling.updateChannelConnectionSettings',
    'client.crm.extensions.calling.updateRecordingSettings',
    'client.crm.extensions.calling.updateSettings',
    'client.crm.extensions.calling.transcripts.create',
    'client.crm.extensions.calling.transcripts.createInboundCall',
    'client.crm.extensions.calling.transcripts.delete',
    'client.crm.extensions.calling.transcripts.get',
    'client.crm.extensions.cardsDev.create',
    'client.crm.extensions.cardsDev.delete',
    'client.crm.extensions.cardsDev.get',
    'client.crm.extensions.cardsDev.getByID',
    'client.crm.extensions.cardsDev.getSampleResponse',
    'client.crm.extensions.cardsDev.migrateViews',
    'client.crm.extensions.cardsDev.update',
    'client.crm.extensions.videoConferencing.delete',
    'client.crm.extensions.videoConferencing.get',
    'client.crm.extensions.videoConferencing.update',
    'client.crm.featureFlags.delete',
    'client.crm.featureFlags.deletePortalState',
    'client.crm.featureFlags.get',
    'client.crm.featureFlags.getPortalState',
    'client.crm.featureFlags.listAll',
    'client.crm.featureFlags.listPortals',
    'client.crm.featureFlags.update',
    'client.crm.featureFlags.updatePortalState',
    'client.crm.featureFlags.batch.delete',
    'client.crm.featureFlags.batch.upsert',
    'client.crm.imports.cancel',
    'client.crm.imports.create',
    'client.crm.imports.get',
    'client.crm.imports.list',
    'client.crm.imports.listErrors',
    'client.crm.limits.getAssociationLabelLimits',
    'client.crm.limits.getAssociationRecordsLimitsByObjectType',
    'client.crm.limits.getAssociationRecordsLimitsFromObjects',
    'client.crm.limits.getAssociationRecordsLimitsToObjects',
    'client.crm.limits.getCalculatedPropertyLimits',
    'client.crm.limits.getCustomObjectTypeLimits',
    'client.crm.limits.getCustomPropertyLimits',
    'client.crm.limits.getPipelineLimits',
    'client.crm.limits.getRecordLimits',
    'client.crm.lists.addAndRemoveMemberships',
    'client.crm.lists.addMemberships',
    'client.crm.lists.addMembershipsFrom',
    'client.crm.lists.batchReadMemberships',
    'client.crm.lists.create',
    'client.crm.lists.createFolder',
    'client.crm.lists.createIDMapping',
    'client.crm.lists.delete',
    'client.crm.lists.deleteFolder',
    'client.crm.lists.deleteMemberships',
    'client.crm.lists.get',
    'client.crm.lists.getByObjectTypeAndName',
    'client.crm.lists.getIDMapping',
    'client.crm.lists.getMembershipsJoinOrder',
    'client.crm.lists.getRecordMemberships',
    'client.crm.lists.getScheduleConversion',
    'client.crm.lists.getSizeAndEditsHistoryBetween',
    'client.crm.lists.list',
    'client.crm.lists.listBySearch',
    'client.crm.lists.listFolders',
    'client.crm.lists.listMemberships',
    'client.crm.lists.moveFolder',
    'client.crm.lists.moveList',
    'client.crm.lists.removeMemberships',
    'client.crm.lists.renameFolder',
    'client.crm.lists.restore',
    'client.crm.lists.scheduleConversion',
    'client.crm.lists.updateListFilters',
    'client.crm.lists.updateListName',
    'client.crm.lists.updateScheduleConversion',
    'client.crm.objectLibrary.enablement.getAll',
    'client.crm.objectLibrary.enablement.getByObjectTypeID',
    'client.crm.objectSchemas.create',
    'client.crm.objectSchemas.createAssociation',
    'client.crm.objectSchemas.delete',
    'client.crm.objectSchemas.deleteAssociation',
    'client.crm.objectSchemas.get',
    'client.crm.objectSchemas.list',
    'client.crm.objectSchemas.update',
    'client.crm.objectSchemas.batch.get',
    'client.crm.objects.calls.create',
    'client.crm.objects.calls.delete',
    'client.crm.objects.calls.get',
    'client.crm.objects.calls.list',
    'client.crm.objects.calls.search',
    'client.crm.objects.calls.update',
    'client.crm.objects.calls.batch.create',
    'client.crm.objects.calls.batch.delete',
    'client.crm.objects.calls.batch.get',
    'client.crm.objects.calls.batch.update',
    'client.crm.objects.calls.batch.upsert',
    'client.crm.objects.carts.create',
    'client.crm.objects.carts.delete',
    'client.crm.objects.carts.get',
    'client.crm.objects.carts.list',
    'client.crm.objects.carts.search',
    'client.crm.objects.carts.update',
    'client.crm.objects.carts.batch.create',
    'client.crm.objects.carts.batch.delete',
    'client.crm.objects.carts.batch.get',
    'client.crm.objects.carts.batch.update',
    'client.crm.objects.carts.batch.upsert',
    'client.crm.objects.commercePayments.create',
    'client.crm.objects.commercePayments.delete',
    'client.crm.objects.commercePayments.get',
    'client.crm.objects.commercePayments.list',
    'client.crm.objects.commercePayments.search',
    'client.crm.objects.commercePayments.update',
    'client.crm.objects.commercePayments.batch.create',
    'client.crm.objects.commercePayments.batch.delete',
    'client.crm.objects.commercePayments.batch.get',
    'client.crm.objects.commercePayments.batch.update',
    'client.crm.objects.commercePayments.batch.upsert',
    'client.crm.objects.communications.create',
    'client.crm.objects.communications.delete',
    'client.crm.objects.communications.get',
    'client.crm.objects.communications.list',
    'client.crm.objects.communications.search',
    'client.crm.objects.communications.update',
    'client.crm.objects.communications.batch.create',
    'client.crm.objects.communications.batch.delete',
    'client.crm.objects.communications.batch.get',
    'client.crm.objects.communications.batch.update',
    'client.crm.objects.communications.batch.upsert',
    'client.crm.objects.companies.create',
    'client.crm.objects.companies.delete',
    'client.crm.objects.companies.get',
    'client.crm.objects.companies.list',
    'client.crm.objects.companies.merge',
    'client.crm.objects.companies.search',
    'client.crm.objects.companies.update',
    'client.crm.objects.companies.batch.create',
    'client.crm.objects.companies.batch.delete',
    'client.crm.objects.companies.batch.get',
    'client.crm.objects.companies.batch.update',
    'client.crm.objects.companies.batch.upsert',
    'client.crm.objects.contacts.create',
    'client.crm.objects.contacts.delete',
    'client.crm.objects.contacts.gdprDelete',
    'client.crm.objects.contacts.get',
    'client.crm.objects.contacts.list',
    'client.crm.objects.contacts.merge',
    'client.crm.objects.contacts.search',
    'client.crm.objects.contacts.update',
    'client.crm.objects.contacts.batch.create',
    'client.crm.objects.contacts.batch.delete',
    'client.crm.objects.contacts.batch.get',
    'client.crm.objects.contacts.batch.update',
    'client.crm.objects.contacts.batch.upsert',
    'client.crm.objects.contracts.create',
    'client.crm.objects.contracts.delete',
    'client.crm.objects.contracts.get',
    'client.crm.objects.contracts.list',
    'client.crm.objects.contracts.search',
    'client.crm.objects.contracts.update',
    'client.crm.objects.contracts.batch.create',
    'client.crm.objects.contracts.batch.delete',
    'client.crm.objects.contracts.batch.get',
    'client.crm.objects.contracts.batch.update',
    'client.crm.objects.contracts.batch.upsert',
    'client.crm.objects.courses.create',
    'client.crm.objects.courses.delete',
    'client.crm.objects.courses.get',
    'client.crm.objects.courses.list',
    'client.crm.objects.courses.search',
    'client.crm.objects.courses.update',
    'client.crm.objects.courses.batch.create',
    'client.crm.objects.courses.batch.delete',
    'client.crm.objects.courses.batch.get',
    'client.crm.objects.courses.batch.update',
    'client.crm.objects.courses.batch.upsert',
    'client.crm.objects.custom.create',
    'client.crm.objects.custom.delete',
    'client.crm.objects.custom.get',
    'client.crm.objects.custom.list',
    'client.crm.objects.custom.merge',
    'client.crm.objects.custom.search',
    'client.crm.objects.custom.update',
    'client.crm.objects.custom.batch.create',
    'client.crm.objects.custom.batch.delete',
    'client.crm.objects.custom.batch.get',
    'client.crm.objects.custom.batch.update',
    'client.crm.objects.custom.batch.upsert',
    'client.crm.objects.deals.create',
    'client.crm.objects.deals.delete',
    'client.crm.objects.deals.get',
    'client.crm.objects.deals.list',
    'client.crm.objects.deals.merge',
    'client.crm.objects.deals.search',
    'client.crm.objects.deals.update',
    'client.crm.objects.deals.batch.create',
    'client.crm.objects.deals.batch.delete',
    'client.crm.objects.deals.batch.get',
    'client.crm.objects.deals.batch.update',
    'client.crm.objects.deals.batch.upsert',
    'client.crm.objects.discounts.create',
    'client.crm.objects.discounts.delete',
    'client.crm.objects.discounts.get',
    'client.crm.objects.discounts.list',
    'client.crm.objects.discounts.search',
    'client.crm.objects.discounts.update',
    'client.crm.objects.discounts.batch.create',
    'client.crm.objects.discounts.batch.delete',
    'client.crm.objects.discounts.batch.get',
    'client.crm.objects.discounts.batch.update',
    'client.crm.objects.discounts.batch.upsert',
    'client.crm.objects.emails.create',
    'client.crm.objects.emails.delete',
    'client.crm.objects.emails.get',
    'client.crm.objects.emails.list',
    'client.crm.objects.emails.search',
    'client.crm.objects.emails.update',
    'client.crm.objects.emails.batch.create',
    'client.crm.objects.emails.batch.delete',
    'client.crm.objects.emails.batch.get',
    'client.crm.objects.emails.batch.update',
    'client.crm.objects.emails.batch.upsert',
    'client.crm.objects.feedbackSubmissions.get',
    'client.crm.objects.feedbackSubmissions.list',
    'client.crm.objects.feedbackSubmissions.search',
    'client.crm.objects.feedbackSubmissions.batch.get',
    'client.crm.objects.fees.create',
    'client.crm.objects.fees.delete',
    'client.crm.objects.fees.get',
    'client.crm.objects.fees.list',
    'client.crm.objects.fees.search',
    'client.crm.objects.fees.update',
    'client.crm.objects.fees.batch.create',
    'client.crm.objects.fees.batch.delete',
    'client.crm.objects.fees.batch.get',
    'client.crm.objects.fees.batch.update',
    'client.crm.objects.fees.batch.upsert',
    'client.crm.objects.genericObjects.create',
    'client.crm.objects.genericObjects.delete',
    'client.crm.objects.genericObjects.get',
    'client.crm.objects.genericObjects.list',
    'client.crm.objects.genericObjects.search',
    'client.crm.objects.genericObjects.update',
    'client.crm.objects.genericObjects.batch.create',
    'client.crm.objects.genericObjects.batch.delete',
    'client.crm.objects.genericObjects.batch.get',
    'client.crm.objects.genericObjects.batch.update',
    'client.crm.objects.genericObjects.batch.upsert',
    'client.crm.objects.goalTargets.create',
    'client.crm.objects.goalTargets.delete',
    'client.crm.objects.goalTargets.get',
    'client.crm.objects.goalTargets.list',
    'client.crm.objects.goalTargets.search',
    'client.crm.objects.goalTargets.update',
    'client.crm.objects.goalTargets.batch.create',
    'client.crm.objects.goalTargets.batch.delete',
    'client.crm.objects.goalTargets.batch.get',
    'client.crm.objects.goalTargets.batch.update',
    'client.crm.objects.goalTargets.batch.upsert',
    'client.crm.objects.invoices.create',
    'client.crm.objects.invoices.delete',
    'client.crm.objects.invoices.get',
    'client.crm.objects.invoices.list',
    'client.crm.objects.invoices.search',
    'client.crm.objects.invoices.update',
    'client.crm.objects.invoices.batch.create',
    'client.crm.objects.invoices.batch.delete',
    'client.crm.objects.invoices.batch.get',
    'client.crm.objects.invoices.batch.update',
    'client.crm.objects.invoices.batch.upsert',
    'client.crm.objects.leads.create',
    'client.crm.objects.leads.delete',
    'client.crm.objects.leads.get',
    'client.crm.objects.leads.list',
    'client.crm.objects.leads.search',
    'client.crm.objects.leads.update',
    'client.crm.objects.leads.batch.create',
    'client.crm.objects.leads.batch.delete',
    'client.crm.objects.leads.batch.get',
    'client.crm.objects.leads.batch.update',
    'client.crm.objects.leads.batch.upsert',
    'client.crm.objects.lineItems.create',
    'client.crm.objects.lineItems.delete',
    'client.crm.objects.lineItems.get',
    'client.crm.objects.lineItems.list',
    'client.crm.objects.lineItems.search',
    'client.crm.objects.lineItems.update',
    'client.crm.objects.lineItems.batch.create',
    'client.crm.objects.lineItems.batch.delete',
    'client.crm.objects.lineItems.batch.get',
    'client.crm.objects.lineItems.batch.update',
    'client.crm.objects.lineItems.batch.upsert',
    'client.crm.objects.listings.create',
    'client.crm.objects.listings.delete',
    'client.crm.objects.listings.get',
    'client.crm.objects.listings.list',
    'client.crm.objects.listings.search',
    'client.crm.objects.listings.update',
    'client.crm.objects.listings.batch.create',
    'client.crm.objects.listings.batch.delete',
    'client.crm.objects.listings.batch.get',
    'client.crm.objects.listings.batch.update',
    'client.crm.objects.listings.batch.upsert',
    'client.crm.objects.meetings.create',
    'client.crm.objects.meetings.delete',
    'client.crm.objects.meetings.get',
    'client.crm.objects.meetings.list',
    'client.crm.objects.meetings.search',
    'client.crm.objects.meetings.update',
    'client.crm.objects.meetings.batch.create',
    'client.crm.objects.meetings.batch.delete',
    'client.crm.objects.meetings.batch.get',
    'client.crm.objects.meetings.batch.update',
    'client.crm.objects.meetings.batch.upsert',
    'client.crm.objects.notes.create',
    'client.crm.objects.notes.delete',
    'client.crm.objects.notes.get',
    'client.crm.objects.notes.list',
    'client.crm.objects.notes.search',
    'client.crm.objects.notes.update',
    'client.crm.objects.notes.batch.create',
    'client.crm.objects.notes.batch.delete',
    'client.crm.objects.notes.batch.get',
    'client.crm.objects.notes.batch.update',
    'client.crm.objects.notes.batch.upsert',
    'client.crm.objects.orders.create',
    'client.crm.objects.orders.delete',
    'client.crm.objects.orders.get',
    'client.crm.objects.orders.list',
    'client.crm.objects.orders.search',
    'client.crm.objects.orders.update',
    'client.crm.objects.orders.batch.create',
    'client.crm.objects.orders.batch.delete',
    'client.crm.objects.orders.batch.get',
    'client.crm.objects.orders.batch.update',
    'client.crm.objects.orders.batch.upsert',
    'client.crm.objects.partnerClients.get',
    'client.crm.objects.partnerClients.list',
    'client.crm.objects.partnerClients.listAssociations',
    'client.crm.objects.partnerClients.search',
    'client.crm.objects.partnerClients.update',
    'client.crm.objects.partnerClients.batch.get',
    'client.crm.objects.partnerClients.batch.update',
    'client.crm.objects.partnerServices.get',
    'client.crm.objects.partnerServices.list',
    'client.crm.objects.partnerServices.search',
    'client.crm.objects.partnerServices.update',
    'client.crm.objects.partnerServices.batch.get',
    'client.crm.objects.partnerServices.batch.update',
    'client.crm.objects.postalMail.create',
    'client.crm.objects.postalMail.delete',
    'client.crm.objects.postalMail.get',
    'client.crm.objects.postalMail.list',
    'client.crm.objects.postalMail.search',
    'client.crm.objects.postalMail.update',
    'client.crm.objects.postalMail.batch.create',
    'client.crm.objects.postalMail.batch.delete',
    'client.crm.objects.postalMail.batch.get',
    'client.crm.objects.postalMail.batch.update',
    'client.crm.objects.postalMail.batch.upsert',
    'client.crm.objects.products.create',
    'client.crm.objects.products.delete',
    'client.crm.objects.products.get',
    'client.crm.objects.products.list',
    'client.crm.objects.products.search',
    'client.crm.objects.products.update',
    'client.crm.objects.products.batch.create',
    'client.crm.objects.products.batch.delete',
    'client.crm.objects.products.batch.get',
    'client.crm.objects.products.batch.update',
    'client.crm.objects.products.batch.upsert',
    'client.crm.objects.projects.create',
    'client.crm.objects.projects.delete',
    'client.crm.objects.projects.get',
    'client.crm.objects.projects.list',
    'client.crm.objects.projects.merge',
    'client.crm.objects.projects.search',
    'client.crm.objects.projects.update',
    'client.crm.objects.projects.batch.create',
    'client.crm.objects.projects.batch.delete',
    'client.crm.objects.projects.batch.get',
    'client.crm.objects.projects.batch.update',
    'client.crm.objects.projects.batch.upsert',
    'client.crm.objects.quotes.create',
    'client.crm.objects.quotes.delete',
    'client.crm.objects.quotes.get',
    'client.crm.objects.quotes.list',
    'client.crm.objects.quotes.search',
    'client.crm.objects.quotes.update',
    'client.crm.objects.quotes.batch.create',
    'client.crm.objects.quotes.batch.delete',
    'client.crm.objects.quotes.batch.get',
    'client.crm.objects.quotes.batch.update',
    'client.crm.objects.quotes.batch.upsert',
    'client.crm.objects.services.create',
    'client.crm.objects.services.delete',
    'client.crm.objects.services.get',
    'client.crm.objects.services.list',
    'client.crm.objects.services.search',
    'client.crm.objects.services.update',
    'client.crm.objects.services.batch.create',
    'client.crm.objects.services.batch.delete',
    'client.crm.objects.services.batch.get',
    'client.crm.objects.services.batch.update',
    'client.crm.objects.services.batch.upsert',
    'client.crm.objects.subscriptions.create',
    'client.crm.objects.subscriptions.delete',
    'client.crm.objects.subscriptions.get',
    'client.crm.objects.subscriptions.list',
    'client.crm.objects.subscriptions.search',
    'client.crm.objects.subscriptions.update',
    'client.crm.objects.subscriptions.batch.create',
    'client.crm.objects.subscriptions.batch.delete',
    'client.crm.objects.subscriptions.batch.get',
    'client.crm.objects.subscriptions.batch.update',
    'client.crm.objects.subscriptions.batch.upsert',
    'client.crm.objects.tasks.create',
    'client.crm.objects.tasks.delete',
    'client.crm.objects.tasks.get',
    'client.crm.objects.tasks.list',
    'client.crm.objects.tasks.search',
    'client.crm.objects.tasks.update',
    'client.crm.objects.tasks.batch.create',
    'client.crm.objects.tasks.batch.delete',
    'client.crm.objects.tasks.batch.get',
    'client.crm.objects.tasks.batch.update',
    'client.crm.objects.tasks.batch.upsert',
    'client.crm.objects.taxes.create',
    'client.crm.objects.taxes.delete',
    'client.crm.objects.taxes.get',
    'client.crm.objects.taxes.list',
    'client.crm.objects.taxes.search',
    'client.crm.objects.taxes.update',
    'client.crm.objects.taxes.batch.create',
    'client.crm.objects.taxes.batch.delete',
    'client.crm.objects.taxes.batch.get',
    'client.crm.objects.taxes.batch.update',
    'client.crm.objects.taxes.batch.upsert',
    'client.crm.objects.tickets.create',
    'client.crm.objects.tickets.delete',
    'client.crm.objects.tickets.get',
    'client.crm.objects.tickets.list',
    'client.crm.objects.tickets.merge',
    'client.crm.objects.tickets.search',
    'client.crm.objects.tickets.update',
    'client.crm.objects.tickets.batch.create',
    'client.crm.objects.tickets.batch.delete',
    'client.crm.objects.tickets.batch.get',
    'client.crm.objects.tickets.batch.update',
    'client.crm.objects.tickets.batch.upsert',
    'client.crm.objects.users.create',
    'client.crm.objects.users.delete',
    'client.crm.objects.users.get',
    'client.crm.objects.users.list',
    'client.crm.objects.users.search',
    'client.crm.objects.users.update',
    'client.crm.objects.users.batch.create',
    'client.crm.objects.users.batch.delete',
    'client.crm.objects.users.batch.get',
    'client.crm.objects.users.batch.update',
    'client.crm.objects.users.batch.upsert',
    'client.crm.owners.get',
    'client.crm.owners.list',
    'client.crm.pipelines.create',
    'client.crm.pipelines.createStage',
    'client.crm.pipelines.delete',
    'client.crm.pipelines.deleteStage',
    'client.crm.pipelines.get',
    'client.crm.pipelines.getStage',
    'client.crm.pipelines.list',
    'client.crm.pipelines.listAudit',
    'client.crm.pipelines.listStageAudit',
    'client.crm.pipelines.listStages',
    'client.crm.pipelines.update',
    'client.crm.pipelines.updateAllProperties',
    'client.crm.pipelines.updateStage',
    'client.crm.pipelines.updateStageAllProperties',
    'client.crm.properties.create',
    'client.crm.properties.delete',
    'client.crm.properties.get',
    'client.crm.properties.list',
    'client.crm.properties.update',
    'client.crm.properties.batch.create',
    'client.crm.properties.batch.delete',
    'client.crm.properties.batch.get',
    'client.crm.properties.groups.create',
    'client.crm.properties.groups.delete',
    'client.crm.properties.groups.get',
    'client.crm.properties.groups.list',
    'client.crm.properties.groups.update',
    'client.crm.propertiesValidations.getByObjectTypeID',
    'client.crm.propertiesValidations.getByObjectTypeIDAndPropertyName',
    'client.crm.propertiesValidations.getByObjectTypeIDPropertyNameAndRuleType',
    'client.crm.propertiesValidations.updateByObjectTypeIDPropertyNameAndRuleType',
    'client.crm.timeline.createEvent',
    'client.crm.timeline.createProjectType',
    'client.crm.timeline.batch.create',
    'client.events.definitions.create',
    'client.events.definitions.createProperty',
    'client.events.definitions.delete',
    'client.events.definitions.deleteProperty',
    'client.events.definitions.get',
    'client.events.definitions.list',
    'client.events.definitions.sendBatch',
    'client.events.definitions.update',
    'client.events.definitions.updateProperty',
    'client.events.occurrences.list',
    'client.events.occurrences.listEventTypes',
    'client.events.send.batchSend',
    'client.events.send.send',
    'client.files.fileAssets.create',
    'client.files.fileAssets.delete',
    'client.files.fileAssets.gdprDelete',
    'client.files.fileAssets.get',
    'client.files.fileAssets.getImportTaskStatus',
    'client.files.fileAssets.getSignedURL',
    'client.files.fileAssets.importFromURLAsync',
    'client.files.fileAssets.replace',
    'client.files.fileAssets.search',
    'client.files.fileAssets.update',
    'client.files.fileAssets.upload',
    'client.files.folders.deleteByID',
    'client.files.folders.deleteByPath',
    'client.files.folders.getByID',
    'client.files.folders.getByPath',
    'client.files.folders.getUpdateAsyncStatus',
    'client.files.folders.search',
    'client.files.folders.updateAsyncByID',
    'client.files.folders.updateByID',
    'client.marketing.campaigns.create',
    'client.marketing.campaigns.delete',
    'client.marketing.campaigns.get',
    'client.marketing.campaigns.list',
    'client.marketing.campaigns.update',
    'client.marketing.campaigns.assets.delete',
    'client.marketing.campaigns.assets.list',
    'client.marketing.campaigns.assets.update',
    'client.marketing.campaigns.batch.create',
    'client.marketing.campaigns.batch.delete',
    'client.marketing.campaigns.batch.get',
    'client.marketing.campaigns.batch.update',
    'client.marketing.campaigns.budget.create',
    'client.marketing.campaigns.budget.delete',
    'client.marketing.campaigns.budget.get',
    'client.marketing.campaigns.budget.getTotals',
    'client.marketing.campaigns.budget.update',
    'client.marketing.campaigns.metrics.getAttributionMetrics',
    'client.marketing.campaigns.metrics.getRevenueAttribution',
    'client.marketing.campaigns.metrics.listContactIDsByType',
    'client.marketing.campaigns.spend.create',
    'client.marketing.campaigns.spend.delete',
    'client.marketing.campaigns.spend.get',
    'client.marketing.campaigns.spend.update',
    'client.marketing.emails.clone',
    'client.marketing.emails.create',
    'client.marketing.emails.createAbTestVariation',
    'client.marketing.emails.delete',
    'client.marketing.emails.get',
    'client.marketing.emails.getAbTestVariation',
    'client.marketing.emails.getDraft',
    'client.marketing.emails.getHistogram',
    'client.marketing.emails.getRevision',
    'client.marketing.emails.list',
    'client.marketing.emails.listRevisions',
    'client.marketing.emails.publish',
    'client.marketing.emails.resetDraft',
    'client.marketing.emails.restoreRevision',
    'client.marketing.emails.restoreRevisionToDraft',
    'client.marketing.emails.unpublish',
    'client.marketing.emails.update',
    'client.marketing.emails.updateDraft',
    'client.marketing.marketingEvents.create',
    'client.marketing.marketingEvents.delete',
    'client.marketing.marketingEvents.deleteBatch',
    'client.marketing.marketingEvents.deleteBatchByExternalEventID',
    'client.marketing.marketingEvents.deleteByExternalEventID',
    'client.marketing.marketingEvents.get',
    'client.marketing.marketingEvents.getByExternalEventID',
    'client.marketing.marketingEvents.list',
    'client.marketing.marketingEvents.searchByExternalEventID',
    'client.marketing.marketingEvents.searchIdentifiersByExternalEventID',
    'client.marketing.marketingEvents.update',
    'client.marketing.marketingEvents.updateBatch',
    'client.marketing.marketingEvents.updateByExternalEventID',
    'client.marketing.marketingEvents.upsertBatch',
    'client.marketing.marketingEvents.upsertByExternalEventID',
    'client.marketing.marketingEvents.attendance.createByEventIDAndContactID',
    'client.marketing.marketingEvents.attendance.createByEventIDAndEmail',
    'client.marketing.marketingEvents.attendance.createByExternalEventIDAndContactID',
    'client.marketing.marketingEvents.attendance.createByExternalEventIDAndEmail',
    'client.marketing.marketingEvents.events.cancelByExternalEventID',
    'client.marketing.marketingEvents.events.completeByExternalEventID',
    'client.marketing.marketingEvents.listAssociations.associate',
    'client.marketing.marketingEvents.listAssociations.associateByExternalAccount',
    'client.marketing.marketingEvents.listAssociations.delete',
    'client.marketing.marketingEvents.listAssociations.deleteByExternalAccount',
    'client.marketing.marketingEvents.listAssociations.list',
    'client.marketing.marketingEvents.listAssociations.listByExternalAccount',
    'client.marketing.marketingEvents.participations.getByExternalAccountAndEventID',
    'client.marketing.marketingEvents.participations.getByID',
    'client.marketing.marketingEvents.participations.listBreakdownByContact',
    'client.marketing.marketingEvents.participations.listBreakdownByExternalAccountAndEventID',
    'client.marketing.marketingEvents.participations.listBreakdownByID',
    'client.marketing.marketingEvents.settings.createOrUpdate',
    'client.marketing.marketingEvents.settings.get',
    'client.marketing.marketingEvents.subscriberState.recordByEmail',
    'client.marketing.marketingEvents.subscriberState.recordByID',
    'client.marketing.singleSend.create',
    'client.marketing.transactional.singleEmail.send',
    'client.marketing.transactional.smtpTokens.create',
    'client.marketing.transactional.smtpTokens.delete',
    'client.marketing.transactional.smtpTokens.get',
    'client.marketing.transactional.smtpTokens.list',
    'client.marketing.transactional.smtpTokens.resetPassword',
    'client.meta.origins.ipRanges.list',
    'client.meta.origins.ipRanges.listSimple',
    'client.scheduler.meetings.advanced.book',
    'client.scheduler.meetings.advanced.create',
    'client.scheduler.meetings.basic.getAvailabilityBySlug',
    'client.scheduler.meetings.basic.getBookingInfoBySlug',
    'client.scheduler.meetings.basic.list',
    'client.settings.currencies.getCompanyCurrency',
    'client.settings.currencies.listCodes',
    'client.settings.currencies.updateCompanyCurrency',
    'client.settings.currencies.centralFxRates.createCurrency',
    'client.settings.currencies.centralFxRates.getInformation',
    'client.settings.currencies.centralFxRates.getUnsupportedCurrencies',
    'client.settings.currencies.exchangeRates.createExchangeRate',
    'client.settings.currencies.exchangeRates.getExchangeRateByID',
    'client.settings.currencies.exchangeRates.listCurrentExchangeRates',
    'client.settings.currencies.exchangeRates.listExchangeRates',
    'client.settings.currencies.exchangeRates.updateExchangeRate',
    'client.settings.currencies.exchangeRates.updateVisibility',
    'client.settings.currencies.exchangeRates.batch.create',
    'client.settings.currencies.exchangeRates.batch.get',
    'client.settings.currencies.exchangeRates.batch.update',
    'client.settings.taxRates.get',
    'client.settings.taxRates.list',
    'client.settings.users.create',
    'client.settings.users.delete',
    'client.settings.users.get',
    'client.settings.users.list',
    'client.settings.users.listRoles',
    'client.settings.users.listTeams',
    'client.settings.users.update',
    'client.webhooks.createBatchEventSubscriptions',
    'client.webhooks.createCrmSnapshots',
    'client.webhooks.createEventSubscription',
    'client.webhooks.createJournalSubscription',
    'client.webhooks.createSubscriptionFilter',
    'client.webhooks.deleteEventSubscription',
    'client.webhooks.deleteJournalSubscription',
    'client.webhooks.deleteJournalSubscriptionForPortal',
    'client.webhooks.deleteSettings',
    'client.webhooks.deleteSubscriptionFilter',
    'client.webhooks.getEarliestJournalBatch',
    'client.webhooks.getEarliestJournalEntry',
    'client.webhooks.getEarliestLocalJournalBatch',
    'client.webhooks.getEarliestLocalJournalEntry',
    'client.webhooks.getEventSubscription',
    'client.webhooks.getJournalBatchByRequest',
    'client.webhooks.getJournalBatchFromOffset',
    'client.webhooks.getJournalStatus',
    'client.webhooks.getJournalSubscription',
    'client.webhooks.getLatestJournalBatch',
    'client.webhooks.getLatestJournalEntry',
    'client.webhooks.getLatestLocalJournalBatch',
    'client.webhooks.getLatestLocalJournalEntry',
    'client.webhooks.getLocalJournalBatchByRequest',
    'client.webhooks.getLocalJournalBatchFromOffset',
    'client.webhooks.getLocalJournalStatus',
    'client.webhooks.getNextJournalEntries',
    'client.webhooks.getNextLocalJournalEntries',
    'client.webhooks.getSettings',
    'client.webhooks.getSubscriptionFilter',
    'client.webhooks.listEventSubscriptions',
    'client.webhooks.listJournalSubscriptions',
    'client.webhooks.listSubscriptionFilters',
    'client.webhooks.updateEventSubscription',
    'client.webhooks.updateSettings',
  ],
  { threshold: 1, shouldSort: true },
);

function getMethodSuggestions(fullyQualifiedMethodName: string): string[] {
  return fuse
    .search(fullyQualifiedMethodName)
    .map(({ item }) => item)
    .slice(0, 5);
}

const proxyToObj = new WeakMap<any, any>();
const objToProxy = new WeakMap<any, any>();

type ClientProxyConfig = {
  path: string[];
  isBelievedBad?: boolean;
};

function makeSdkProxy<T extends object>(obj: T, { path, isBelievedBad = false }: ClientProxyConfig): T {
  let proxy: T = objToProxy.get(obj);

  if (!proxy) {
    proxy = new Proxy(obj, {
      get(target, prop, receiver) {
        const propPath = [...path, String(prop)];
        const value = Reflect.get(target, prop, receiver);

        if (isBelievedBad || (!(prop in target) && value === undefined)) {
          // If we're accessing a path that doesn't exist, it will probably eventually error.
          // Let's proxy it and mark it bad so that we can control the error message.
          // We proxy an empty class so that an invocation or construction attempt is possible.
          return makeSdkProxy(class {}, { path: propPath, isBelievedBad: true });
        }

        if (value !== null && (typeof value === 'object' || typeof value === 'function')) {
          return makeSdkProxy(value, { path: propPath, isBelievedBad });
        }

        return value;
      },

      apply(target, thisArg, args) {
        if (isBelievedBad || typeof target !== 'function') {
          const fullyQualifiedMethodName = path.join('.');
          const suggestions = getMethodSuggestions(fullyQualifiedMethodName);
          throw new Error(
            `${fullyQualifiedMethodName} is not a function. Did you mean: ${suggestions.join(', ')}`,
          );
        }

        return Reflect.apply(target, proxyToObj.get(thisArg) ?? thisArg, args);
      },

      construct(target, args, newTarget) {
        if (isBelievedBad || typeof target !== 'function') {
          const fullyQualifiedMethodName = path.join('.');
          const suggestions = getMethodSuggestions(fullyQualifiedMethodName);
          throw new Error(
            `${fullyQualifiedMethodName} is not a constructor. Did you mean: ${suggestions.join(', ')}`,
          );
        }

        return Reflect.construct(target, args, newTarget);
      },
    });

    objToProxy.set(obj, proxy);
    proxyToObj.set(proxy, obj);
  }

  return proxy;
}

function parseError(code: string, error: unknown): string | undefined {
  if (!(error instanceof Error)) return;
  const cause = error.cause instanceof Error ? `: ${error.cause.message}` : '';
  const message = error.name ? `${error.name}: ${error.message}${cause}` : `${error.message}${cause}`;
  try {
    // Deno uses V8; the first "<anonymous>:LINE:COLUMN" is the top of stack.
    const lineNumber = error.stack?.match(/<anonymous>:([0-9]+):[0-9]+/)?.[1];
    // -1 for the zero-based indexing
    const line =
      lineNumber &&
      code
        .split('\n')
        .at(parseInt(lineNumber, 10) - 1)
        ?.trim();
    return line ? `${message}\n  at line ${lineNumber}\n    ${line}` : message;
  } catch {
    return message;
  }
}

const fetch = async (req: Request): Promise<Response> => {
  const { opts, code } = (await req.json()) as { opts: ClientOptions; code: string };

  const runFunctionSource = code ? getRunFunctionSource(code) : null;
  if (!runFunctionSource) {
    const message =
      code ?
        'The code is missing a top-level `run` function.'
      : 'The code argument is missing. Provide one containing a top-level `run` function.';
    return Response.json(
      {
        is_error: true,
        result: `${message} Write code within this template:\n\n\`\`\`\nasync function run(client) {\n  // Fill this out\n}\n\`\`\``,
        log_lines: [],
        err_lines: [],
      } satisfies WorkerOutput,
      { status: 400, statusText: 'Code execution error' },
    );
  }

  const diagnostics = getTSDiagnostics(code);
  if (diagnostics.length > 0) {
    return Response.json(
      {
        is_error: true,
        result: `The code contains TypeScript diagnostics:\n${diagnostics.join('\n')}`,
        log_lines: [],
        err_lines: [],
      } satisfies WorkerOutput,
      { status: 400, statusText: 'Code execution error' },
    );
  }

  const client = new HubSpot({
    ...opts,
  });

  const log_lines: string[] = [];
  const err_lines: string[] = [];
  const originalConsole = globalThis.console;
  globalThis.console = {
    ...originalConsole,
    log: (...args: unknown[]) => {
      log_lines.push(util.format(...args));
    },
    error: (...args: unknown[]) => {
      err_lines.push(util.format(...args));
    },
  };
  try {
    let run_ = async (client: any) => {};
    run_ = (await tseval(`${code}\nexport default run;`)).default;
    const result = await run_(makeSdkProxy(client, { path: ['client'] }));
    return Response.json({
      is_error: false,
      result,
      log_lines,
      err_lines,
    } satisfies WorkerOutput);
  } catch (e) {
    return Response.json(
      {
        is_error: true,
        result: parseError(code, e),
        log_lines,
        err_lines,
      } satisfies WorkerOutput,
      { status: 400, statusText: 'Code execution error' },
    );
  } finally {
    globalThis.console = originalConsole;
  }
};

export default { fetch };
