// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as WebhooksAPI from './webhooks_/webhooks_';
import {
  AppLifecycleEventSubscriptionUpsertRequest,
  AssociationSubscriptionUpsertRequest,
  BatchInputSubscriptionBatchUpdateRequest,
  BatchResponseJournalFetchResponse,
  BatchResponseSubscriptionResponse,
  CollectionResponseSubscriptionResponseNoPaging,
  Condition,
  CrmObjectSnapshotBatchRequest,
  CrmObjectSnapshotBatchResponse,
  CrmObjectSnapshotRequest,
  CrmObjectSnapshotResponse,
  Filter,
  FilterCreateRequest,
  FilterCreateResponse,
  FilterResponse,
  JournalFetchResponse,
  ListMembershipSubscriptionUpsertRequest,
  ObjectSubscriptionUpsertRequest,
  SettingsChangeRequest,
  SettingsResponse,
  SnapshotStatusResponse,
  SubscriptionBatchUpdateRequest,
  SubscriptionCreateRequest,
  SubscriptionListResponse,
  SubscriptionPatchRequest,
  SubscriptionResponse,
  SubscriptionResponse1,
  SubscriptionUpsertRequest,
  ThrottlingSettings,
  WebhookCreateCrmSnapshotParams,
  WebhookCreateFilterParams,
  WebhookCreateSubscriptionParams,
  WebhookDeleteSubscriptionParams,
  WebhookGetEarliestJournalLocalParams,
  WebhookGetEarliestJournalParams,
  WebhookGetFilterBySubscriptionResponse,
  WebhookGetLatestJournalLocalParams,
  WebhookGetLatestJournalParams,
  WebhookGetNextJournalByOffsetParams,
  WebhookGetNextJournalLocalByOffsetParams,
  WebhookGetSubscriptionParams,
  WebhookUpdateSettingsParams,
  WebhookUpdateSubscriptionParams,
  Webhooks as WebhooksAPIWebhooks,
} from './webhooks_/webhooks_';

export class Webhooks extends APIResource {
  webhooks: WebhooksAPI.Webhooks = new WebhooksAPI.Webhooks(this._client);
}

Webhooks.Webhooks = WebhooksAPIWebhooks;

export declare namespace Webhooks {
  export {
    WebhooksAPIWebhooks as Webhooks,
    type AppLifecycleEventSubscriptionUpsertRequest as AppLifecycleEventSubscriptionUpsertRequest,
    type AssociationSubscriptionUpsertRequest as AssociationSubscriptionUpsertRequest,
    type BatchInputSubscriptionBatchUpdateRequest as BatchInputSubscriptionBatchUpdateRequest,
    type BatchResponseJournalFetchResponse as BatchResponseJournalFetchResponse,
    type BatchResponseSubscriptionResponse as BatchResponseSubscriptionResponse,
    type CollectionResponseSubscriptionResponseNoPaging as CollectionResponseSubscriptionResponseNoPaging,
    type Condition as Condition,
    type CrmObjectSnapshotBatchRequest as CrmObjectSnapshotBatchRequest,
    type CrmObjectSnapshotBatchResponse as CrmObjectSnapshotBatchResponse,
    type CrmObjectSnapshotRequest as CrmObjectSnapshotRequest,
    type CrmObjectSnapshotResponse as CrmObjectSnapshotResponse,
    type Filter as Filter,
    type FilterCreateRequest as FilterCreateRequest,
    type FilterCreateResponse as FilterCreateResponse,
    type FilterResponse as FilterResponse,
    type JournalFetchResponse as JournalFetchResponse,
    type ListMembershipSubscriptionUpsertRequest as ListMembershipSubscriptionUpsertRequest,
    type ObjectSubscriptionUpsertRequest as ObjectSubscriptionUpsertRequest,
    type SettingsChangeRequest as SettingsChangeRequest,
    type SettingsResponse as SettingsResponse,
    type SnapshotStatusResponse as SnapshotStatusResponse,
    type SubscriptionBatchUpdateRequest as SubscriptionBatchUpdateRequest,
    type SubscriptionCreateRequest as SubscriptionCreateRequest,
    type SubscriptionListResponse as SubscriptionListResponse,
    type SubscriptionPatchRequest as SubscriptionPatchRequest,
    type SubscriptionResponse as SubscriptionResponse,
    type SubscriptionResponse1 as SubscriptionResponse1,
    type SubscriptionUpsertRequest as SubscriptionUpsertRequest,
    type ThrottlingSettings as ThrottlingSettings,
    type WebhookGetFilterBySubscriptionResponse as WebhookGetFilterBySubscriptionResponse,
    type WebhookCreateCrmSnapshotParams as WebhookCreateCrmSnapshotParams,
    type WebhookCreateFilterParams as WebhookCreateFilterParams,
    type WebhookCreateSubscriptionParams as WebhookCreateSubscriptionParams,
    type WebhookDeleteSubscriptionParams as WebhookDeleteSubscriptionParams,
    type WebhookGetEarliestJournalParams as WebhookGetEarliestJournalParams,
    type WebhookGetEarliestJournalLocalParams as WebhookGetEarliestJournalLocalParams,
    type WebhookGetLatestJournalParams as WebhookGetLatestJournalParams,
    type WebhookGetLatestJournalLocalParams as WebhookGetLatestJournalLocalParams,
    type WebhookGetNextJournalByOffsetParams as WebhookGetNextJournalByOffsetParams,
    type WebhookGetNextJournalLocalByOffsetParams as WebhookGetNextJournalLocalByOffsetParams,
    type WebhookGetSubscriptionParams as WebhookGetSubscriptionParams,
    type WebhookUpdateSettingsParams as WebhookUpdateSettingsParams,
    type WebhookUpdateSubscriptionParams as WebhookUpdateSubscriptionParams,
  };
}
