// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as WebhookSubscriptionsAPI from './webhook-subscriptions/webhook-subscriptions';
import {
  ActionOverrideRequest,
  AppLifecycleEventSubscriptionUpsertRequest,
  AssociationSubscriptionUpsertRequest,
  BatchInputSubscriptionBatchUpdateRequest,
  BatchResponseJournalFetchResponse,
  BatchResponseJournalFetchResponseWithErrors,
  BatchResponseSubscriptionResponse,
  BatchResponseSubscriptionResponseWithErrors,
  CollectionResponseSubscriptionResponseNoPaging,
  Condition,
  CrmObjectSnapshotBatchRequest,
  CrmObjectSnapshotBatchResponse,
  CrmObjectSnapshotRequest,
  CrmObjectSnapshotResponse,
  Filter,
  FilterCreateRequest,
  FilterCreateResponse,
  FilterResponse,
  JournalFetchResponse,
  ListMembershipSubscriptionUpsertRequest,
  ObjectSubscriptionUpsertRequest,
  SettingsChangeRequest,
  SettingsResponse,
  SnapshotStatusResponse,
  SubscriptionBatchUpdateRequest,
  SubscriptionCreateRequest,
  SubscriptionListResponse,
  SubscriptionPatchRequest,
  SubscriptionResponse,
  SubscriptionResponse1,
  SubscriptionUpsertRequest,
  ThrottlingSettings,
  WebhookSubscriptionCreateCrmSnapshotParams,
  WebhookSubscriptionCreateJournalSubscriptionParams,
  WebhookSubscriptionCreateSubscriptionFilterParams,
  WebhookSubscriptionCreateSubscriptionParams,
  WebhookSubscriptionDeleteSubscriptionParams,
  WebhookSubscriptionGetJournalEarliestParams,
  WebhookSubscriptionGetJournalLatestParams,
  WebhookSubscriptionGetJournalNextByOffsetParams,
  WebhookSubscriptionGetLocalJournalEarliestParams,
  WebhookSubscriptionGetLocalJournalLatestParams,
  WebhookSubscriptionGetLocalJournalNextByOffsetParams,
  WebhookSubscriptionGetSubscriptionFilterForSubscriptionResponse,
  WebhookSubscriptionGetSubscriptionParams,
  WebhookSubscriptionUpdateSettingsParams,
  WebhookSubscriptionUpdateSubscriptionParams,
  WebhookSubscriptions,
} from './webhook-subscriptions/webhook-subscriptions';

export class Webhooks extends APIResource {
  webhookSubscriptions: WebhookSubscriptionsAPI.WebhookSubscriptions =
    new WebhookSubscriptionsAPI.WebhookSubscriptions(this._client);
}

Webhooks.WebhookSubscriptions = WebhookSubscriptions;

export declare namespace Webhooks {
  export {
    WebhookSubscriptions as WebhookSubscriptions,
    type ActionOverrideRequest as ActionOverrideRequest,
    type AppLifecycleEventSubscriptionUpsertRequest as AppLifecycleEventSubscriptionUpsertRequest,
    type AssociationSubscriptionUpsertRequest as AssociationSubscriptionUpsertRequest,
    type BatchInputSubscriptionBatchUpdateRequest as BatchInputSubscriptionBatchUpdateRequest,
    type BatchResponseJournalFetchResponse as BatchResponseJournalFetchResponse,
    type BatchResponseJournalFetchResponseWithErrors as BatchResponseJournalFetchResponseWithErrors,
    type BatchResponseSubscriptionResponse as BatchResponseSubscriptionResponse,
    type BatchResponseSubscriptionResponseWithErrors as BatchResponseSubscriptionResponseWithErrors,
    type CollectionResponseSubscriptionResponseNoPaging as CollectionResponseSubscriptionResponseNoPaging,
    type Condition as Condition,
    type CrmObjectSnapshotBatchRequest as CrmObjectSnapshotBatchRequest,
    type CrmObjectSnapshotBatchResponse as CrmObjectSnapshotBatchResponse,
    type CrmObjectSnapshotRequest as CrmObjectSnapshotRequest,
    type CrmObjectSnapshotResponse as CrmObjectSnapshotResponse,
    type Filter as Filter,
    type FilterCreateRequest as FilterCreateRequest,
    type FilterCreateResponse as FilterCreateResponse,
    type FilterResponse as FilterResponse,
    type JournalFetchResponse as JournalFetchResponse,
    type ListMembershipSubscriptionUpsertRequest as ListMembershipSubscriptionUpsertRequest,
    type ObjectSubscriptionUpsertRequest as ObjectSubscriptionUpsertRequest,
    type SettingsChangeRequest as SettingsChangeRequest,
    type SettingsResponse as SettingsResponse,
    type SnapshotStatusResponse as SnapshotStatusResponse,
    type SubscriptionBatchUpdateRequest as SubscriptionBatchUpdateRequest,
    type SubscriptionCreateRequest as SubscriptionCreateRequest,
    type SubscriptionListResponse as SubscriptionListResponse,
    type SubscriptionPatchRequest as SubscriptionPatchRequest,
    type SubscriptionResponse as SubscriptionResponse,
    type SubscriptionResponse1 as SubscriptionResponse1,
    type SubscriptionUpsertRequest as SubscriptionUpsertRequest,
    type ThrottlingSettings as ThrottlingSettings,
    type WebhookSubscriptionGetSubscriptionFilterForSubscriptionResponse as WebhookSubscriptionGetSubscriptionFilterForSubscriptionResponse,
    type WebhookSubscriptionCreateCrmSnapshotParams as WebhookSubscriptionCreateCrmSnapshotParams,
    type WebhookSubscriptionCreateJournalSubscriptionParams as WebhookSubscriptionCreateJournalSubscriptionParams,
    type WebhookSubscriptionCreateSubscriptionParams as WebhookSubscriptionCreateSubscriptionParams,
    type WebhookSubscriptionCreateSubscriptionFilterParams as WebhookSubscriptionCreateSubscriptionFilterParams,
    type WebhookSubscriptionDeleteSubscriptionParams as WebhookSubscriptionDeleteSubscriptionParams,
    type WebhookSubscriptionGetJournalEarliestParams as WebhookSubscriptionGetJournalEarliestParams,
    type WebhookSubscriptionGetJournalLatestParams as WebhookSubscriptionGetJournalLatestParams,
    type WebhookSubscriptionGetJournalNextByOffsetParams as WebhookSubscriptionGetJournalNextByOffsetParams,
    type WebhookSubscriptionGetLocalJournalEarliestParams as WebhookSubscriptionGetLocalJournalEarliestParams,
    type WebhookSubscriptionGetLocalJournalLatestParams as WebhookSubscriptionGetLocalJournalLatestParams,
    type WebhookSubscriptionGetLocalJournalNextByOffsetParams as WebhookSubscriptionGetLocalJournalNextByOffsetParams,
    type WebhookSubscriptionGetSubscriptionParams as WebhookSubscriptionGetSubscriptionParams,
    type WebhookSubscriptionUpdateSettingsParams as WebhookSubscriptionUpdateSettingsParams,
    type WebhookSubscriptionUpdateSubscriptionParams as WebhookSubscriptionUpdateSubscriptionParams,
  };
}
