// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

export {
  Campaigns,
  type BatchInputPublicCampaignBatchUpdateItem,
  type BatchInputPublicCampaignDeleteInput,
  type BatchInputPublicCampaignInput,
  type BatchInputPublicCampaignReadInput,
  type BatchResponsePublicCampaign,
  type BatchResponsePublicCampaignWithAssets,
  type CollectionResponseContactReferenceForwardPaging,
  type CollectionResponsePublicCampaignAsset,
  type CollectionResponsePublicCampaignAssetForwardPaging,
  type CollectionResponseWithTotalPublicCampaign,
  type ContactReference,
  type MetricsCounters,
  type PublicBudgetItem,
  type PublicBudgetItemInput,
  type PublicBudgetTotals,
  type PublicBusinessUnit,
  type PublicCampaign,
  type PublicCampaignAsset,
  type PublicCampaignBatchUpdateItem,
  type PublicCampaignDeleteInput,
  type PublicCampaignInput,
  type PublicCampaignReadInput,
  type PublicCampaignWithAssets,
  type PublicSpendItem,
  type PublicSpendItemInput,
  type RevenueAttributionAggregate,
  type CampaignUpdateParams,
  type CampaignGetParams,
  type ContactReferencesPage,
} from './campaigns/index';
export { Marketing } from './marketing';
