// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

export {
  Campaigns,
  type BatchInputPublicCampaignBatchUpdateItem,
  type BatchInputPublicCampaignDeleteInput,
  type BatchInputPublicCampaignInput,
  type BatchInputPublicCampaignReadInput,
  type BatchResponsePublicCampaign,
  type BatchResponsePublicCampaignWithAssets,
  type BatchResponsePublicCampaignWithAssetsWithErrors,
  type BatchResponsePublicCampaignWithErrors,
  type CollectionResponseContactReferenceForwardPaging,
  type CollectionResponsePublicCampaignAsset,
  type CollectionResponsePublicCampaignAssetForwardPaging,
  type CollectionResponseWithTotalPublicCampaignForwardPaging,
  type ContactReference,
  type MetricsCounters,
  type PublicBudgetItem,
  type PublicBudgetItemInput,
  type PublicBudgetTotals,
  type PublicBusinessUnit,
  type PublicCampaign,
  type PublicCampaignAsset,
  type PublicCampaignBatchUpdateItem,
  type PublicCampaignDeleteInput,
  type PublicCampaignInput,
  type PublicCampaignReadInput,
  type PublicCampaignWithAssets,
  type PublicSpendItem,
  type PublicSpendItemInput,
  type RevenueAttributionAggregate,
  type CampaignCreateParams,
  type CampaignUpdateParams,
  type CampaignListParams,
  type CampaignGetParams,
  type PublicCampaignsPage,
} from './campaigns/index';
export { Emails } from './emails/index';
export {
  Events,
  type EventCreateParams,
  type EventUpdateParams,
  type EventListParams,
  type EventCancelByExternalEventIDParams,
  type EventCompleteByExternalEventIDParams,
  type EventDeleteBatchParams,
  type EventDeleteBatchByExternalEventIDParams,
  type EventDeleteByExternalEventIDParams,
  type EventGetByExternalEventIDParams,
  type EventSearchByExternalEventIDParams,
  type EventUpdateBatchParams,
  type EventUpdateByExternalEventIDParams,
  type EventUpsertBatchParams,
  type EventUpsertByExternalEventIDParams,
  type EventUpsertSubscriberStateByEmailParams,
  type EventUpsertSubscriberStateByIDParams,
} from './events/index';
export {
  Forms,
  type CollectionResponseFormDefinitionBaseForwardPaging,
  type DatepickerField,
  type DependentField,
  type DependentFieldFilter,
  type DropdownField,
  type EmailField,
  type EmailFieldValidation,
  type EnumeratedFieldOption,
  type FieldGroup,
  type FileField,
  type FormDefinitionBase,
  type FormDefinitionCreateRequestBase,
  type FormDisplayOptions,
  type FormPostSubmitAction,
  type FormStyle,
  type HubSpotFormConfiguration,
  type HubSpotFormDefinition,
  type HubSpotFormDefinitionCreateRequest,
  type HubSpotFormDefinitionPatchRequest,
  type LegalConsentCheckbox,
  type LegalConsentOptionsExplicitConsentToProcess,
  type LegalConsentOptionsImplicitConsentToProcess,
  type LegalConsentOptionsLegitimateInterest,
  type LegalConsentOptionsNone,
  type LifecycleStage,
  type MobilePhoneField,
  type MultiLineTextField,
  type MultipleCheckboxesField,
  type NumberField,
  type NumberFieldValidation,
  type PaymentLinkRadioField,
  type PhoneField,
  type PhoneFieldValidation,
  type RadioField,
  type SingleCheckboxField,
  type SingleLineTextField,
  type FormCreateParams,
  type FormUpdateParams,
  type FormListParams,
  type FormReadParams,
  type FormReplaceParams,
  type HubSpotFormDefinitionsPage,
} from './forms';
export { Marketing } from './marketing';
export {
  Subscriptions,
  type PublicSubscriptionStatus,
  type PublicSubscriptionStatusesResponse,
  type PublicUpdateSubscriptionStatusRequest,
  type SubscriptionDefinition,
  type SubscriptionDefinitionsResponse,
  type SubscriptionSubscribeParams,
  type SubscriptionUnsubscribeParams,
} from './subscriptions/index';
export {
  Transactional,
  type CollectionResponseSmtpAPITokenViewForwardPaging,
  type SmtpAPITokenRequestEgg,
  type SmtpAPITokenView,
  type SmtpAPITokenViewsPage,
} from './transactional/index';
