// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as EmailsAPI from './emails';
import {
  AbTestCreateRequestVNext,
  AggregateEmailStatistics,
  CollectionResponseWithTotalEmailStatisticIntervalNoPaging,
  CollectionResponseWithTotalPublicEmailForwardPaging,
  CollectionResponseWithTotalVersionPublicEmail,
  EmailCloneParams,
  EmailCloneRequestVNext,
  EmailCreateAbTestVariationParams,
  EmailCreateParams,
  EmailCreateRequest,
  EmailDeleteParams,
  EmailGetEmailsListParams,
  EmailGetHistogramParams,
  EmailGetRevisionByIDParams,
  EmailGetRevisionsParams,
  EmailListParams,
  EmailReadParams,
  EmailRestoreDraftRevisionParams,
  EmailRestoreRevisionParams,
  EmailStatisticInterval,
  EmailStatisticsData,
  EmailUpdateParams,
  EmailUpdateRequest,
  EmailUpsertDraftParams,
  Emails,
  Interval,
  Paging,
  PublicButtonStyleSettings,
  PublicDividerStyleSettings,
  PublicEmail,
  PublicEmailContent,
  PublicEmailFromDetails,
  PublicEmailRecipients,
  PublicEmailStyleSettings,
  PublicEmailSubscriptionDetails,
  PublicEmailTestingDetails,
  PublicEmailToDetails,
  PublicEmailsPage,
  PublicFontStyle,
  PublicRssEmailDetails,
  PublicWebversionDetails,
  SmartEmailField,
  VersionPublicEmail,
  VersionUser,
} from './emails';
import * as FormsAPI from './forms';
import {
  CollectionResponseFormDefinitionBaseForwardPaging,
  DatepickerField,
  DependentField,
  DependentFieldFilter,
  DropdownField,
  EmailField,
  EmailFieldValidation,
  EnumeratedFieldOption,
  FieldGroup,
  FileField,
  FormCreateParams,
  FormDefinitionBase,
  FormDefinitionCreateRequestBase,
  FormDisplayOptions,
  FormListParams,
  FormPostSubmitAction,
  FormReadParams,
  FormReplaceParams,
  FormStyle,
  FormUpdateParams,
  Forms,
  HubSpotFormConfiguration,
  HubSpotFormDefinition,
  HubSpotFormDefinitionCreateRequest,
  HubSpotFormDefinitionPatchRequest,
  HubSpotFormDefinitionsPage,
  LegalConsentCheckbox,
  LegalConsentOptionsExplicitConsentToProcess,
  LegalConsentOptionsImplicitConsentToProcess,
  LegalConsentOptionsLegitimateInterest,
  LegalConsentOptionsNone,
  LifecycleStage,
  MobilePhoneField,
  MultiLineTextField,
  MultipleCheckboxesField,
  NumberField,
  NumberFieldValidation,
  PaymentLinkRadioField,
  PhoneField,
  PhoneFieldValidation,
  RadioField,
  SingleCheckboxField,
  SingleLineTextField,
} from './forms';
import * as SubscriptionsAPI from './subscriptions/subscriptions';
import {
  PublicSubscriptionStatus,
  PublicSubscriptionStatusesResponse,
  PublicUpdateSubscriptionStatusRequest,
  SubscriptionDefinition,
  SubscriptionDefinitionsResponse,
  SubscriptionSubscribeParams,
  SubscriptionUnsubscribeParams,
  Subscriptions,
} from './subscriptions/subscriptions';

export class Marketing extends APIResource {
  emails: EmailsAPI.Emails = new EmailsAPI.Emails(this._client);
  forms: FormsAPI.Forms = new FormsAPI.Forms(this._client);
  subscriptions: SubscriptionsAPI.Subscriptions = new SubscriptionsAPI.Subscriptions(this._client);
}

Marketing.Emails = Emails;
Marketing.Forms = Forms;
Marketing.Subscriptions = Subscriptions;

export declare namespace Marketing {
  export {
    Emails as Emails,
    type AbTestCreateRequestVNext as AbTestCreateRequestVNext,
    type AggregateEmailStatistics as AggregateEmailStatistics,
    type CollectionResponseWithTotalEmailStatisticIntervalNoPaging as CollectionResponseWithTotalEmailStatisticIntervalNoPaging,
    type CollectionResponseWithTotalPublicEmailForwardPaging as CollectionResponseWithTotalPublicEmailForwardPaging,
    type CollectionResponseWithTotalVersionPublicEmail as CollectionResponseWithTotalVersionPublicEmail,
    type EmailCloneRequestVNext as EmailCloneRequestVNext,
    type EmailCreateRequest as EmailCreateRequest,
    type EmailStatisticInterval as EmailStatisticInterval,
    type EmailStatisticsData as EmailStatisticsData,
    type EmailUpdateRequest as EmailUpdateRequest,
    type Interval as Interval,
    type Paging as Paging,
    type PublicButtonStyleSettings as PublicButtonStyleSettings,
    type PublicDividerStyleSettings as PublicDividerStyleSettings,
    type PublicEmail as PublicEmail,
    type PublicEmailContent as PublicEmailContent,
    type PublicEmailFromDetails as PublicEmailFromDetails,
    type PublicEmailRecipients as PublicEmailRecipients,
    type PublicEmailStyleSettings as PublicEmailStyleSettings,
    type PublicEmailSubscriptionDetails as PublicEmailSubscriptionDetails,
    type PublicEmailTestingDetails as PublicEmailTestingDetails,
    type PublicEmailToDetails as PublicEmailToDetails,
    type PublicFontStyle as PublicFontStyle,
    type PublicRssEmailDetails as PublicRssEmailDetails,
    type PublicWebversionDetails as PublicWebversionDetails,
    type SmartEmailField as SmartEmailField,
    type VersionPublicEmail as VersionPublicEmail,
    type VersionUser as VersionUser,
    type PublicEmailsPage as PublicEmailsPage,
    type EmailCreateParams as EmailCreateParams,
    type EmailUpdateParams as EmailUpdateParams,
    type EmailListParams as EmailListParams,
    type EmailDeleteParams as EmailDeleteParams,
    type EmailCloneParams as EmailCloneParams,
    type EmailCreateAbTestVariationParams as EmailCreateAbTestVariationParams,
    type EmailGetEmailsListParams as EmailGetEmailsListParams,
    type EmailGetHistogramParams as EmailGetHistogramParams,
    type EmailGetRevisionByIDParams as EmailGetRevisionByIDParams,
    type EmailGetRevisionsParams as EmailGetRevisionsParams,
    type EmailReadParams as EmailReadParams,
    type EmailRestoreDraftRevisionParams as EmailRestoreDraftRevisionParams,
    type EmailRestoreRevisionParams as EmailRestoreRevisionParams,
    type EmailUpsertDraftParams as EmailUpsertDraftParams,
  };

  export {
    Forms as Forms,
    type CollectionResponseFormDefinitionBaseForwardPaging as CollectionResponseFormDefinitionBaseForwardPaging,
    type DatepickerField as DatepickerField,
    type DependentField as DependentField,
    type DependentFieldFilter as DependentFieldFilter,
    type DropdownField as DropdownField,
    type EmailField as EmailField,
    type EmailFieldValidation as EmailFieldValidation,
    type EnumeratedFieldOption as EnumeratedFieldOption,
    type FieldGroup as FieldGroup,
    type FileField as FileField,
    type FormDefinitionBase as FormDefinitionBase,
    type FormDefinitionCreateRequestBase as FormDefinitionCreateRequestBase,
    type FormDisplayOptions as FormDisplayOptions,
    type FormPostSubmitAction as FormPostSubmitAction,
    type FormStyle as FormStyle,
    type HubSpotFormConfiguration as HubSpotFormConfiguration,
    type HubSpotFormDefinition as HubSpotFormDefinition,
    type HubSpotFormDefinitionCreateRequest as HubSpotFormDefinitionCreateRequest,
    type HubSpotFormDefinitionPatchRequest as HubSpotFormDefinitionPatchRequest,
    type LegalConsentCheckbox as LegalConsentCheckbox,
    type LegalConsentOptionsExplicitConsentToProcess as LegalConsentOptionsExplicitConsentToProcess,
    type LegalConsentOptionsImplicitConsentToProcess as LegalConsentOptionsImplicitConsentToProcess,
    type LegalConsentOptionsLegitimateInterest as LegalConsentOptionsLegitimateInterest,
    type LegalConsentOptionsNone as LegalConsentOptionsNone,
    type LifecycleStage as LifecycleStage,
    type MobilePhoneField as MobilePhoneField,
    type MultiLineTextField as MultiLineTextField,
    type MultipleCheckboxesField as MultipleCheckboxesField,
    type NumberField as NumberField,
    type NumberFieldValidation as NumberFieldValidation,
    type PaymentLinkRadioField as PaymentLinkRadioField,
    type PhoneField as PhoneField,
    type PhoneFieldValidation as PhoneFieldValidation,
    type RadioField as RadioField,
    type SingleCheckboxField as SingleCheckboxField,
    type SingleLineTextField as SingleLineTextField,
    type HubSpotFormDefinitionsPage as HubSpotFormDefinitionsPage,
    type FormCreateParams as FormCreateParams,
    type FormUpdateParams as FormUpdateParams,
    type FormListParams as FormListParams,
    type FormReadParams as FormReadParams,
    type FormReplaceParams as FormReplaceParams,
  };

  export {
    Subscriptions as Subscriptions,
    type PublicSubscriptionStatus as PublicSubscriptionStatus,
    type PublicSubscriptionStatusesResponse as PublicSubscriptionStatusesResponse,
    type PublicUpdateSubscriptionStatusRequest as PublicUpdateSubscriptionStatusRequest,
    type SubscriptionDefinition as SubscriptionDefinition,
    type SubscriptionDefinitionsResponse as SubscriptionDefinitionsResponse,
    type SubscriptionSubscribeParams as SubscriptionSubscribeParams,
    type SubscriptionUnsubscribeParams as SubscriptionUnsubscribeParams,
  };
}
