// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as EmailsAPI from './emails';
import {
  AggregateEmailStatistics,
  CollectionResponseWithTotalEmailStatisticIntervalNoPaging,
  CollectionResponseWithTotalPublicEmailForwardPaging,
  CollectionResponseWithTotalVersionPublicEmail,
  EmailCloneParams,
  EmailCloneRequestVNext,
  EmailCreateAbTestVariationParams,
  EmailCreateParams,
  EmailCreateRequest,
  EmailDeleteParams,
  EmailGetEmailsListParams,
  EmailGetHistogramParams,
  EmailGetRevisionByIDParams,
  EmailGetRevisionsParams,
  EmailListParams,
  EmailReadParams,
  EmailRestoreDraftRevisionParams,
  EmailRestoreRevisionParams,
  EmailStatisticInterval,
  EmailStatisticsData,
  EmailUpdateParams,
  EmailUpdateRequest,
  EmailUpsertDraftParams,
  Emails,
  Interval,
  Paging,
  PublicButtonStyleSettings,
  PublicDividerStyleSettings,
  PublicEmail,
  PublicEmailContent,
  PublicEmailFromDetails,
  PublicEmailRecipients,
  PublicEmailStyleSettings,
  PublicEmailSubscriptionDetails,
  PublicEmailTestingDetails,
  PublicEmailToDetails,
  PublicEmailsPage,
  PublicFontStyle,
  PublicRssEmailDetails,
  PublicWebversionDetails,
  SmartEmailField,
  VersionPublicEmail,
  VersionPublicEmailsPage,
} from './emails';
import * as FormsAPI from './forms';
import {
  CollectionResponseFormDefinitionBaseForwardPaging,
  DatepickerField,
  DependentField,
  DependentFieldFilter,
  DropdownField,
  EmailField,
  EmailFieldValidation,
  EnumeratedFieldOption,
  FieldGroup,
  FileField,
  FormCreateParams,
  FormDefinitionBase,
  FormDefinitionCreateRequestBase,
  FormDisplayOptions,
  FormListParams,
  FormPostSubmitAction,
  FormReadParams,
  FormReplaceParams,
  FormStyle,
  FormUpdateParams,
  Forms,
  HubSpotFormConfiguration,
  HubSpotFormDefinition,
  HubSpotFormDefinitionCreateRequest,
  HubSpotFormDefinitionPatchRequest,
  HubSpotFormDefinitionsPage,
  LegalConsentCheckbox,
  LegalConsentOptionsExplicitConsentToProcess,
  LegalConsentOptionsImplicitConsentToProcess,
  LegalConsentOptionsLegitimateInterest,
  LegalConsentOptionsNone,
  LifecycleStage,
  MobilePhoneField,
  MultiLineTextField,
  MultipleCheckboxesField,
  NumberField,
  NumberFieldValidation,
  PaymentLinkRadioField,
  PhoneField,
  PhoneFieldValidation,
  RadioField,
  SingleCheckboxField,
  SingleLineTextField,
} from './forms';
import * as MarketingEventsAPI from './marketing-events/marketing-events';
import {
  AppInfo,
  AttendanceCounters,
  BatchInputMarketingEventCreateRequestParams,
  BatchInputMarketingEventEmailSubscriber,
  BatchInputMarketingEventExternalUniqueIdentifier,
  BatchInputMarketingEventPublicObjectIDDeleteRequest,
  BatchInputMarketingEventPublicUpdateRequestFullV2,
  BatchInputMarketingEventSubscriber,
  BatchResponseMarketingEventPublicDefaultResponse,
  BatchResponseMarketingEventPublicDefaultResponseV2,
  BatchResponseMarketingEventPublicDefaultResponseV2WithErrors,
  BatchResponseSubscriberEmailResponse,
  BatchResponseSubscriberVidResponse,
  CRMPropertyWrapper,
  CollectionResponseMarketingEventPublicReadResponseV2ForwardPaging,
  CollectionResponseSearchPublicResponseWrapperNoPaging,
  CollectionResponseWithTotalMarketingEventIdentifiersResponseNoPaging,
  CollectionResponseWithTotalParticipationBreakdownForwardPaging,
  CollectionResponseWithTotalPublicListNoPaging,
  ContactAssociation,
  EventDetailSettings,
  EventDetailSettingsURL,
  MarketingEventAssociation,
  MarketingEventCancelByExternalEventIDParams,
  MarketingEventCompleteByExternalEventIDParams,
  MarketingEventCompleteRequestParams,
  MarketingEventCreateParams,
  MarketingEventCreateRequestParams,
  MarketingEventDefaultResponse,
  MarketingEventDeleteBatchByExternalEventIDParams,
  MarketingEventDeleteBatchParams,
  MarketingEventDeleteByExternalEventIDParams,
  MarketingEventEmailSubscriber,
  MarketingEventExternalUniqueIdentifier,
  MarketingEventGetByExternalEventIDParams,
  MarketingEventIdentifiersResponse,
  MarketingEventListParams,
  MarketingEventPublicDefaultResponse,
  MarketingEventPublicDefaultResponseV2,
  MarketingEventPublicObjectIDDeleteRequest,
  MarketingEventPublicReadResponse,
  MarketingEventPublicReadResponseV2,
  MarketingEventPublicReadResponseV2sPage,
  MarketingEventPublicUpdateRequestFullV2,
  MarketingEventPublicUpdateRequestV2,
  MarketingEventSearchByExternalEventIDParams,
  MarketingEventSubscriber,
  MarketingEventUpdateBatchParams,
  MarketingEventUpdateByExternalEventIDParams,
  MarketingEventUpdateParams,
  MarketingEventUpdateRequestParams,
  MarketingEventUpsertBatchParams,
  MarketingEventUpsertByExternalEventIDParams,
  MarketingEventUpsertSubscriberStateByEmailParams,
  MarketingEventUpsertSubscriberStateByIDParams,
  MarketingEvents,
  ParticipationAssociations,
  ParticipationBreakdown,
  ParticipationProperties,
  PropertyValue,
  PublicList,
  SearchPublicResponseWrapper,
  SubscriberEmailResponse,
  SubscriberVidResponse,
} from './marketing-events/marketing-events';
import * as SubscriptionsAPI from './subscriptions/subscriptions';
import {
  PublicSubscriptionStatus,
  PublicSubscriptionStatusesResponse,
  PublicUpdateSubscriptionStatusRequest,
  SubscriptionDefinition,
  SubscriptionDefinitionsResponse,
  SubscriptionSubscribeParams,
  SubscriptionUnsubscribeParams,
  Subscriptions,
} from './subscriptions/subscriptions';
import * as TransactionalAPI from './transactional/transactional';
import {
  CollectionResponseSmtpAPITokenViewForwardPaging,
  EmailSendStatusView,
  EventIDView,
  PublicSingleSendEmail,
  PublicSingleSendRequestEgg,
  SmtpAPITokenRequestEgg,
  SmtpAPITokenView,
  Transactional,
} from './transactional/transactional';

export class Marketing extends APIResource {
  emails: EmailsAPI.Emails = new EmailsAPI.Emails(this._client);
  forms: FormsAPI.Forms = new FormsAPI.Forms(this._client);
  marketingEvents: MarketingEventsAPI.MarketingEvents = new MarketingEventsAPI.MarketingEvents(this._client);
  subscriptions: SubscriptionsAPI.Subscriptions = new SubscriptionsAPI.Subscriptions(this._client);
  transactional: TransactionalAPI.Transactional = new TransactionalAPI.Transactional(this._client);
}

Marketing.Emails = Emails;
Marketing.Forms = Forms;
Marketing.MarketingEvents = MarketingEvents;
Marketing.Subscriptions = Subscriptions;
Marketing.Transactional = Transactional;

export declare namespace Marketing {
  export {
    Emails as Emails,
    type AggregateEmailStatistics as AggregateEmailStatistics,
    type CollectionResponseWithTotalEmailStatisticIntervalNoPaging as CollectionResponseWithTotalEmailStatisticIntervalNoPaging,
    type CollectionResponseWithTotalPublicEmailForwardPaging as CollectionResponseWithTotalPublicEmailForwardPaging,
    type CollectionResponseWithTotalVersionPublicEmail as CollectionResponseWithTotalVersionPublicEmail,
    type EmailCloneRequestVNext as EmailCloneRequestVNext,
    type EmailCreateRequest as EmailCreateRequest,
    type EmailStatisticInterval as EmailStatisticInterval,
    type EmailStatisticsData as EmailStatisticsData,
    type EmailUpdateRequest as EmailUpdateRequest,
    type Interval as Interval,
    type Paging as Paging,
    type PublicButtonStyleSettings as PublicButtonStyleSettings,
    type PublicDividerStyleSettings as PublicDividerStyleSettings,
    type PublicEmail as PublicEmail,
    type PublicEmailContent as PublicEmailContent,
    type PublicEmailFromDetails as PublicEmailFromDetails,
    type PublicEmailRecipients as PublicEmailRecipients,
    type PublicEmailStyleSettings as PublicEmailStyleSettings,
    type PublicEmailSubscriptionDetails as PublicEmailSubscriptionDetails,
    type PublicEmailTestingDetails as PublicEmailTestingDetails,
    type PublicEmailToDetails as PublicEmailToDetails,
    type PublicFontStyle as PublicFontStyle,
    type PublicRssEmailDetails as PublicRssEmailDetails,
    type PublicWebversionDetails as PublicWebversionDetails,
    type SmartEmailField as SmartEmailField,
    type VersionPublicEmail as VersionPublicEmail,
    type PublicEmailsPage as PublicEmailsPage,
    type VersionPublicEmailsPage as VersionPublicEmailsPage,
    type EmailCreateParams as EmailCreateParams,
    type EmailUpdateParams as EmailUpdateParams,
    type EmailListParams as EmailListParams,
    type EmailDeleteParams as EmailDeleteParams,
    type EmailCloneParams as EmailCloneParams,
    type EmailCreateAbTestVariationParams as EmailCreateAbTestVariationParams,
    type EmailGetEmailsListParams as EmailGetEmailsListParams,
    type EmailGetHistogramParams as EmailGetHistogramParams,
    type EmailGetRevisionByIDParams as EmailGetRevisionByIDParams,
    type EmailGetRevisionsParams as EmailGetRevisionsParams,
    type EmailReadParams as EmailReadParams,
    type EmailRestoreDraftRevisionParams as EmailRestoreDraftRevisionParams,
    type EmailRestoreRevisionParams as EmailRestoreRevisionParams,
    type EmailUpsertDraftParams as EmailUpsertDraftParams,
  };

  export {
    Forms as Forms,
    type CollectionResponseFormDefinitionBaseForwardPaging as CollectionResponseFormDefinitionBaseForwardPaging,
    type DatepickerField as DatepickerField,
    type DependentField as DependentField,
    type DependentFieldFilter as DependentFieldFilter,
    type DropdownField as DropdownField,
    type EmailField as EmailField,
    type EmailFieldValidation as EmailFieldValidation,
    type EnumeratedFieldOption as EnumeratedFieldOption,
    type FieldGroup as FieldGroup,
    type FileField as FileField,
    type FormDefinitionBase as FormDefinitionBase,
    type FormDefinitionCreateRequestBase as FormDefinitionCreateRequestBase,
    type FormDisplayOptions as FormDisplayOptions,
    type FormPostSubmitAction as FormPostSubmitAction,
    type FormStyle as FormStyle,
    type HubSpotFormConfiguration as HubSpotFormConfiguration,
    type HubSpotFormDefinition as HubSpotFormDefinition,
    type HubSpotFormDefinitionCreateRequest as HubSpotFormDefinitionCreateRequest,
    type HubSpotFormDefinitionPatchRequest as HubSpotFormDefinitionPatchRequest,
    type LegalConsentCheckbox as LegalConsentCheckbox,
    type LegalConsentOptionsExplicitConsentToProcess as LegalConsentOptionsExplicitConsentToProcess,
    type LegalConsentOptionsImplicitConsentToProcess as LegalConsentOptionsImplicitConsentToProcess,
    type LegalConsentOptionsLegitimateInterest as LegalConsentOptionsLegitimateInterest,
    type LegalConsentOptionsNone as LegalConsentOptionsNone,
    type LifecycleStage as LifecycleStage,
    type MobilePhoneField as MobilePhoneField,
    type MultiLineTextField as MultiLineTextField,
    type MultipleCheckboxesField as MultipleCheckboxesField,
    type NumberField as NumberField,
    type NumberFieldValidation as NumberFieldValidation,
    type PaymentLinkRadioField as PaymentLinkRadioField,
    type PhoneField as PhoneField,
    type PhoneFieldValidation as PhoneFieldValidation,
    type RadioField as RadioField,
    type SingleCheckboxField as SingleCheckboxField,
    type SingleLineTextField as SingleLineTextField,
    type HubSpotFormDefinitionsPage as HubSpotFormDefinitionsPage,
    type FormCreateParams as FormCreateParams,
    type FormUpdateParams as FormUpdateParams,
    type FormListParams as FormListParams,
    type FormReadParams as FormReadParams,
    type FormReplaceParams as FormReplaceParams,
  };

  export {
    MarketingEvents as MarketingEvents,
    type AppInfo as AppInfo,
    type AttendanceCounters as AttendanceCounters,
    type BatchInputMarketingEventCreateRequestParams as BatchInputMarketingEventCreateRequestParams,
    type BatchInputMarketingEventEmailSubscriber as BatchInputMarketingEventEmailSubscriber,
    type BatchInputMarketingEventExternalUniqueIdentifier as BatchInputMarketingEventExternalUniqueIdentifier,
    type BatchInputMarketingEventPublicObjectIDDeleteRequest as BatchInputMarketingEventPublicObjectIDDeleteRequest,
    type BatchInputMarketingEventPublicUpdateRequestFullV2 as BatchInputMarketingEventPublicUpdateRequestFullV2,
    type BatchInputMarketingEventSubscriber as BatchInputMarketingEventSubscriber,
    type BatchResponseMarketingEventPublicDefaultResponse as BatchResponseMarketingEventPublicDefaultResponse,
    type BatchResponseMarketingEventPublicDefaultResponseV2 as BatchResponseMarketingEventPublicDefaultResponseV2,
    type BatchResponseMarketingEventPublicDefaultResponseV2WithErrors as BatchResponseMarketingEventPublicDefaultResponseV2WithErrors,
    type BatchResponseSubscriberEmailResponse as BatchResponseSubscriberEmailResponse,
    type BatchResponseSubscriberVidResponse as BatchResponseSubscriberVidResponse,
    type CollectionResponseMarketingEventPublicReadResponseV2ForwardPaging as CollectionResponseMarketingEventPublicReadResponseV2ForwardPaging,
    type CollectionResponseSearchPublicResponseWrapperNoPaging as CollectionResponseSearchPublicResponseWrapperNoPaging,
    type CollectionResponseWithTotalMarketingEventIdentifiersResponseNoPaging as CollectionResponseWithTotalMarketingEventIdentifiersResponseNoPaging,
    type CollectionResponseWithTotalParticipationBreakdownForwardPaging as CollectionResponseWithTotalParticipationBreakdownForwardPaging,
    type CollectionResponseWithTotalPublicListNoPaging as CollectionResponseWithTotalPublicListNoPaging,
    type ContactAssociation as ContactAssociation,
    type CRMPropertyWrapper as CRMPropertyWrapper,
    type EventDetailSettings as EventDetailSettings,
    type EventDetailSettingsURL as EventDetailSettingsURL,
    type MarketingEventAssociation as MarketingEventAssociation,
    type MarketingEventCompleteRequestParams as MarketingEventCompleteRequestParams,
    type MarketingEventCreateRequestParams as MarketingEventCreateRequestParams,
    type MarketingEventDefaultResponse as MarketingEventDefaultResponse,
    type MarketingEventEmailSubscriber as MarketingEventEmailSubscriber,
    type MarketingEventExternalUniqueIdentifier as MarketingEventExternalUniqueIdentifier,
    type MarketingEventIdentifiersResponse as MarketingEventIdentifiersResponse,
    type MarketingEventPublicDefaultResponse as MarketingEventPublicDefaultResponse,
    type MarketingEventPublicDefaultResponseV2 as MarketingEventPublicDefaultResponseV2,
    type MarketingEventPublicObjectIDDeleteRequest as MarketingEventPublicObjectIDDeleteRequest,
    type MarketingEventPublicReadResponse as MarketingEventPublicReadResponse,
    type MarketingEventPublicReadResponseV2 as MarketingEventPublicReadResponseV2,
    type MarketingEventPublicUpdateRequestFullV2 as MarketingEventPublicUpdateRequestFullV2,
    type MarketingEventPublicUpdateRequestV2 as MarketingEventPublicUpdateRequestV2,
    type MarketingEventSubscriber as MarketingEventSubscriber,
    type MarketingEventUpdateRequestParams as MarketingEventUpdateRequestParams,
    type ParticipationAssociations as ParticipationAssociations,
    type ParticipationBreakdown as ParticipationBreakdown,
    type ParticipationProperties as ParticipationProperties,
    type PropertyValue as PropertyValue,
    type PublicList as PublicList,
    type SearchPublicResponseWrapper as SearchPublicResponseWrapper,
    type SubscriberEmailResponse as SubscriberEmailResponse,
    type SubscriberVidResponse as SubscriberVidResponse,
    type MarketingEventPublicReadResponseV2sPage as MarketingEventPublicReadResponseV2sPage,
    type MarketingEventCreateParams as MarketingEventCreateParams,
    type MarketingEventUpdateParams as MarketingEventUpdateParams,
    type MarketingEventListParams as MarketingEventListParams,
    type MarketingEventCancelByExternalEventIDParams as MarketingEventCancelByExternalEventIDParams,
    type MarketingEventCompleteByExternalEventIDParams as MarketingEventCompleteByExternalEventIDParams,
    type MarketingEventDeleteBatchParams as MarketingEventDeleteBatchParams,
    type MarketingEventDeleteBatchByExternalEventIDParams as MarketingEventDeleteBatchByExternalEventIDParams,
    type MarketingEventDeleteByExternalEventIDParams as MarketingEventDeleteByExternalEventIDParams,
    type MarketingEventGetByExternalEventIDParams as MarketingEventGetByExternalEventIDParams,
    type MarketingEventSearchByExternalEventIDParams as MarketingEventSearchByExternalEventIDParams,
    type MarketingEventUpdateBatchParams as MarketingEventUpdateBatchParams,
    type MarketingEventUpdateByExternalEventIDParams as MarketingEventUpdateByExternalEventIDParams,
    type MarketingEventUpsertBatchParams as MarketingEventUpsertBatchParams,
    type MarketingEventUpsertByExternalEventIDParams as MarketingEventUpsertByExternalEventIDParams,
    type MarketingEventUpsertSubscriberStateByEmailParams as MarketingEventUpsertSubscriberStateByEmailParams,
    type MarketingEventUpsertSubscriberStateByIDParams as MarketingEventUpsertSubscriberStateByIDParams,
  };

  export {
    Subscriptions as Subscriptions,
    type PublicSubscriptionStatus as PublicSubscriptionStatus,
    type PublicSubscriptionStatusesResponse as PublicSubscriptionStatusesResponse,
    type PublicUpdateSubscriptionStatusRequest as PublicUpdateSubscriptionStatusRequest,
    type SubscriptionDefinition as SubscriptionDefinition,
    type SubscriptionDefinitionsResponse as SubscriptionDefinitionsResponse,
    type SubscriptionSubscribeParams as SubscriptionSubscribeParams,
    type SubscriptionUnsubscribeParams as SubscriptionUnsubscribeParams,
  };

  export {
    Transactional as Transactional,
    type CollectionResponseSmtpAPITokenViewForwardPaging as CollectionResponseSmtpAPITokenViewForwardPaging,
    type EmailSendStatusView as EmailSendStatusView,
    type EventIDView as EventIDView,
    type PublicSingleSendEmail as PublicSingleSendEmail,
    type PublicSingleSendRequestEgg as PublicSingleSendRequestEgg,
    type SmtpAPITokenRequestEgg as SmtpAPITokenRequestEgg,
    type SmtpAPITokenView as SmtpAPITokenView,
  };
}
