// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

export {
  Meetings,
  type CollectionResponseWithTotalExternalLinkMetadataForwardPaging,
  type ExternalAssociationCreateRequest,
  type ExternalBookingFormField,
  type ExternalBookingInfo,
  type ExternalBrandingMetadata,
  type ExternalCalendarMeetingEventCreateProperties,
  type ExternalCalendarMeetingEventCreateRequest,
  type ExternalCalendarMeetingEventResponseProperties,
  type ExternalCalenderMeetingEventResponse,
  type ExternalClosedRange,
  type ExternalCommunicationConsentCheckbox,
  type ExternalEmailReminderSchedule,
  type ExternalGuestSettings,
  type ExternalLegalConsentOptions,
  type ExternalLegalConsentResponse,
  type ExternalLinkAvailability,
  type ExternalLinkAvailabilityAndBusyTimes,
  type ExternalLinkAvailabilityForDuration,
  type ExternalLinkDisplayInfo,
  type ExternalLinkFormField,
  type ExternalLinkMetadata,
  type ExternalMeetingAvailability,
  type ExternalMeetingBooking,
  type ExternalMeetingBookingResponse,
  type ExternalMeetingsLinkSettings,
  type ExternalMeetingsUser,
  type ExternalMeetingsWelcomeScreenInfo,
  type ExternalOption,
  type ExternalReminder,
  type ExternalTimeRange,
  type ExternalUserBusyTimes,
  type ExternalUserProfile,
  type ExternalValidatedFormField,
} from './meetings';
export { Scheduler } from './scheduler';
