// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as SendAPI from './send';
import {
  AbsoluteComparativeTimestampRefineBy,
  AbsoluteRangedTimestampRefineBy,
  AllHistoryRefineBy,
  AllPropertyTypesOperation,
  AssociationDefinition,
  BatchedBehavioralEventHTTPCompletionRequest,
  BehavioralEventHTTPCompletionRequest,
  BehavioralEventTypeDefinitionLabels,
  BoolPropertyOperation,
  CalendarDatePropertyOperation,
  CollectionResponseWithTotalExternalBehavioralEventTypeDefinition,
  ComboEventRule,
  ComboEventRuleBranch,
  ComparativeBoolPropertyOperation,
  ComparativeDatePropertyOperation,
  ComparativeNumberPropertyOperation,
  ComparativePropertyUpdatedOperation,
  ComparativeStringPropertyOperation,
  DatePoint,
  DatePropertyOperation,
  DateTimePropertyOperation,
  EnumerationPropertyOperation,
  ExternalBehavioralEventPropertyCreate,
  ExternalBehavioralEventPropertyDefinitionPatch,
  ExternalBehavioralEventTypeDefinition,
  ExternalBehavioralEventTypeDefinitionEgg,
  ExternalBehavioralEventTypeDefinitionPatch,
  ExternalBehavioralEventTypeDefinitionsPage,
  ExternalObjectResolutionMappingRequest,
  ExternalObjectResolutionMappingResponse,
  ExternalPrimaryObjectResolutionRule,
  FiscalQuarter,
  FiscalYear,
  IndexOffset,
  IndexedTimePoint,
  MonthReference,
  MultiStringPropertyOperation,
  NowReference,
  NumOccurrencesRefineBy,
  NumberPropertyOperation,
  Option,
  OptionInput,
  Property,
  PropertyFilter,
  PropertyFilterContext,
  PropertyModificationMetadata,
  PropertyReferencedTime,
  QuarterReference,
  RangedDatePropertyOperation,
  RangedNumberPropertyOperation,
  RangedTimeOperation,
  RegexPropertyOperation,
  RelativeComparativeTimestampRefineBy,
  RelativeRangedTimestampRefineBy,
  RollingDateRangePropertyOperation,
  RollingPropertyUpdatedOperation,
  Send,
  SendCreateEventDefinitionParams,
  SendCreateEventDefinitionPropertyParams,
  SendDeleteEventDefinitionPropertyParams,
  SendListEventDefinitionsParams,
  SendSendEventBatchParams,
  SendSendEventParams,
  SendUpdateEventDefinitionParams,
  SendUpdateEventDefinitionPropertyParams,
  SetOccurrencesRefineBy,
  StringPropertyOperation,
  TimeOffset,
  TimePointOperation,
  TodayReference,
  WeekReference,
  YearReference,
} from './send';

export class Events extends APIResource {
  send: SendAPI.Send = new SendAPI.Send(this._client);
}

Events.Send = Send;

export declare namespace Events {
  export {
    Send as Send,
    type AbsoluteComparativeTimestampRefineBy as AbsoluteComparativeTimestampRefineBy,
    type AbsoluteRangedTimestampRefineBy as AbsoluteRangedTimestampRefineBy,
    type AllHistoryRefineBy as AllHistoryRefineBy,
    type AllPropertyTypesOperation as AllPropertyTypesOperation,
    type AssociationDefinition as AssociationDefinition,
    type BatchedBehavioralEventHTTPCompletionRequest as BatchedBehavioralEventHTTPCompletionRequest,
    type BehavioralEventHTTPCompletionRequest as BehavioralEventHTTPCompletionRequest,
    type BehavioralEventTypeDefinitionLabels as BehavioralEventTypeDefinitionLabels,
    type BoolPropertyOperation as BoolPropertyOperation,
    type CalendarDatePropertyOperation as CalendarDatePropertyOperation,
    type CollectionResponseWithTotalExternalBehavioralEventTypeDefinition as CollectionResponseWithTotalExternalBehavioralEventTypeDefinition,
    type ComboEventRule as ComboEventRule,
    type ComboEventRuleBranch as ComboEventRuleBranch,
    type ComparativeBoolPropertyOperation as ComparativeBoolPropertyOperation,
    type ComparativeDatePropertyOperation as ComparativeDatePropertyOperation,
    type ComparativeNumberPropertyOperation as ComparativeNumberPropertyOperation,
    type ComparativePropertyUpdatedOperation as ComparativePropertyUpdatedOperation,
    type ComparativeStringPropertyOperation as ComparativeStringPropertyOperation,
    type DatePoint as DatePoint,
    type DatePropertyOperation as DatePropertyOperation,
    type DateTimePropertyOperation as DateTimePropertyOperation,
    type EnumerationPropertyOperation as EnumerationPropertyOperation,
    type ExternalBehavioralEventPropertyCreate as ExternalBehavioralEventPropertyCreate,
    type ExternalBehavioralEventPropertyDefinitionPatch as ExternalBehavioralEventPropertyDefinitionPatch,
    type ExternalBehavioralEventTypeDefinition as ExternalBehavioralEventTypeDefinition,
    type ExternalBehavioralEventTypeDefinitionEgg as ExternalBehavioralEventTypeDefinitionEgg,
    type ExternalBehavioralEventTypeDefinitionPatch as ExternalBehavioralEventTypeDefinitionPatch,
    type ExternalObjectResolutionMappingRequest as ExternalObjectResolutionMappingRequest,
    type ExternalObjectResolutionMappingResponse as ExternalObjectResolutionMappingResponse,
    type ExternalPrimaryObjectResolutionRule as ExternalPrimaryObjectResolutionRule,
    type FiscalQuarter as FiscalQuarter,
    type FiscalYear as FiscalYear,
    type IndexOffset as IndexOffset,
    type IndexedTimePoint as IndexedTimePoint,
    type MonthReference as MonthReference,
    type MultiStringPropertyOperation as MultiStringPropertyOperation,
    type NowReference as NowReference,
    type NumOccurrencesRefineBy as NumOccurrencesRefineBy,
    type NumberPropertyOperation as NumberPropertyOperation,
    type Option as Option,
    type OptionInput as OptionInput,
    type Property as Property,
    type PropertyFilter as PropertyFilter,
    type PropertyFilterContext as PropertyFilterContext,
    type PropertyModificationMetadata as PropertyModificationMetadata,
    type PropertyReferencedTime as PropertyReferencedTime,
    type QuarterReference as QuarterReference,
    type RangedDatePropertyOperation as RangedDatePropertyOperation,
    type RangedNumberPropertyOperation as RangedNumberPropertyOperation,
    type RangedTimeOperation as RangedTimeOperation,
    type RegexPropertyOperation as RegexPropertyOperation,
    type RelativeComparativeTimestampRefineBy as RelativeComparativeTimestampRefineBy,
    type RelativeRangedTimestampRefineBy as RelativeRangedTimestampRefineBy,
    type RollingDateRangePropertyOperation as RollingDateRangePropertyOperation,
    type RollingPropertyUpdatedOperation as RollingPropertyUpdatedOperation,
    type SetOccurrencesRefineBy as SetOccurrencesRefineBy,
    type StringPropertyOperation as StringPropertyOperation,
    type TimeOffset as TimeOffset,
    type TimePointOperation as TimePointOperation,
    type TodayReference as TodayReference,
    type WeekReference as WeekReference,
    type YearReference as YearReference,
    type ExternalBehavioralEventTypeDefinitionsPage as ExternalBehavioralEventTypeDefinitionsPage,
    type SendCreateEventDefinitionParams as SendCreateEventDefinitionParams,
    type SendCreateEventDefinitionPropertyParams as SendCreateEventDefinitionPropertyParams,
    type SendDeleteEventDefinitionPropertyParams as SendDeleteEventDefinitionPropertyParams,
    type SendListEventDefinitionsParams as SendListEventDefinitionsParams,
    type SendSendEventParams as SendSendEventParams,
    type SendSendEventBatchParams as SendSendEventBatchParams,
    type SendUpdateEventDefinitionParams as SendUpdateEventDefinitionParams,
    type SendUpdateEventDefinitionPropertyParams as SendUpdateEventDefinitionPropertyParams,
  };
}
