// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as ActionsAPI from './actions';
import {
  ActionArchiveByFunctionTypeParams,
  ActionCompleteBatchParams,
  ActionCompleteParams,
  ActionCreateOrReplaceByFunctionTypeParams,
  ActionCreateOrReplaceParams,
  ActionCreateParams,
  ActionDeleteParams,
  ActionGetByFunctionTypeParams,
  ActionListParams,
  ActionReadParams,
  ActionUpdateParams,
  Actions,
  BatchInputCallbackCompletionBatchRequest,
  CallbackCompletionBatchRequest,
  CallbackCompletionRequest,
  CollectionResponsePublicActionDefinitionForwardPaging,
  CollectionResponsePublicActionFunctionIdentifierNoPaging,
  CollectionResponsePublicActionRevisionForwardPaging,
  FieldTypeDefinition,
  InputFieldDefinition,
  Option,
  OutputFieldDefinition,
  PublicActionDefinition,
  PublicActionDefinitionEgg,
  PublicActionDefinitionPatch,
  PublicActionFunction,
  PublicActionFunctionIdentifier,
  PublicActionLabels,
  PublicActionRevision,
  PublicActionRevisionsPage,
  PublicConditionalSingleFieldDependency,
  PublicExecutionTranslationRule,
  PublicObjectRequestOptions,
  PublicSingleFieldDependency,
} from './actions';
import * as WorkflowsAPI from './workflows';
import {
  APIAbTestBranchAction,
  APIActionDataValue,
  APIAppendObjectPropertyValue,
  APIAssociationDataSource,
  APIAssociationTimestampDataSource,
  APIAuthKeyWebhookAuthSettings,
  APIBlockedDate,
  APIConnection,
  APIContactFlow,
  APIContactFlowCreateRequest,
  APIContactFlowPutRequest,
  APIContactPropertyAnchor,
  APICustomCodeAction,
  APIDailyEnrollmentSchedule,
  APIDatasetFieldPropertyFilterDataSource,
  APIEnrolledArgumentPropertyFilterDataSource,
  APIEnrolledRecordPropertyFilterDataSource,
  APIEnrollmentEventPropertyValue,
  APIEnumerationOutputField,
  APIEventBasedEnrollmentCriteria,
  APIFetchedObjectPropertyValue,
  APIFlow,
  APIFlowBatchFetchFlowIDCoordinate,
  APIFlowBatchFetchMigrationFlowIDCoordinate,
  APIFlowBatchFetchMigrationWorkflowIDCoordinate,
  APIFlowBatchInput,
  APIFlowBatchMigrationInput,
  APIFlowCreateRequest,
  APIFlowEmailCampaign,
  APIFlowListing,
  APIFlowPutRequest,
  APIIncrementValue,
  APIInputVariable,
  APIListBasedEnrollmentCriteria,
  APIListBranch,
  APIListBranchAction,
  APIManualEnrollmentCriteria,
  APIMonthlyRelativeDaysEnrollmentSchedule,
  APIMonthlySpecificDaysEnrollmentSchedule,
  APIObjectPropertyValue,
  APIPlatformFlow,
  APIPlatformFlowCreateRequest,
  APIPlatformFlowPutRequest,
  APIPropertyBasedEnrollmentSchedule,
  APIRelativeDateTimeValue,
  APISignatureWebhookAuthSettings,
  APISingleConnectionAction,
  APISort,
  APIStaticAppendValue,
  APIStaticBranch,
  APIStaticBranchAction,
  APIStaticDateAnchor,
  APIStaticPropertyFilterDataSource,
  APIStaticTimeZoneStrategy,
  APIStaticValue,
  APITimeDelay,
  APITimeOfDay,
  APITimeWindow,
  APITimestampValue,
  APIUnEnrollmentSetting,
  APIWebhookAction,
  APIWeeklyEnrollmentSchedule,
  APIYearlyEnrollmentSchedule,
  BatchResponseAPIFlow,
  BatchResponseAPIFlowWithErrors,
  BatchResponseFlowIDWorkflowIDMappingResponse,
  BatchResponseFlowIDWorkflowIDMappingResponseWithErrors,
  CollectionResponseAPIFlowEmailCampaign,
  CollectionResponseAPIFlowListingForwardPaging,
  FlowIDWorkflowIDMappingResponse,
  PublicAbsoluteComparativeTimestampRefineBy,
  PublicAbsoluteRangedTimestampRefineBy,
  PublicAdsSearchFilter,
  PublicAdsTimeFilter,
  PublicAllHistoryRefineBy,
  PublicAllPropertyTypesOperation,
  PublicAndFilterBranch,
  PublicAssociationFilterBranch,
  PublicAssociationInListFilter,
  PublicBoolPropertyOperation,
  PublicCalendarDatePropertyOperation,
  PublicCampaignInfluencedFilter,
  PublicCommunicationSubscriptionFilter,
  PublicComparativeDatePropertyOperation,
  PublicComparativePropertyUpdatedOperation,
  PublicConstantFilter,
  PublicCtaAnalyticsFilter,
  PublicDatePoint,
  PublicDatePropertyOperation,
  PublicDateTimePropertyOperation,
  PublicEmailEventFilter,
  PublicEmailSubscriptionFilter,
  PublicEnumerationPropertyOperation,
  PublicEventAnalyticsFilter,
  PublicEventFilterMetadata,
  PublicFiscalQuarterReference,
  PublicFiscalYearReference,
  PublicFormSubmissionFilter,
  PublicFormSubmissionOnPageFilter,
  PublicInListFilter,
  PublicInListFilterMetadata,
  PublicIndexOffset,
  PublicIndexedTimePoint,
  PublicIntegrationEventFilter,
  PublicMonthReference,
  PublicMultiStringPropertyOperation,
  PublicNotAllFilterBranch,
  PublicNotAnyFilterBranch,
  PublicNowReference,
  PublicNumAssociationsFilter,
  PublicNumOccurrencesRefineBy,
  PublicNumberPropertyOperation,
  PublicOrFilterBranch,
  PublicPageViewAnalyticsFilter,
  PublicPrivacyAnalyticsFilter,
  PublicPropertyAssociationFilterBranch,
  PublicPropertyAssociationInListFilter,
  PublicPropertyFilter,
  PublicPropertyReferencedTime,
  PublicQuarterReference,
  PublicRangedDatePropertyOperation,
  PublicRangedNumberPropertyOperation,
  PublicRangedTimeOperation,
  PublicRelativeComparativeTimestampRefineBy,
  PublicRelativeRangedTimestampRefineBy,
  PublicRestrictedFilterBranch,
  PublicRollingDateRangePropertyOperation,
  PublicRollingPropertyUpdatedOperation,
  PublicSetOccurrencesRefineBy,
  PublicStringPropertyOperation,
  PublicSurveyMonkeyFilter,
  PublicSurveyMonkeyValueFilter,
  PublicTimeOffset,
  PublicTimePointOperation,
  PublicTodayReference,
  PublicUnifiedEventsFilter,
  PublicUnifiedEventsFilterBranch,
  PublicWebinarFilter,
  PublicWeekReference,
  PublicYearReference,
  Workflows,
} from './workflows';

export class Automation extends APIResource {
  actions: ActionsAPI.Actions = new ActionsAPI.Actions(this._client);
  workflows: WorkflowsAPI.Workflows = new WorkflowsAPI.Workflows(this._client);
}

Automation.Actions = Actions;
Automation.Workflows = Workflows;

export declare namespace Automation {
  export {
    Actions as Actions,
    type BatchInputCallbackCompletionBatchRequest as BatchInputCallbackCompletionBatchRequest,
    type CallbackCompletionBatchRequest as CallbackCompletionBatchRequest,
    type CallbackCompletionRequest as CallbackCompletionRequest,
    type CollectionResponsePublicActionDefinitionForwardPaging as CollectionResponsePublicActionDefinitionForwardPaging,
    type CollectionResponsePublicActionFunctionIdentifierNoPaging as CollectionResponsePublicActionFunctionIdentifierNoPaging,
    type CollectionResponsePublicActionRevisionForwardPaging as CollectionResponsePublicActionRevisionForwardPaging,
    type FieldTypeDefinition as FieldTypeDefinition,
    type InputFieldDefinition as InputFieldDefinition,
    type Option as Option,
    type OutputFieldDefinition as OutputFieldDefinition,
    type PublicActionDefinition as PublicActionDefinition,
    type PublicActionDefinitionEgg as PublicActionDefinitionEgg,
    type PublicActionDefinitionPatch as PublicActionDefinitionPatch,
    type PublicActionFunction as PublicActionFunction,
    type PublicActionFunctionIdentifier as PublicActionFunctionIdentifier,
    type PublicActionLabels as PublicActionLabels,
    type PublicActionRevision as PublicActionRevision,
    type PublicConditionalSingleFieldDependency as PublicConditionalSingleFieldDependency,
    type PublicExecutionTranslationRule as PublicExecutionTranslationRule,
    type PublicObjectRequestOptions as PublicObjectRequestOptions,
    type PublicSingleFieldDependency as PublicSingleFieldDependency,
    type PublicActionRevisionsPage as PublicActionRevisionsPage,
    type ActionCreateParams as ActionCreateParams,
    type ActionUpdateParams as ActionUpdateParams,
    type ActionListParams as ActionListParams,
    type ActionDeleteParams as ActionDeleteParams,
    type ActionArchiveByFunctionTypeParams as ActionArchiveByFunctionTypeParams,
    type ActionCompleteParams as ActionCompleteParams,
    type ActionCompleteBatchParams as ActionCompleteBatchParams,
    type ActionCreateOrReplaceParams as ActionCreateOrReplaceParams,
    type ActionCreateOrReplaceByFunctionTypeParams as ActionCreateOrReplaceByFunctionTypeParams,
    type ActionGetByFunctionTypeParams as ActionGetByFunctionTypeParams,
    type ActionReadParams as ActionReadParams,
  };

  export {
    Workflows as Workflows,
    type APIAbTestBranchAction as APIAbTestBranchAction,
    type APIActionDataValue as APIActionDataValue,
    type APIAppendObjectPropertyValue as APIAppendObjectPropertyValue,
    type APIAssociationDataSource as APIAssociationDataSource,
    type APIAssociationTimestampDataSource as APIAssociationTimestampDataSource,
    type APIAuthKeyWebhookAuthSettings as APIAuthKeyWebhookAuthSettings,
    type APIBlockedDate as APIBlockedDate,
    type APIConnection as APIConnection,
    type APIContactFlow as APIContactFlow,
    type APIContactFlowCreateRequest as APIContactFlowCreateRequest,
    type APIContactFlowPutRequest as APIContactFlowPutRequest,
    type APIContactPropertyAnchor as APIContactPropertyAnchor,
    type APICustomCodeAction as APICustomCodeAction,
    type APIDailyEnrollmentSchedule as APIDailyEnrollmentSchedule,
    type APIDatasetFieldPropertyFilterDataSource as APIDatasetFieldPropertyFilterDataSource,
    type APIEnrolledArgumentPropertyFilterDataSource as APIEnrolledArgumentPropertyFilterDataSource,
    type APIEnrolledRecordPropertyFilterDataSource as APIEnrolledRecordPropertyFilterDataSource,
    type APIEnrollmentEventPropertyValue as APIEnrollmentEventPropertyValue,
    type APIEnumerationOutputField as APIEnumerationOutputField,
    type APIEventBasedEnrollmentCriteria as APIEventBasedEnrollmentCriteria,
    type APIFetchedObjectPropertyValue as APIFetchedObjectPropertyValue,
    type APIFlow as APIFlow,
    type APIFlowBatchFetchFlowIDCoordinate as APIFlowBatchFetchFlowIDCoordinate,
    type APIFlowBatchFetchMigrationFlowIDCoordinate as APIFlowBatchFetchMigrationFlowIDCoordinate,
    type APIFlowBatchFetchMigrationWorkflowIDCoordinate as APIFlowBatchFetchMigrationWorkflowIDCoordinate,
    type APIFlowBatchInput as APIFlowBatchInput,
    type APIFlowBatchMigrationInput as APIFlowBatchMigrationInput,
    type APIFlowCreateRequest as APIFlowCreateRequest,
    type APIFlowEmailCampaign as APIFlowEmailCampaign,
    type APIFlowListing as APIFlowListing,
    type APIFlowPutRequest as APIFlowPutRequest,
    type APIIncrementValue as APIIncrementValue,
    type APIInputVariable as APIInputVariable,
    type APIListBasedEnrollmentCriteria as APIListBasedEnrollmentCriteria,
    type APIListBranch as APIListBranch,
    type APIListBranchAction as APIListBranchAction,
    type APIManualEnrollmentCriteria as APIManualEnrollmentCriteria,
    type APIMonthlyRelativeDaysEnrollmentSchedule as APIMonthlyRelativeDaysEnrollmentSchedule,
    type APIMonthlySpecificDaysEnrollmentSchedule as APIMonthlySpecificDaysEnrollmentSchedule,
    type APIObjectPropertyValue as APIObjectPropertyValue,
    type APIPlatformFlow as APIPlatformFlow,
    type APIPlatformFlowCreateRequest as APIPlatformFlowCreateRequest,
    type APIPlatformFlowPutRequest as APIPlatformFlowPutRequest,
    type APIPropertyBasedEnrollmentSchedule as APIPropertyBasedEnrollmentSchedule,
    type APIRelativeDateTimeValue as APIRelativeDateTimeValue,
    type APISignatureWebhookAuthSettings as APISignatureWebhookAuthSettings,
    type APISingleConnectionAction as APISingleConnectionAction,
    type APISort as APISort,
    type APIStaticAppendValue as APIStaticAppendValue,
    type APIStaticBranch as APIStaticBranch,
    type APIStaticBranchAction as APIStaticBranchAction,
    type APIStaticDateAnchor as APIStaticDateAnchor,
    type APIStaticPropertyFilterDataSource as APIStaticPropertyFilterDataSource,
    type APIStaticTimeZoneStrategy as APIStaticTimeZoneStrategy,
    type APIStaticValue as APIStaticValue,
    type APITimeDelay as APITimeDelay,
    type APITimeOfDay as APITimeOfDay,
    type APITimestampValue as APITimestampValue,
    type APITimeWindow as APITimeWindow,
    type APIUnEnrollmentSetting as APIUnEnrollmentSetting,
    type APIWebhookAction as APIWebhookAction,
    type APIWeeklyEnrollmentSchedule as APIWeeklyEnrollmentSchedule,
    type APIYearlyEnrollmentSchedule as APIYearlyEnrollmentSchedule,
    type BatchResponseAPIFlow as BatchResponseAPIFlow,
    type BatchResponseAPIFlowWithErrors as BatchResponseAPIFlowWithErrors,
    type BatchResponseFlowIDWorkflowIDMappingResponse as BatchResponseFlowIDWorkflowIDMappingResponse,
    type BatchResponseFlowIDWorkflowIDMappingResponseWithErrors as BatchResponseFlowIDWorkflowIDMappingResponseWithErrors,
    type CollectionResponseAPIFlowEmailCampaign as CollectionResponseAPIFlowEmailCampaign,
    type CollectionResponseAPIFlowListingForwardPaging as CollectionResponseAPIFlowListingForwardPaging,
    type FlowIDWorkflowIDMappingResponse as FlowIDWorkflowIDMappingResponse,
    type PublicAbsoluteComparativeTimestampRefineBy as PublicAbsoluteComparativeTimestampRefineBy,
    type PublicAbsoluteRangedTimestampRefineBy as PublicAbsoluteRangedTimestampRefineBy,
    type PublicAdsSearchFilter as PublicAdsSearchFilter,
    type PublicAdsTimeFilter as PublicAdsTimeFilter,
    type PublicAllHistoryRefineBy as PublicAllHistoryRefineBy,
    type PublicAllPropertyTypesOperation as PublicAllPropertyTypesOperation,
    type PublicAndFilterBranch as PublicAndFilterBranch,
    type PublicAssociationFilterBranch as PublicAssociationFilterBranch,
    type PublicAssociationInListFilter as PublicAssociationInListFilter,
    type PublicBoolPropertyOperation as PublicBoolPropertyOperation,
    type PublicCalendarDatePropertyOperation as PublicCalendarDatePropertyOperation,
    type PublicCampaignInfluencedFilter as PublicCampaignInfluencedFilter,
    type PublicCommunicationSubscriptionFilter as PublicCommunicationSubscriptionFilter,
    type PublicComparativeDatePropertyOperation as PublicComparativeDatePropertyOperation,
    type PublicComparativePropertyUpdatedOperation as PublicComparativePropertyUpdatedOperation,
    type PublicConstantFilter as PublicConstantFilter,
    type PublicCtaAnalyticsFilter as PublicCtaAnalyticsFilter,
    type PublicDatePoint as PublicDatePoint,
    type PublicDatePropertyOperation as PublicDatePropertyOperation,
    type PublicDateTimePropertyOperation as PublicDateTimePropertyOperation,
    type PublicEmailEventFilter as PublicEmailEventFilter,
    type PublicEmailSubscriptionFilter as PublicEmailSubscriptionFilter,
    type PublicEnumerationPropertyOperation as PublicEnumerationPropertyOperation,
    type PublicEventAnalyticsFilter as PublicEventAnalyticsFilter,
    type PublicEventFilterMetadata as PublicEventFilterMetadata,
    type PublicFiscalQuarterReference as PublicFiscalQuarterReference,
    type PublicFiscalYearReference as PublicFiscalYearReference,
    type PublicFormSubmissionFilter as PublicFormSubmissionFilter,
    type PublicFormSubmissionOnPageFilter as PublicFormSubmissionOnPageFilter,
    type PublicIndexedTimePoint as PublicIndexedTimePoint,
    type PublicIndexOffset as PublicIndexOffset,
    type PublicInListFilter as PublicInListFilter,
    type PublicInListFilterMetadata as PublicInListFilterMetadata,
    type PublicIntegrationEventFilter as PublicIntegrationEventFilter,
    type PublicMonthReference as PublicMonthReference,
    type PublicMultiStringPropertyOperation as PublicMultiStringPropertyOperation,
    type PublicNotAllFilterBranch as PublicNotAllFilterBranch,
    type PublicNotAnyFilterBranch as PublicNotAnyFilterBranch,
    type PublicNowReference as PublicNowReference,
    type PublicNumAssociationsFilter as PublicNumAssociationsFilter,
    type PublicNumberPropertyOperation as PublicNumberPropertyOperation,
    type PublicNumOccurrencesRefineBy as PublicNumOccurrencesRefineBy,
    type PublicOrFilterBranch as PublicOrFilterBranch,
    type PublicPageViewAnalyticsFilter as PublicPageViewAnalyticsFilter,
    type PublicPrivacyAnalyticsFilter as PublicPrivacyAnalyticsFilter,
    type PublicPropertyAssociationFilterBranch as PublicPropertyAssociationFilterBranch,
    type PublicPropertyAssociationInListFilter as PublicPropertyAssociationInListFilter,
    type PublicPropertyFilter as PublicPropertyFilter,
    type PublicPropertyReferencedTime as PublicPropertyReferencedTime,
    type PublicQuarterReference as PublicQuarterReference,
    type PublicRangedDatePropertyOperation as PublicRangedDatePropertyOperation,
    type PublicRangedNumberPropertyOperation as PublicRangedNumberPropertyOperation,
    type PublicRangedTimeOperation as PublicRangedTimeOperation,
    type PublicRelativeComparativeTimestampRefineBy as PublicRelativeComparativeTimestampRefineBy,
    type PublicRelativeRangedTimestampRefineBy as PublicRelativeRangedTimestampRefineBy,
    type PublicRestrictedFilterBranch as PublicRestrictedFilterBranch,
    type PublicRollingDateRangePropertyOperation as PublicRollingDateRangePropertyOperation,
    type PublicRollingPropertyUpdatedOperation as PublicRollingPropertyUpdatedOperation,
    type PublicSetOccurrencesRefineBy as PublicSetOccurrencesRefineBy,
    type PublicStringPropertyOperation as PublicStringPropertyOperation,
    type PublicSurveyMonkeyFilter as PublicSurveyMonkeyFilter,
    type PublicSurveyMonkeyValueFilter as PublicSurveyMonkeyValueFilter,
    type PublicTimeOffset as PublicTimeOffset,
    type PublicTimePointOperation as PublicTimePointOperation,
    type PublicTodayReference as PublicTodayReference,
    type PublicUnifiedEventsFilter as PublicUnifiedEventsFilter,
    type PublicUnifiedEventsFilterBranch as PublicUnifiedEventsFilterBranch,
    type PublicWebinarFilter as PublicWebinarFilter,
    type PublicWeekReference as PublicWeekReference,
    type PublicYearReference as PublicYearReference,
  };
}
