// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as WorkflowsAPI from './workflows';
import {
  APIAbTestBranchAction,
  APIActionDataValue,
  APIAppendObjectPropertyValue,
  APIAssociationDataSource,
  APIAssociationTimestampDataSource,
  APIAuthKeyWebhookAuthSettings,
  APIBlockedDate,
  APIConnection,
  APIContactFlow,
  APIContactFlowCreateRequest,
  APIContactFlowPutRequest,
  APIContactPropertyAnchor,
  APICustomCodeAction,
  APIDailyEnrollmentSchedule,
  APIDatasetFieldPropertyFilterDataSource,
  APIEnrolledArgumentPropertyFilterDataSource,
  APIEnrolledRecordPropertyFilterDataSource,
  APIEnrollmentEventPropertyValue,
  APIEnumerationOutputField,
  APIEventBasedEnrollmentCriteria,
  APIFetchedObjectPropertyValue,
  APIFlow,
  APIFlowBatchFetchFlowIDCoordinate,
  APIFlowBatchFetchMigrationFlowIDCoordinate,
  APIFlowBatchFetchMigrationWorkflowIDCoordinate,
  APIFlowBatchInput,
  APIFlowBatchMigrationInput,
  APIFlowCreateRequest,
  APIFlowEmailCampaign,
  APIFlowListing,
  APIFlowListingsPage,
  APIFlowPutRequest,
  APIIncrementValue,
  APIInputVariable,
  APIListBasedEnrollmentCriteria,
  APIListBranch,
  APIListBranchAction,
  APIManualEnrollmentCriteria,
  APIMonthlyRelativeDaysEnrollmentSchedule,
  APIMonthlySpecificDaysEnrollmentSchedule,
  APIObjectPropertyValue,
  APIPlatformFlow,
  APIPlatformFlowCreateRequest,
  APIPlatformFlowPutRequest,
  APIPropertyBasedEnrollmentSchedule,
  APIRelativeDateTimeValue,
  APISignatureWebhookAuthSettings,
  APISingleConnectionAction,
  APISort,
  APIStaticAppendValue,
  APIStaticBranch,
  APIStaticBranchAction,
  APIStaticDateAnchor,
  APIStaticPropertyFilterDataSource,
  APIStaticTimeZoneStrategy,
  APIStaticValue,
  APITimeDelay,
  APITimeOfDay,
  APITimeWindow,
  APITimestampValue,
  APIUnEnrollmentSetting,
  APIWebhookAction,
  APIWeeklyEnrollmentSchedule,
  APIYearlyEnrollmentSchedule,
  BatchResponseAPIFlow,
  BatchResponseAPIFlowWithErrors,
  BatchResponseFlowIDWorkflowIDMappingResponse,
  BatchResponseFlowIDWorkflowIDMappingResponseWithErrors,
  CollectionResponseAPIFlowEmailCampaign,
  CollectionResponseAPIFlowListingForwardPaging,
  FlowIDWorkflowIDMappingResponse,
  WorkflowBatchGetIDMappingsParams,
  WorkflowBatchGetParams,
  WorkflowCreateParams,
  WorkflowListEmailCampaignsParams,
  WorkflowListParams,
  WorkflowUpdateParams,
  Workflows,
} from './workflows';
import * as ActionsAPI from './actions/actions';
import {
  Actions,
  BatchInputCallbackCompletionBatchRequest,
  CallbackCompletionBatchRequest,
  CallbackCompletionRequest,
  CollectionResponsePublicActionDefinitionForwardPaging,
  CollectionResponsePublicActionFunctionIdentifierNoPaging,
  CollectionResponsePublicActionRevisionForwardPaging,
  FieldTypeDefinition,
  InputFieldDefinition,
  Option,
  OutputFieldDefinition,
  PublicActionDefinition,
  PublicActionDefinitionEgg,
  PublicActionDefinitionPatch,
  PublicActionFunction,
  PublicActionFunctionIdentifier,
  PublicActionLabels,
  PublicActionRevision,
  PublicConditionalSingleFieldDependency,
  PublicExecutionTranslationRule,
  PublicObjectRequestOptions,
  PublicSingleFieldDependency,
} from './actions/actions';

export class Automation extends APIResource {
  actions: ActionsAPI.Actions = new ActionsAPI.Actions(this._client);
  workflows: WorkflowsAPI.Workflows = new WorkflowsAPI.Workflows(this._client);
}

Automation.Actions = Actions;
Automation.Workflows = Workflows;

export declare namespace Automation {
  export {
    Actions as Actions,
    type BatchInputCallbackCompletionBatchRequest as BatchInputCallbackCompletionBatchRequest,
    type CallbackCompletionBatchRequest as CallbackCompletionBatchRequest,
    type CallbackCompletionRequest as CallbackCompletionRequest,
    type CollectionResponsePublicActionDefinitionForwardPaging as CollectionResponsePublicActionDefinitionForwardPaging,
    type CollectionResponsePublicActionFunctionIdentifierNoPaging as CollectionResponsePublicActionFunctionIdentifierNoPaging,
    type CollectionResponsePublicActionRevisionForwardPaging as CollectionResponsePublicActionRevisionForwardPaging,
    type FieldTypeDefinition as FieldTypeDefinition,
    type InputFieldDefinition as InputFieldDefinition,
    type Option as Option,
    type OutputFieldDefinition as OutputFieldDefinition,
    type PublicActionDefinition as PublicActionDefinition,
    type PublicActionDefinitionEgg as PublicActionDefinitionEgg,
    type PublicActionDefinitionPatch as PublicActionDefinitionPatch,
    type PublicActionFunction as PublicActionFunction,
    type PublicActionFunctionIdentifier as PublicActionFunctionIdentifier,
    type PublicActionLabels as PublicActionLabels,
    type PublicActionRevision as PublicActionRevision,
    type PublicConditionalSingleFieldDependency as PublicConditionalSingleFieldDependency,
    type PublicExecutionTranslationRule as PublicExecutionTranslationRule,
    type PublicObjectRequestOptions as PublicObjectRequestOptions,
    type PublicSingleFieldDependency as PublicSingleFieldDependency,
  };

  export {
    Workflows as Workflows,
    type APIAbTestBranchAction as APIAbTestBranchAction,
    type APIActionDataValue as APIActionDataValue,
    type APIAppendObjectPropertyValue as APIAppendObjectPropertyValue,
    type APIAssociationDataSource as APIAssociationDataSource,
    type APIAssociationTimestampDataSource as APIAssociationTimestampDataSource,
    type APIAuthKeyWebhookAuthSettings as APIAuthKeyWebhookAuthSettings,
    type APIBlockedDate as APIBlockedDate,
    type APIConnection as APIConnection,
    type APIContactFlow as APIContactFlow,
    type APIContactFlowCreateRequest as APIContactFlowCreateRequest,
    type APIContactFlowPutRequest as APIContactFlowPutRequest,
    type APIContactPropertyAnchor as APIContactPropertyAnchor,
    type APICustomCodeAction as APICustomCodeAction,
    type APIDailyEnrollmentSchedule as APIDailyEnrollmentSchedule,
    type APIDatasetFieldPropertyFilterDataSource as APIDatasetFieldPropertyFilterDataSource,
    type APIEnrolledArgumentPropertyFilterDataSource as APIEnrolledArgumentPropertyFilterDataSource,
    type APIEnrolledRecordPropertyFilterDataSource as APIEnrolledRecordPropertyFilterDataSource,
    type APIEnrollmentEventPropertyValue as APIEnrollmentEventPropertyValue,
    type APIEnumerationOutputField as APIEnumerationOutputField,
    type APIEventBasedEnrollmentCriteria as APIEventBasedEnrollmentCriteria,
    type APIFetchedObjectPropertyValue as APIFetchedObjectPropertyValue,
    type APIFlow as APIFlow,
    type APIFlowBatchFetchFlowIDCoordinate as APIFlowBatchFetchFlowIDCoordinate,
    type APIFlowBatchFetchMigrationFlowIDCoordinate as APIFlowBatchFetchMigrationFlowIDCoordinate,
    type APIFlowBatchFetchMigrationWorkflowIDCoordinate as APIFlowBatchFetchMigrationWorkflowIDCoordinate,
    type APIFlowBatchInput as APIFlowBatchInput,
    type APIFlowBatchMigrationInput as APIFlowBatchMigrationInput,
    type APIFlowCreateRequest as APIFlowCreateRequest,
    type APIFlowEmailCampaign as APIFlowEmailCampaign,
    type APIFlowListing as APIFlowListing,
    type APIFlowPutRequest as APIFlowPutRequest,
    type APIIncrementValue as APIIncrementValue,
    type APIInputVariable as APIInputVariable,
    type APIListBasedEnrollmentCriteria as APIListBasedEnrollmentCriteria,
    type APIListBranch as APIListBranch,
    type APIListBranchAction as APIListBranchAction,
    type APIManualEnrollmentCriteria as APIManualEnrollmentCriteria,
    type APIMonthlyRelativeDaysEnrollmentSchedule as APIMonthlyRelativeDaysEnrollmentSchedule,
    type APIMonthlySpecificDaysEnrollmentSchedule as APIMonthlySpecificDaysEnrollmentSchedule,
    type APIObjectPropertyValue as APIObjectPropertyValue,
    type APIPlatformFlow as APIPlatformFlow,
    type APIPlatformFlowCreateRequest as APIPlatformFlowCreateRequest,
    type APIPlatformFlowPutRequest as APIPlatformFlowPutRequest,
    type APIPropertyBasedEnrollmentSchedule as APIPropertyBasedEnrollmentSchedule,
    type APIRelativeDateTimeValue as APIRelativeDateTimeValue,
    type APISignatureWebhookAuthSettings as APISignatureWebhookAuthSettings,
    type APISingleConnectionAction as APISingleConnectionAction,
    type APISort as APISort,
    type APIStaticAppendValue as APIStaticAppendValue,
    type APIStaticBranch as APIStaticBranch,
    type APIStaticBranchAction as APIStaticBranchAction,
    type APIStaticDateAnchor as APIStaticDateAnchor,
    type APIStaticPropertyFilterDataSource as APIStaticPropertyFilterDataSource,
    type APIStaticTimeZoneStrategy as APIStaticTimeZoneStrategy,
    type APIStaticValue as APIStaticValue,
    type APITimeDelay as APITimeDelay,
    type APITimeOfDay as APITimeOfDay,
    type APITimestampValue as APITimestampValue,
    type APITimeWindow as APITimeWindow,
    type APIUnEnrollmentSetting as APIUnEnrollmentSetting,
    type APIWebhookAction as APIWebhookAction,
    type APIWeeklyEnrollmentSchedule as APIWeeklyEnrollmentSchedule,
    type APIYearlyEnrollmentSchedule as APIYearlyEnrollmentSchedule,
    type BatchResponseAPIFlow as BatchResponseAPIFlow,
    type BatchResponseAPIFlowWithErrors as BatchResponseAPIFlowWithErrors,
    type BatchResponseFlowIDWorkflowIDMappingResponse as BatchResponseFlowIDWorkflowIDMappingResponse,
    type BatchResponseFlowIDWorkflowIDMappingResponseWithErrors as BatchResponseFlowIDWorkflowIDMappingResponseWithErrors,
    type CollectionResponseAPIFlowEmailCampaign as CollectionResponseAPIFlowEmailCampaign,
    type CollectionResponseAPIFlowListingForwardPaging as CollectionResponseAPIFlowListingForwardPaging,
    type FlowIDWorkflowIDMappingResponse as FlowIDWorkflowIDMappingResponse,
    type APIFlowListingsPage as APIFlowListingsPage,
    type WorkflowCreateParams as WorkflowCreateParams,
    type WorkflowUpdateParams as WorkflowUpdateParams,
    type WorkflowListParams as WorkflowListParams,
    type WorkflowBatchGetParams as WorkflowBatchGetParams,
    type WorkflowBatchGetIDMappingsParams as WorkflowBatchGetIDMappingsParams,
    type WorkflowListEmailCampaignsParams as WorkflowListEmailCampaignsParams,
  };
}
