// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as SequencesAPI from './sequences';
import {
  CollectionResponseWithTotalPublicSequenceLiteResponse,
  PublicEmailPatternResponse,
  PublicSequenceEnrollmentLiteResponse,
  PublicSequenceEnrollmentRequest,
  PublicSequenceEnrollmentResponse,
  PublicSequenceLiteResponse,
  PublicSequenceLiteResponsesPage,
  PublicSequenceResponse,
  PublicSequenceSettingsResponse,
  PublicSequenceStepDependencyResponse,
  PublicSequenceStepResponse,
  PublicTaskPatternResponse,
  SequenceCreateEnrollmentParams,
  SequenceGetParams,
  SequenceListParams,
  Sequences,
} from './sequences';
import * as ActionsAPI from './actions/actions';
import {
  ActionExecutionIndexIdentifier,
  Actions,
  AgentRequestContext,
  ArrayFieldSchema,
  BatchInputCallbackCompletionBatchRequest,
  BooleanFieldSchema,
  CallbackCompletionBatchRequest,
  CallbackCompletionRequest,
  ChirpAIContextObject,
  CollectionResponsePublicActionDefinitionForwardPaging,
  CollectionResponsePublicActionFunctionIdentifierNoPaging,
  CollectionResponsePublicActionRevisionForwardPaging,
  ComplianceIDs,
  ContactID,
  CopilotRequestContext,
  DoubleFieldSchema,
  FieldTypeDefinition,
  IntegerFieldSchema,
  LongFieldSchema,
  ObjectFieldSchema,
  OutputFieldDefinition,
  PublicActionDefinition,
  PublicActionDefinitionEgg,
  PublicActionDefinitionPatch,
  PublicActionDefinitionRequiresObjectRequest,
  PublicActionDefinitionRequiresObjectResponse,
  PublicActionFunction,
  PublicActionFunctionIdentifier,
  PublicActionLabels,
  PublicActionRevision,
  PublicConditionalSingleFieldDependency,
  PublicExecutionTranslationRule,
  PublicFieldTypeDefinition,
  PublicInputFieldDefinition,
  PublicObjectRequestOptions,
  PublicOption,
  PublicSingleFieldDependency,
  StandaloneRequestContext,
  StringFieldSchema,
  TestRequestContext,
  WorkflowsRequestContext,
} from './actions/actions';

export class Automation extends APIResource {
  actions: ActionsAPI.Actions = new ActionsAPI.Actions(this._client);
  sequences: SequencesAPI.Sequences = new SequencesAPI.Sequences(this._client);
}

Automation.Actions = Actions;
Automation.Sequences = Sequences;

export declare namespace Automation {
  export {
    Actions as Actions,
    type ActionExecutionIndexIdentifier as ActionExecutionIndexIdentifier,
    type AgentRequestContext as AgentRequestContext,
    type ArrayFieldSchema as ArrayFieldSchema,
    type BatchInputCallbackCompletionBatchRequest as BatchInputCallbackCompletionBatchRequest,
    type BooleanFieldSchema as BooleanFieldSchema,
    type CallbackCompletionBatchRequest as CallbackCompletionBatchRequest,
    type CallbackCompletionRequest as CallbackCompletionRequest,
    type ChirpAIContextObject as ChirpAIContextObject,
    type CollectionResponsePublicActionDefinitionForwardPaging as CollectionResponsePublicActionDefinitionForwardPaging,
    type CollectionResponsePublicActionFunctionIdentifierNoPaging as CollectionResponsePublicActionFunctionIdentifierNoPaging,
    type CollectionResponsePublicActionRevisionForwardPaging as CollectionResponsePublicActionRevisionForwardPaging,
    type ComplianceIDs as ComplianceIDs,
    type ContactID as ContactID,
    type CopilotRequestContext as CopilotRequestContext,
    type DoubleFieldSchema as DoubleFieldSchema,
    type FieldTypeDefinition as FieldTypeDefinition,
    type IntegerFieldSchema as IntegerFieldSchema,
    type LongFieldSchema as LongFieldSchema,
    type ObjectFieldSchema as ObjectFieldSchema,
    type OutputFieldDefinition as OutputFieldDefinition,
    type PublicActionDefinition as PublicActionDefinition,
    type PublicActionDefinitionEgg as PublicActionDefinitionEgg,
    type PublicActionDefinitionPatch as PublicActionDefinitionPatch,
    type PublicActionDefinitionRequiresObjectRequest as PublicActionDefinitionRequiresObjectRequest,
    type PublicActionDefinitionRequiresObjectResponse as PublicActionDefinitionRequiresObjectResponse,
    type PublicActionFunction as PublicActionFunction,
    type PublicActionFunctionIdentifier as PublicActionFunctionIdentifier,
    type PublicActionLabels as PublicActionLabels,
    type PublicActionRevision as PublicActionRevision,
    type PublicConditionalSingleFieldDependency as PublicConditionalSingleFieldDependency,
    type PublicExecutionTranslationRule as PublicExecutionTranslationRule,
    type PublicFieldTypeDefinition as PublicFieldTypeDefinition,
    type PublicInputFieldDefinition as PublicInputFieldDefinition,
    type PublicObjectRequestOptions as PublicObjectRequestOptions,
    type PublicOption as PublicOption,
    type PublicSingleFieldDependency as PublicSingleFieldDependency,
    type StandaloneRequestContext as StandaloneRequestContext,
    type StringFieldSchema as StringFieldSchema,
    type TestRequestContext as TestRequestContext,
    type WorkflowsRequestContext as WorkflowsRequestContext,
  };

  export {
    Sequences as Sequences,
    type CollectionResponseWithTotalPublicSequenceLiteResponse as CollectionResponseWithTotalPublicSequenceLiteResponse,
    type PublicEmailPatternResponse as PublicEmailPatternResponse,
    type PublicSequenceEnrollmentLiteResponse as PublicSequenceEnrollmentLiteResponse,
    type PublicSequenceEnrollmentRequest as PublicSequenceEnrollmentRequest,
    type PublicSequenceEnrollmentResponse as PublicSequenceEnrollmentResponse,
    type PublicSequenceLiteResponse as PublicSequenceLiteResponse,
    type PublicSequenceResponse as PublicSequenceResponse,
    type PublicSequenceSettingsResponse as PublicSequenceSettingsResponse,
    type PublicSequenceStepDependencyResponse as PublicSequenceStepDependencyResponse,
    type PublicSequenceStepResponse as PublicSequenceStepResponse,
    type PublicTaskPatternResponse as PublicTaskPatternResponse,
    type PublicSequenceLiteResponsesPage as PublicSequenceLiteResponsesPage,
    type SequenceListParams as SequenceListParams,
    type SequenceCreateEnrollmentParams as SequenceCreateEnrollmentParams,
    type SequenceGetParams as SequenceGetParams,
  };
}
