// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

export {
  Companies,
  type CompanyCreateParams,
  type CompanyUpdateParams,
  type CompanyListParams,
  type CompanyDeleteParams,
  type CompanyMergeParams,
  type CompanyReadParams,
  type CompanySearchParams,
  type CompanyUpsertParams,
} from './companies';
export {
  Contacts,
  type ContactCreateParams,
  type ContactUpdateParams,
  type ContactListParams,
  type ContactDeleteParams,
  type ContactMergeParams,
  type ContactPurgeParams,
  type ContactReadParams,
  type ContactSearchParams,
  type ContactUpsertParams,
} from './contacts';
export {
  Deals,
  type DealCreateParams,
  type DealUpdateParams,
  type DealListParams,
  type DealMergeParams,
  type DealReadParams,
  type DealSearchParams,
  type DealUpsertParams,
} from './deals/index';
export {
  Objects,
  type CRMObjectsBatchInputSimplePublicObjectBatchInput,
  type CRMObjectsBatchInputSimplePublicObjectBatchInputForCreate,
  type CRMObjectsBatchInputSimplePublicObjectBatchInputUpsert,
  type CRMObjectsBatchInputSimplePublicObjectID,
  type CRMObjectsBatchReadInputSimplePublicObjectID,
  type CRMObjectsBatchResponseSimplePublicObject,
  type CRMObjectsBatchResponseSimplePublicUpsertObject,
  type CRMObjectsCollectionResponseAssociatedID,
  type CRMObjectsCollectionResponseSimplePublicObjectWithAssociations,
  type CRMObjectsCollectionResponseWithTotalSimplePublicObject,
  type CRMObjectsCreatedResponseSimplePublicObject,
  type CRMObjectsFilter,
  type CRMObjectsFilterGroup,
  type CRMObjectsPublicAssociationsForObject,
  type CRMObjectsPublicGdprDeleteInput,
  type CRMObjectsPublicMergeInput,
  type CRMObjectsPublicObjectSearchRequest,
  type CRMObjectsSimplePublicObject,
  type CRMObjectsSimplePublicObjectBatchInput,
  type CRMObjectsSimplePublicObjectBatchInputForCreate,
  type CRMObjectsSimplePublicObjectBatchInputUpsert,
  type CRMObjectsSimplePublicObjectID,
  type CRMObjectsSimplePublicObjectInput,
  type CRMObjectsSimplePublicObjectInputForCreate,
  type CRMObjectsSimplePublicObjectWithAssociations,
  type CRMObjectsSimplePublicUpsertObject,
  type CRMObjectsValueWithTimestamp,
} from './objects';
export {
  Schemas,
  type SchemaCreateParams,
  type SchemaUpdateParams,
  type SchemaListParams,
  type SchemaDeleteParams,
  type SchemaArchiveAssociationParams,
  type SchemaCreateAssociationParams,
} from './schemas';
