// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

export {
  Companies,
  type CompanyCreateParams,
  type CompanyUpdateParams,
  type CompanyListParams,
  type CompanyDeleteParams,
  type CompanyMergeParams,
  type CompanyReadParams,
  type CompanySearchParams,
  type CompanyUpsertParams,
} from './companies';
export {
  Contacts,
  type ContactCreateParams,
  type ContactUpdateParams,
  type ContactListParams,
  type ContactDeleteParams,
  type ContactMergeParams,
  type ContactPurgeParams,
  type ContactReadParams,
  type ContactSearchParams,
  type ContactUpsertParams,
} from './contacts';
export {
  Deals,
  type DealCreateParams,
  type DealUpdateParams,
  type DealListParams,
  type DealMergeParams,
  type DealReadParams,
  type DealSearchParams,
  type DealUpsertParams,
} from './deals/index';
export {
  Objects,
  type BatchInputSimplePublicObjectBatchInput,
  type BatchInputSimplePublicObjectBatchInputForCreate,
  type BatchInputSimplePublicObjectBatchInputUpsert,
  type BatchInputSimplePublicObjectID,
  type BatchReadInputSimplePublicObjectID,
  type BatchResponseSimplePublicObject,
  type BatchResponseSimplePublicUpsertObject,
  type CollectionResponseAssociatedID,
  type CollectionResponseSimplePublicObjectWithAssociations,
  type CollectionResponseWithTotalSimplePublicObject,
  type CreatedResponseSimplePublicObject,
  type Filter,
  type FilterGroup,
  type PublicAssociationsForObject,
  type PublicGdprDeleteInput,
  type PublicMergeInput,
  type PublicObjectSearchRequest,
  type SimplePublicObject,
  type SimplePublicObjectBatchInput,
  type SimplePublicObjectBatchInputForCreate,
  type SimplePublicObjectBatchInputUpsert,
  type SimplePublicObjectID,
  type SimplePublicObjectInput,
  type SimplePublicObjectInputForCreate,
  type SimplePublicObjectWithAssociations,
  type SimplePublicUpsertObject,
  type ValueWithTimestamp,
  type SimplePublicObjectWithAssociationsCursorURLPage,
} from './objects';
export {
  Schemas,
  type AssociationDefinition,
  type AssociationDefinitionEgg,
  type CollectionResponseObjectSchemaNoPaging,
  type ObjectSchema,
  type ObjectSchemaEgg,
  type ObjectTypeDefinition,
  type ObjectTypeDefinitionLabels,
  type ObjectTypeDefinitionPatch,
  type ObjectTypePropertyCreate,
  type OptionInput,
  type SchemaCreateParams,
  type SchemaUpdateParams,
  type SchemaListParams,
  type SchemaDeleteParams,
  type SchemaArchiveAssociationParams,
  type SchemaCreateAssociationParams,
} from './schemas';
