// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as DomainsAPI from './domains';
import {
  CollectionResponseWithTotalDomainForwardPaging,
  Domain,
  DomainListParams,
  Domains,
  DomainsPage,
} from './domains';
import * as HubdbAPI from './hubdb';
import {
  BatchInputHubDBTableRowBatchCloneRequest,
  BatchInputHubDBTableRowV3BatchUpdateRequest,
  BatchInputHubDBTableRowV3Request,
  BatchResponseHubDBTableRowV3,
  BatchResponseHubDBTableRowV3WithErrors,
  BoundedNextPage,
  BoundedPaging,
  CollectionResponseWithTotalHubDBTableV3ForwardPaging,
  Column,
  ColumnRequest,
  ForeignID,
  HubDBTableCloneRequest,
  HubDBTableRowBatchCloneRequest,
  HubDBTableRowV3,
  HubDBTableRowV3BatchUpdateRequest,
  HubDBTableRowV3Request,
  HubDBTableV3,
  HubDBTableV3Request,
  Hubdb,
  HubdbCloneBatchParams,
  HubdbCloneDraftParams,
  HubdbCloneDraftTableParams,
  HubdbCloneDraftTableRowParams,
  HubdbCloneDraftTableRowsParams,
  HubdbCreateBatchParams,
  HubdbCreateDraftTableRowsParams,
  HubdbCreateParams,
  HubdbCreateTableParams,
  HubdbCreateTableRowParams,
  HubdbDeleteDraftParams,
  HubdbDeleteVersionParams,
  HubdbExportDraftParams,
  HubdbExportDraftTableParams,
  HubdbExportParams,
  HubdbExportTableParams,
  HubdbGetAllDraftTablesParams,
  HubdbGetAllTablesParams,
  HubdbGetDraftParams,
  HubdbGetDraftTableDetailsByIDParams,
  HubdbGetDraftTableRowByIDParams,
  HubdbGetParams,
  HubdbGetTableDetailsParams,
  HubdbGetTableRowParams,
  HubdbGetTableRowsParams,
  HubdbImportDraftParams,
  HubdbImportDraftTableParams,
  HubdbListDraftParams,
  HubdbListDraftsParams,
  HubdbListParams,
  HubdbPublishDraftParams,
  HubdbPublishDraftTableParams,
  HubdbPurgeBatchParams,
  HubdbPurgeDraftTableRowParams,
  HubdbPurgeDraftTableRowsParams,
  HubdbReadBatchParams,
  HubdbReadDraftBatchParams,
  HubdbReadDraftTableRowsParams,
  HubdbReadTableRowsParams,
  HubdbRemoveTableVersionParams,
  HubdbReplaceBatchParams,
  HubdbReplaceDraftParams,
  HubdbReplaceDraftTableRowParams,
  HubdbReplaceDraftTableRowsParams,
  HubdbResetDraftParams,
  HubdbResetDraftTableParams,
  HubdbUnpublishParams,
  HubdbUnpublishTableParams,
  HubdbUpdateBatchParams,
  HubdbUpdateDraftParams,
  HubdbUpdateDraftTableParams,
  HubdbUpdateDraftTableRowParams,
  HubdbUpdateDraftTableRowsParams,
  ImportResult,
  Option,
  RandomAccessCollectionResponseWithTotalHubDBTableRowV3,
  SimpleUser,
  StandardError,
  StreamingCollectionResponseWithTotalHubDBTableRowV3,
  UnifiedCollectionResponseWithTotalBaseHubDBTableRowV3,
  Variant,
} from './hubdb';
import * as URLRedirectsAPI from './url-redirects';
import {
  CollectionResponseWithTotalURLMappingForwardPaging,
  URLMapping,
  URLMappingCreateRequestBody,
  URLMappingsPage,
  URLRedirectCreateParams,
  URLRedirectListParams,
  URLRedirectUpdateParams,
  URLRedirects,
} from './url-redirects';
import * as BlogsAPI from './blogs/blogs';
import {
  AttachToLangPrimaryRequestVNext,
  BatchInputJsonNode,
  Blogs,
  DetachFromLangGroupRequestVNext,
  SetNewLanguagePrimaryRequestVNext,
  UpdateLanguagesRequestVNext,
} from './blogs/blogs';

export class Cms extends APIResource {
  blogs: BlogsAPI.Blogs = new BlogsAPI.Blogs(this._client);
  domains: DomainsAPI.Domains = new DomainsAPI.Domains(this._client);
  hubdb: HubdbAPI.Hubdb = new HubdbAPI.Hubdb(this._client);
  urlRedirects: URLRedirectsAPI.URLRedirects = new URLRedirectsAPI.URLRedirects(this._client);
}

Cms.Blogs = Blogs;
Cms.Domains = Domains;
Cms.Hubdb = Hubdb;
Cms.URLRedirects = URLRedirects;

export declare namespace Cms {
  export {
    Blogs as Blogs,
    type AttachToLangPrimaryRequestVNext as AttachToLangPrimaryRequestVNext,
    type BatchInputJsonNode as BatchInputJsonNode,
    type DetachFromLangGroupRequestVNext as DetachFromLangGroupRequestVNext,
    type SetNewLanguagePrimaryRequestVNext as SetNewLanguagePrimaryRequestVNext,
    type UpdateLanguagesRequestVNext as UpdateLanguagesRequestVNext,
  };

  export {
    Domains as Domains,
    type CollectionResponseWithTotalDomainForwardPaging as CollectionResponseWithTotalDomainForwardPaging,
    type Domain as Domain,
    type DomainsPage as DomainsPage,
    type DomainListParams as DomainListParams,
  };

  export {
    Hubdb as Hubdb,
    type BatchInputHubDBTableRowBatchCloneRequest as BatchInputHubDBTableRowBatchCloneRequest,
    type BatchInputHubDBTableRowV3BatchUpdateRequest as BatchInputHubDBTableRowV3BatchUpdateRequest,
    type BatchInputHubDBTableRowV3Request as BatchInputHubDBTableRowV3Request,
    type BatchResponseHubDBTableRowV3 as BatchResponseHubDBTableRowV3,
    type BatchResponseHubDBTableRowV3WithErrors as BatchResponseHubDBTableRowV3WithErrors,
    type BoundedNextPage as BoundedNextPage,
    type BoundedPaging as BoundedPaging,
    type CollectionResponseWithTotalHubDBTableV3ForwardPaging as CollectionResponseWithTotalHubDBTableV3ForwardPaging,
    type Column as Column,
    type ColumnRequest as ColumnRequest,
    type ForeignID as ForeignID,
    type HubDBTableCloneRequest as HubDBTableCloneRequest,
    type HubDBTableRowBatchCloneRequest as HubDBTableRowBatchCloneRequest,
    type HubDBTableRowV3 as HubDBTableRowV3,
    type HubDBTableRowV3BatchUpdateRequest as HubDBTableRowV3BatchUpdateRequest,
    type HubDBTableRowV3Request as HubDBTableRowV3Request,
    type HubDBTableV3 as HubDBTableV3,
    type HubDBTableV3Request as HubDBTableV3Request,
    type ImportResult as ImportResult,
    type Option as Option,
    type RandomAccessCollectionResponseWithTotalHubDBTableRowV3 as RandomAccessCollectionResponseWithTotalHubDBTableRowV3,
    type SimpleUser as SimpleUser,
    type StandardError as StandardError,
    type StreamingCollectionResponseWithTotalHubDBTableRowV3 as StreamingCollectionResponseWithTotalHubDBTableRowV3,
    type UnifiedCollectionResponseWithTotalBaseHubDBTableRowV3 as UnifiedCollectionResponseWithTotalBaseHubDBTableRowV3,
    type Variant as Variant,
    type HubdbCreateParams as HubdbCreateParams,
    type HubdbListParams as HubdbListParams,
    type HubdbCloneBatchParams as HubdbCloneBatchParams,
    type HubdbCloneDraftParams as HubdbCloneDraftParams,
    type HubdbCloneDraftTableParams as HubdbCloneDraftTableParams,
    type HubdbCloneDraftTableRowParams as HubdbCloneDraftTableRowParams,
    type HubdbCloneDraftTableRowsParams as HubdbCloneDraftTableRowsParams,
    type HubdbCreateBatchParams as HubdbCreateBatchParams,
    type HubdbCreateDraftTableRowsParams as HubdbCreateDraftTableRowsParams,
    type HubdbCreateTableParams as HubdbCreateTableParams,
    type HubdbCreateTableRowParams as HubdbCreateTableRowParams,
    type HubdbDeleteDraftParams as HubdbDeleteDraftParams,
    type HubdbDeleteVersionParams as HubdbDeleteVersionParams,
    type HubdbExportParams as HubdbExportParams,
    type HubdbExportDraftParams as HubdbExportDraftParams,
    type HubdbExportDraftTableParams as HubdbExportDraftTableParams,
    type HubdbExportTableParams as HubdbExportTableParams,
    type HubdbGetParams as HubdbGetParams,
    type HubdbGetAllDraftTablesParams as HubdbGetAllDraftTablesParams,
    type HubdbGetAllTablesParams as HubdbGetAllTablesParams,
    type HubdbGetDraftParams as HubdbGetDraftParams,
    type HubdbGetDraftTableDetailsByIDParams as HubdbGetDraftTableDetailsByIDParams,
    type HubdbGetDraftTableRowByIDParams as HubdbGetDraftTableRowByIDParams,
    type HubdbGetTableDetailsParams as HubdbGetTableDetailsParams,
    type HubdbGetTableRowParams as HubdbGetTableRowParams,
    type HubdbGetTableRowsParams as HubdbGetTableRowsParams,
    type HubdbImportDraftParams as HubdbImportDraftParams,
    type HubdbImportDraftTableParams as HubdbImportDraftTableParams,
    type HubdbListDraftParams as HubdbListDraftParams,
    type HubdbListDraftsParams as HubdbListDraftsParams,
    type HubdbPublishDraftParams as HubdbPublishDraftParams,
    type HubdbPublishDraftTableParams as HubdbPublishDraftTableParams,
    type HubdbPurgeBatchParams as HubdbPurgeBatchParams,
    type HubdbPurgeDraftTableRowParams as HubdbPurgeDraftTableRowParams,
    type HubdbPurgeDraftTableRowsParams as HubdbPurgeDraftTableRowsParams,
    type HubdbReadBatchParams as HubdbReadBatchParams,
    type HubdbReadDraftBatchParams as HubdbReadDraftBatchParams,
    type HubdbReadDraftTableRowsParams as HubdbReadDraftTableRowsParams,
    type HubdbReadTableRowsParams as HubdbReadTableRowsParams,
    type HubdbRemoveTableVersionParams as HubdbRemoveTableVersionParams,
    type HubdbReplaceBatchParams as HubdbReplaceBatchParams,
    type HubdbReplaceDraftParams as HubdbReplaceDraftParams,
    type HubdbReplaceDraftTableRowParams as HubdbReplaceDraftTableRowParams,
    type HubdbReplaceDraftTableRowsParams as HubdbReplaceDraftTableRowsParams,
    type HubdbResetDraftParams as HubdbResetDraftParams,
    type HubdbResetDraftTableParams as HubdbResetDraftTableParams,
    type HubdbUnpublishParams as HubdbUnpublishParams,
    type HubdbUnpublishTableParams as HubdbUnpublishTableParams,
    type HubdbUpdateBatchParams as HubdbUpdateBatchParams,
    type HubdbUpdateDraftParams as HubdbUpdateDraftParams,
    type HubdbUpdateDraftTableParams as HubdbUpdateDraftTableParams,
    type HubdbUpdateDraftTableRowParams as HubdbUpdateDraftTableRowParams,
    type HubdbUpdateDraftTableRowsParams as HubdbUpdateDraftTableRowsParams,
  };

  export {
    URLRedirects as URLRedirects,
    type CollectionResponseWithTotalURLMappingForwardPaging as CollectionResponseWithTotalURLMappingForwardPaging,
    type URLMapping as URLMapping,
    type URLMappingCreateRequestBody as URLMappingCreateRequestBody,
    type URLMappingsPage as URLMappingsPage,
    type URLRedirectCreateParams as URLRedirectCreateParams,
    type URLRedirectUpdateParams as URLRedirectUpdateParams,
    type URLRedirectListParams as URLRedirectListParams,
  };
}
