// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as AuditLogsAPI from './audit-logs';
import {
  AuditLogExportParams,
  AuditLogListParams,
  AuditLogs,
  CmsAuditLoggingExportFilters,
  CmsAuditLoggingExportSettings,
  CollectionResponsePublicAuditLog,
  PublicAuditLog,
  PublicAuditLogsPage,
} from './audit-logs';
import * as DomainsAPI from './domains';
import { CollectionResponseWithTotalDomain, Domain, DomainListParams, Domains, DomainsPage } from './domains';
import * as SiteSearchAPI from './site-search';
import {
  ContentSearchResult,
  IndexedData,
  IndexedField,
  PublicSearchResults,
  SiteSearch,
  SiteSearchGetIndexedDataParams,
  SiteSearchSearchParams,
} from './site-search';
import * as SourceCodeAPI from './source-code';
import {
  AssetFileMetadata,
  FileExtractRequest,
  SourceCode,
  SourceCodeCreateParams,
  SourceCodeDeleteParams,
  SourceCodeExtractAsyncParams,
  SourceCodeGetMetadataParams,
  SourceCodeGetParams,
  SourceCodeUpsertParams,
  SourceCodeValidateParams,
} from './source-code';
import * as URLMappingsAPI from './url-mappings';
import { URLMappingCreateParams, URLMappings, URLMappingsURLMapping } from './url-mappings';
import * as URLRedirectsAPI from './url-redirects';
import {
  CollectionResponseWithTotalURLMappingForwardPaging,
  URLMapping,
  URLMappingCreateRequestBody,
  URLMappingsPage,
  URLRedirectCreateParams,
  URLRedirectListParams,
  URLRedirectUpdateParams,
  URLRedirects,
} from './url-redirects';
import * as BlogsAPI from './blogs/blogs';
import {
  AttachToLangPrimaryRequestVNext,
  BatchInputJsonNode,
  Blogs,
  DetachFromLangGroupRequestVNext,
  PublicAccessRule,
  SetNewLanguagePrimaryRequestVNext,
  UpdateLanguagesRequestVNext,
} from './blogs/blogs';
import * as MediaBridgeAPI from './media-bridge/media-bridge';
import {
  AbsoluteValue,
  AddNumbers,
  AddTime,
  And,
  AttentionSpanCalculatedValues,
  AttentionSpanEventRequest,
  BeginsWith,
  BooleanPropertyVariable,
  BooleanTargetPropertyVariable,
  BulkIntegratorObjectCreationResponse,
  CaseChangeTestExtensionData,
  CollectionResponseMediaBridgeObjectForwardPaging,
  ConcatStrings,
  ConstantBoolean,
  ConstantNumber,
  ConstantString,
  Contains,
  CreateAudioObjectRequest,
  CreateDocumentObjectRequest,
  CreateImageObjectRequest,
  CreateMBObjectRequest,
  CreateOtherObjectRequest,
  CreateVideoObjectRequest,
  Date,
  DatedExchangeRate,
  DefaultRequirements,
  DefinitionSource,
  DivideNumbers,
  Endpoints,
  Euler,
  EventVisibilityChange,
  EventVisibilityResponse,
  ExtensionData,
  ExternalOptionsMetaData,
  ExtractMostRecentEmailReplyHTML,
  ExtractMostRecentEmailReplyText,
  ExtractMostRecentPlainTextEmailReply,
  FetchCurrencyDecimalPlaces,
  FetchExchangeRate,
  FetchSingleCurrencyPortalCurrency,
  FieldLevelPermission,
  FilteringMetaData,
  FormatFullName,
  FormatPhoneNumber,
  FormatSearchablePhoneNumber,
  Group,
  GroupView,
  HasEmailReply,
  HasPlainTextEmailReply,
  IfBoolean,
  IfNumber,
  IfString,
  InboundDBObjectType,
  IntegratorOEmbedDomainModel,
  IntegratorOEmbedDomainRequest,
  IntegratorObjectCreationRequest,
  IntegratorObjectCreationResponse,
  IsEngagementType,
  IsPipelineStageClosed,
  IsPresent,
  LessThan,
  LessThanOrEqual,
  LowerCase,
  MaxNumbers,
  MediaBridge,
  MediaBridgeCreateAssociationParams,
  MediaBridgeCreateAttentionSpanEventParams,
  MediaBridgeCreateMediaPlayedEventParams,
  MediaBridgeCreateMediaPlayedPercentEventParams,
  MediaBridgeCreateObjectTypeParams,
  MediaBridgeCreateOembedDomainParams,
  MediaBridgeCreateParams,
  MediaBridgeCreatePropertyGroupParams,
  MediaBridgeCreatePropertyParams,
  MediaBridgeDeleteAssociationParams,
  MediaBridgeDeleteOembedDomainParams,
  MediaBridgeDeleteParams,
  MediaBridgeDeletePropertyGroupParams,
  MediaBridgeDeletePropertyParams,
  MediaBridgeGetOembedDomainParams,
  MediaBridgeGetParams,
  MediaBridgeGetPropertyGroupParams,
  MediaBridgeGetPropertyParams,
  MediaBridgeGetSchemaParams,
  MediaBridgeListObjectTypesByMediaTypeParams,
  MediaBridgeListOembedDomainsParams,
  MediaBridgeListParams,
  MediaBridgeListPropertiesParams,
  MediaBridgeListPropertyGroupsParams,
  MediaBridgeListSchemasParams,
  MediaBridgeObject,
  MediaBridgeObjectsPage,
  MediaBridgePropertyUpdate,
  MediaBridgeProviderPartial,
  MediaBridgeProviderRegistrationResponse,
  MediaBridgeRegisterAppNameParams,
  MediaBridgeUpdateEventVisibilitySettingsParams,
  MediaBridgeUpdateOembedDomainParams,
  MediaBridgeUpdateParams,
  MediaBridgeUpdatePropertyGroupParams,
  MediaBridgeUpdatePropertyParams,
  MediaBridgeUpdateSchemaParams,
  MediaBridgeUpdateSettingsParams,
  MediaPlayedEventRequest,
  MediaPlayedPercentageEventRequest,
  MinNumbers,
  Month,
  MoreThan,
  MoreThanOrEqual,
  MultiplyNumbers,
  Not,
  Now,
  NumberEquals,
  NumberPropertyVariable,
  NumberTargetPropertyVariable,
  NumberToString,
  OEmbedDomainsCollectionResponse,
  ObjectDefinitionResponse,
  ObjectTypeIDProto,
  Option1,
  OptionDecorations,
  OptionDecoratorsExtensionData,
  Or,
  ParseNumber,
  PeriodToMonths,
  PeriodToWeeks,
  PipelineProbability,
  Power,
  Property,
  Property1,
  PropertyDefinition,
  PropertyDefinitionSource,
  RequiredPropertiesExtensionData,
  RollupExpression,
  RoundDownNumbers,
  RoundNearestNumbers,
  RoundUpNumbers,
  ScopeMapping,
  SetContainsString,
  SoftRequiredPropertiesExtensionData,
  SquareRoot,
  StringEquals,
  StringLength,
  StringPropertyVariable,
  StringTargetPropertyVariable,
  Substring,
  SubtractNumbers,
  SubtractTime,
  TimeBetween,
  TimeBetweenSkipWeekends,
  TimestampOfPropertyVariable,
  TimestampOfTargetPropertyVariable,
  UpdateAudioObjectRequest,
  UpdateDocumentObjectRequest,
  UpdateImageObjectRequest,
  UpdateMBObjectRequest,
  UpdateOtherObjectRequest,
  UpdateVideoObjectRequest,
  UpperCase,
  VideoObject,
  Xor,
  Year,
} from './media-bridge/media-bridge';

export class Cms extends APIResource {
  auditLogs: AuditLogsAPI.AuditLogs = new AuditLogsAPI.AuditLogs(this._client);
  blogs: BlogsAPI.Blogs = new BlogsAPI.Blogs(this._client);
  domains: DomainsAPI.Domains = new DomainsAPI.Domains(this._client);
  mediaBridge: MediaBridgeAPI.MediaBridge = new MediaBridgeAPI.MediaBridge(this._client);
  siteSearch: SiteSearchAPI.SiteSearch = new SiteSearchAPI.SiteSearch(this._client);
  sourceCode: SourceCodeAPI.SourceCode = new SourceCodeAPI.SourceCode(this._client);
  urlMappings: URLMappingsAPI.URLMappings = new URLMappingsAPI.URLMappings(this._client);
  urlRedirects: URLRedirectsAPI.URLRedirects = new URLRedirectsAPI.URLRedirects(this._client);
}

Cms.AuditLogs = AuditLogs;
Cms.Blogs = Blogs;
Cms.Domains = Domains;
Cms.MediaBridge = MediaBridge;
Cms.SiteSearch = SiteSearch;
Cms.SourceCode = SourceCode;
Cms.URLMappings = URLMappings;
Cms.URLRedirects = URLRedirects;

export declare namespace Cms {
  export {
    AuditLogs as AuditLogs,
    type CmsAuditLoggingExportFilters as CmsAuditLoggingExportFilters,
    type CmsAuditLoggingExportSettings as CmsAuditLoggingExportSettings,
    type CollectionResponsePublicAuditLog as CollectionResponsePublicAuditLog,
    type PublicAuditLog as PublicAuditLog,
    type PublicAuditLogsPage as PublicAuditLogsPage,
    type AuditLogListParams as AuditLogListParams,
    type AuditLogExportParams as AuditLogExportParams,
  };

  export {
    Blogs as Blogs,
    type AttachToLangPrimaryRequestVNext as AttachToLangPrimaryRequestVNext,
    type BatchInputJsonNode as BatchInputJsonNode,
    type DetachFromLangGroupRequestVNext as DetachFromLangGroupRequestVNext,
    type PublicAccessRule as PublicAccessRule,
    type SetNewLanguagePrimaryRequestVNext as SetNewLanguagePrimaryRequestVNext,
    type UpdateLanguagesRequestVNext as UpdateLanguagesRequestVNext,
  };

  export {
    Domains as Domains,
    type CollectionResponseWithTotalDomain as CollectionResponseWithTotalDomain,
    type Domain as Domain,
    type DomainsPage as DomainsPage,
    type DomainListParams as DomainListParams,
  };

  export {
    MediaBridge as MediaBridge,
    type AbsoluteValue as AbsoluteValue,
    type AddNumbers as AddNumbers,
    type AddTime as AddTime,
    type And as And,
    type AttentionSpanCalculatedValues as AttentionSpanCalculatedValues,
    type AttentionSpanEventRequest as AttentionSpanEventRequest,
    type BeginsWith as BeginsWith,
    type BooleanPropertyVariable as BooleanPropertyVariable,
    type BooleanTargetPropertyVariable as BooleanTargetPropertyVariable,
    type BulkIntegratorObjectCreationResponse as BulkIntegratorObjectCreationResponse,
    type CaseChangeTestExtensionData as CaseChangeTestExtensionData,
    type CollectionResponseMediaBridgeObjectForwardPaging as CollectionResponseMediaBridgeObjectForwardPaging,
    type ConcatStrings as ConcatStrings,
    type ConstantBoolean as ConstantBoolean,
    type ConstantNumber as ConstantNumber,
    type ConstantString as ConstantString,
    type Contains as Contains,
    type CreateAudioObjectRequest as CreateAudioObjectRequest,
    type CreateDocumentObjectRequest as CreateDocumentObjectRequest,
    type CreateImageObjectRequest as CreateImageObjectRequest,
    type CreateMBObjectRequest as CreateMBObjectRequest,
    type CreateOtherObjectRequest as CreateOtherObjectRequest,
    type CreateVideoObjectRequest as CreateVideoObjectRequest,
    type Date as Date,
    type DatedExchangeRate as DatedExchangeRate,
    type DefaultRequirements as DefaultRequirements,
    type DefinitionSource as DefinitionSource,
    type DivideNumbers as DivideNumbers,
    type Endpoints as Endpoints,
    type Euler as Euler,
    type EventVisibilityChange as EventVisibilityChange,
    type EventVisibilityResponse as EventVisibilityResponse,
    type ExtensionData as ExtensionData,
    type ExternalOptionsMetaData as ExternalOptionsMetaData,
    type ExtractMostRecentEmailReplyHTML as ExtractMostRecentEmailReplyHTML,
    type ExtractMostRecentEmailReplyText as ExtractMostRecentEmailReplyText,
    type ExtractMostRecentPlainTextEmailReply as ExtractMostRecentPlainTextEmailReply,
    type FetchCurrencyDecimalPlaces as FetchCurrencyDecimalPlaces,
    type FetchExchangeRate as FetchExchangeRate,
    type FetchSingleCurrencyPortalCurrency as FetchSingleCurrencyPortalCurrency,
    type FieldLevelPermission as FieldLevelPermission,
    type FilteringMetaData as FilteringMetaData,
    type FormatFullName as FormatFullName,
    type FormatPhoneNumber as FormatPhoneNumber,
    type FormatSearchablePhoneNumber as FormatSearchablePhoneNumber,
    type Group as Group,
    type GroupView as GroupView,
    type HasEmailReply as HasEmailReply,
    type HasPlainTextEmailReply as HasPlainTextEmailReply,
    type IfBoolean as IfBoolean,
    type IfNumber as IfNumber,
    type IfString as IfString,
    type InboundDBObjectType as InboundDBObjectType,
    type IntegratorOEmbedDomainModel as IntegratorOEmbedDomainModel,
    type IntegratorOEmbedDomainRequest as IntegratorOEmbedDomainRequest,
    type IntegratorObjectCreationRequest as IntegratorObjectCreationRequest,
    type IntegratorObjectCreationResponse as IntegratorObjectCreationResponse,
    type IsEngagementType as IsEngagementType,
    type IsPipelineStageClosed as IsPipelineStageClosed,
    type IsPresent as IsPresent,
    type LessThan as LessThan,
    type LessThanOrEqual as LessThanOrEqual,
    type LowerCase as LowerCase,
    type MaxNumbers as MaxNumbers,
    type MediaBridgeObject as MediaBridgeObject,
    type MediaBridgePropertyUpdate as MediaBridgePropertyUpdate,
    type MediaBridgeProviderPartial as MediaBridgeProviderPartial,
    type MediaBridgeProviderRegistrationResponse as MediaBridgeProviderRegistrationResponse,
    type MediaPlayedEventRequest as MediaPlayedEventRequest,
    type MediaPlayedPercentageEventRequest as MediaPlayedPercentageEventRequest,
    type MinNumbers as MinNumbers,
    type Month as Month,
    type MoreThan as MoreThan,
    type MoreThanOrEqual as MoreThanOrEqual,
    type MultiplyNumbers as MultiplyNumbers,
    type Not as Not,
    type Now as Now,
    type NumberEquals as NumberEquals,
    type NumberPropertyVariable as NumberPropertyVariable,
    type NumberTargetPropertyVariable as NumberTargetPropertyVariable,
    type NumberToString as NumberToString,
    type OEmbedDomainsCollectionResponse as OEmbedDomainsCollectionResponse,
    type ObjectDefinitionResponse as ObjectDefinitionResponse,
    type ObjectTypeIDProto as ObjectTypeIDProto,
    type Option1 as Option1,
    type OptionDecorations as OptionDecorations,
    type OptionDecoratorsExtensionData as OptionDecoratorsExtensionData,
    type Or as Or,
    type ParseNumber as ParseNumber,
    type PeriodToMonths as PeriodToMonths,
    type PeriodToWeeks as PeriodToWeeks,
    type PipelineProbability as PipelineProbability,
    type Power as Power,
    type Property as Property,
    type Property1 as Property1,
    type PropertyDefinition as PropertyDefinition,
    type PropertyDefinitionSource as PropertyDefinitionSource,
    type RequiredPropertiesExtensionData as RequiredPropertiesExtensionData,
    type RollupExpression as RollupExpression,
    type RoundDownNumbers as RoundDownNumbers,
    type RoundNearestNumbers as RoundNearestNumbers,
    type RoundUpNumbers as RoundUpNumbers,
    type ScopeMapping as ScopeMapping,
    type SetContainsString as SetContainsString,
    type SoftRequiredPropertiesExtensionData as SoftRequiredPropertiesExtensionData,
    type SquareRoot as SquareRoot,
    type StringEquals as StringEquals,
    type StringLength as StringLength,
    type StringPropertyVariable as StringPropertyVariable,
    type StringTargetPropertyVariable as StringTargetPropertyVariable,
    type Substring as Substring,
    type SubtractNumbers as SubtractNumbers,
    type SubtractTime as SubtractTime,
    type TimeBetween as TimeBetween,
    type TimeBetweenSkipWeekends as TimeBetweenSkipWeekends,
    type TimestampOfPropertyVariable as TimestampOfPropertyVariable,
    type TimestampOfTargetPropertyVariable as TimestampOfTargetPropertyVariable,
    type UpdateAudioObjectRequest as UpdateAudioObjectRequest,
    type UpdateDocumentObjectRequest as UpdateDocumentObjectRequest,
    type UpdateImageObjectRequest as UpdateImageObjectRequest,
    type UpdateMBObjectRequest as UpdateMBObjectRequest,
    type UpdateOtherObjectRequest as UpdateOtherObjectRequest,
    type UpdateVideoObjectRequest as UpdateVideoObjectRequest,
    type UpperCase as UpperCase,
    type VideoObject as VideoObject,
    type Xor as Xor,
    type Year as Year,
    type MediaBridgeObjectsPage as MediaBridgeObjectsPage,
    type MediaBridgeCreateParams as MediaBridgeCreateParams,
    type MediaBridgeUpdateParams as MediaBridgeUpdateParams,
    type MediaBridgeListParams as MediaBridgeListParams,
    type MediaBridgeDeleteParams as MediaBridgeDeleteParams,
    type MediaBridgeCreateAssociationParams as MediaBridgeCreateAssociationParams,
    type MediaBridgeCreateAttentionSpanEventParams as MediaBridgeCreateAttentionSpanEventParams,
    type MediaBridgeCreateMediaPlayedEventParams as MediaBridgeCreateMediaPlayedEventParams,
    type MediaBridgeCreateMediaPlayedPercentEventParams as MediaBridgeCreateMediaPlayedPercentEventParams,
    type MediaBridgeCreateObjectTypeParams as MediaBridgeCreateObjectTypeParams,
    type MediaBridgeCreateOembedDomainParams as MediaBridgeCreateOembedDomainParams,
    type MediaBridgeCreatePropertyParams as MediaBridgeCreatePropertyParams,
    type MediaBridgeCreatePropertyGroupParams as MediaBridgeCreatePropertyGroupParams,
    type MediaBridgeDeleteAssociationParams as MediaBridgeDeleteAssociationParams,
    type MediaBridgeDeleteOembedDomainParams as MediaBridgeDeleteOembedDomainParams,
    type MediaBridgeDeletePropertyParams as MediaBridgeDeletePropertyParams,
    type MediaBridgeDeletePropertyGroupParams as MediaBridgeDeletePropertyGroupParams,
    type MediaBridgeGetParams as MediaBridgeGetParams,
    type MediaBridgeGetOembedDomainParams as MediaBridgeGetOembedDomainParams,
    type MediaBridgeGetPropertyParams as MediaBridgeGetPropertyParams,
    type MediaBridgeGetPropertyGroupParams as MediaBridgeGetPropertyGroupParams,
    type MediaBridgeGetSchemaParams as MediaBridgeGetSchemaParams,
    type MediaBridgeListObjectTypesByMediaTypeParams as MediaBridgeListObjectTypesByMediaTypeParams,
    type MediaBridgeListOembedDomainsParams as MediaBridgeListOembedDomainsParams,
    type MediaBridgeListPropertiesParams as MediaBridgeListPropertiesParams,
    type MediaBridgeListPropertyGroupsParams as MediaBridgeListPropertyGroupsParams,
    type MediaBridgeListSchemasParams as MediaBridgeListSchemasParams,
    type MediaBridgeRegisterAppNameParams as MediaBridgeRegisterAppNameParams,
    type MediaBridgeUpdateEventVisibilitySettingsParams as MediaBridgeUpdateEventVisibilitySettingsParams,
    type MediaBridgeUpdateOembedDomainParams as MediaBridgeUpdateOembedDomainParams,
    type MediaBridgeUpdatePropertyParams as MediaBridgeUpdatePropertyParams,
    type MediaBridgeUpdatePropertyGroupParams as MediaBridgeUpdatePropertyGroupParams,
    type MediaBridgeUpdateSchemaParams as MediaBridgeUpdateSchemaParams,
    type MediaBridgeUpdateSettingsParams as MediaBridgeUpdateSettingsParams,
  };

  export {
    SiteSearch as SiteSearch,
    type ContentSearchResult as ContentSearchResult,
    type IndexedData as IndexedData,
    type IndexedField as IndexedField,
    type PublicSearchResults as PublicSearchResults,
    type SiteSearchGetIndexedDataParams as SiteSearchGetIndexedDataParams,
    type SiteSearchSearchParams as SiteSearchSearchParams,
  };

  export {
    SourceCode as SourceCode,
    type AssetFileMetadata as AssetFileMetadata,
    type FileExtractRequest as FileExtractRequest,
    type SourceCodeCreateParams as SourceCodeCreateParams,
    type SourceCodeDeleteParams as SourceCodeDeleteParams,
    type SourceCodeExtractAsyncParams as SourceCodeExtractAsyncParams,
    type SourceCodeGetParams as SourceCodeGetParams,
    type SourceCodeGetMetadataParams as SourceCodeGetMetadataParams,
    type SourceCodeUpsertParams as SourceCodeUpsertParams,
    type SourceCodeValidateParams as SourceCodeValidateParams,
  };

  export {
    URLMappings as URLMappings,
    type URLMappingsURLMapping as URLMappingsURLMapping,
    type URLMappingCreateParams as URLMappingCreateParams,
  };

  export {
    URLRedirects as URLRedirects,
    type CollectionResponseWithTotalURLMappingForwardPaging as CollectionResponseWithTotalURLMappingForwardPaging,
    type URLMapping as URLMapping,
    type URLMappingCreateRequestBody as URLMappingCreateRequestBody,
    type URLMappingsPage as URLMappingsPage,
    type URLRedirectCreateParams as URLRedirectCreateParams,
    type URLRedirectUpdateParams as URLRedirectUpdateParams,
    type URLRedirectListParams as URLRedirectListParams,
  };
}
