// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as ObjectsAPI from './objects/objects';
import {
  AssociatedID,
  AssociationSpec,
  AssociationSpecWithLabel,
  BatchInputSimplePublicObjectBatchInput,
  BatchInputSimplePublicObjectBatchInputForCreate,
  BatchInputSimplePublicObjectBatchInputUpsert,
  BatchInputSimplePublicObjectID,
  BatchReadInputSimplePublicObjectID,
  BatchResponsePublicDefaultAssociation,
  BatchResponseSimplePublicObject,
  BatchResponseSimplePublicUpsertObject,
  CollectionResponseAssociatedID,
  CollectionResponseMultiAssociatedObjectWithLabelForwardPaging,
  CollectionResponseSimplePublicObjectWithAssociationsForwardPaging,
  CollectionResponseWithTotalSimplePublicObject,
  Filter,
  FilterGroup,
  LabelsBetweenObjectPair,
  MultiAssociatedObjectWithLabel,
  Objects,
  Paging,
  PreviousPage,
  PublicAssociationsForObject,
  PublicDefaultAssociation,
  PublicGdprDeleteInput,
  PublicMergeInput,
  PublicObjectID,
  PublicObjectSearchRequest,
  SimplePublicObject,
  SimplePublicObjectBatchInput,
  SimplePublicObjectBatchInputForCreate,
  SimplePublicObjectBatchInputUpsert,
  SimplePublicObjectID,
  SimplePublicObjectInput,
  SimplePublicObjectInputForCreate,
  SimplePublicObjectWithAssociations,
  SimplePublicUpsertObject,
  StandardError,
  ValueWithTimestamp,
} from './objects/objects';

export class Crm extends APIResource {
  objects: ObjectsAPI.Objects = new ObjectsAPI.Objects(this._client);
}

Crm.Objects = Objects;

export declare namespace Crm {
  export {
    Objects as Objects,
    type AssociatedID as AssociatedID,
    type AssociationSpec as AssociationSpec,
    type AssociationSpecWithLabel as AssociationSpecWithLabel,
    type BatchInputSimplePublicObjectBatchInput as BatchInputSimplePublicObjectBatchInput,
    type BatchInputSimplePublicObjectBatchInputForCreate as BatchInputSimplePublicObjectBatchInputForCreate,
    type BatchInputSimplePublicObjectBatchInputUpsert as BatchInputSimplePublicObjectBatchInputUpsert,
    type BatchInputSimplePublicObjectID as BatchInputSimplePublicObjectID,
    type BatchReadInputSimplePublicObjectID as BatchReadInputSimplePublicObjectID,
    type BatchResponsePublicDefaultAssociation as BatchResponsePublicDefaultAssociation,
    type BatchResponseSimplePublicObject as BatchResponseSimplePublicObject,
    type BatchResponseSimplePublicUpsertObject as BatchResponseSimplePublicUpsertObject,
    type CollectionResponseAssociatedID as CollectionResponseAssociatedID,
    type CollectionResponseMultiAssociatedObjectWithLabelForwardPaging as CollectionResponseMultiAssociatedObjectWithLabelForwardPaging,
    type CollectionResponseSimplePublicObjectWithAssociationsForwardPaging as CollectionResponseSimplePublicObjectWithAssociationsForwardPaging,
    type CollectionResponseWithTotalSimplePublicObject as CollectionResponseWithTotalSimplePublicObject,
    type Filter as Filter,
    type FilterGroup as FilterGroup,
    type LabelsBetweenObjectPair as LabelsBetweenObjectPair,
    type MultiAssociatedObjectWithLabel as MultiAssociatedObjectWithLabel,
    type Paging as Paging,
    type PreviousPage as PreviousPage,
    type PublicAssociationsForObject as PublicAssociationsForObject,
    type PublicDefaultAssociation as PublicDefaultAssociation,
    type PublicGdprDeleteInput as PublicGdprDeleteInput,
    type PublicMergeInput as PublicMergeInput,
    type PublicObjectID as PublicObjectID,
    type PublicObjectSearchRequest as PublicObjectSearchRequest,
    type SimplePublicObject as SimplePublicObject,
    type SimplePublicObjectBatchInput as SimplePublicObjectBatchInput,
    type SimplePublicObjectBatchInputForCreate as SimplePublicObjectBatchInputForCreate,
    type SimplePublicObjectBatchInputUpsert as SimplePublicObjectBatchInputUpsert,
    type SimplePublicObjectID as SimplePublicObjectID,
    type SimplePublicObjectInput as SimplePublicObjectInput,
    type SimplePublicObjectInputForCreate as SimplePublicObjectInputForCreate,
    type SimplePublicObjectWithAssociations as SimplePublicObjectWithAssociations,
    type SimplePublicUpsertObject as SimplePublicUpsertObject,
    type StandardError as StandardError,
    type ValueWithTimestamp as ValueWithTimestamp,
  };
}
